### ISSUE TITLE
How can i upgrade react-native-tvos version

### ISSUE THREAD

**Issue by mehthabux** [react-native-tvos/react-native-tvos#105]
## Description
How can i upgrade the react-native-tvos version. Im currently having npm:react-native-tvos@0.62.2-1, i need to update to latest version. Should i follow the react native upgrade helper?

**Comment by dlowder-salesforce** [comment]
I have not tried it, but I think it should work. If you hit any problems please add a comment here.

**Comment by mehthabux** [comment]
Hey @dlowder-salesforce , the react native helper worked !!!!

but i encountered an issue with Flipper , 

`The platform of the target `SharekLiveTV-tvOS` (tvOS 12.0) is not compatible with `FlipperKit/FlipperKitReactPlugin (0.41.5)`, which does not support `tvOS`.`

When i disabled flipper and commented out flipper in AppDelegate.m, the build ran successfully.
Do you have any fix for this ?

Thanks

**Comment by dlowder-salesforce** [comment]
See https://github.com/react-native-community/react-native-tvos/blob/tvos-v0.63.1/template/ios/Podfile for the correct way to get Flipper support in tvOS.
