### ISSUE TITLE
Images not showing in tvOS 14?

### ISSUE THREAD

**Issue by olafurnsig** [react-native-tvos/react-native-tvos#108]
## Description
Just updated my test apple tv device to tvOS 14.0 and it seems that all <Image> are not rendering at all?

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 138.16 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.17.0 - /usr/local/opt/node@10/bin/node
    Yarn: 1.13.0 - ~/.nvm/versions/node/v8.10.0/bin/yarn
    npm: 6.11.3 - /usr/local/opt/node@10/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 24, 26, 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-27 | Android TV Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-Q | Android TV Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_131 - /usr/bin/javac
    Python: 2.7.13 - /Library/Frameworks/Python.framework/Versions/2.7/bin/python
  npmPackages:
    @react-native-community/cli: ^4.10.0 => 4.12.0 
    react: ^16.11.0 => 16.13.1 
    react-native: Not Found
    react-native-tvos:  0.63.1-0 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Run app on real apple tv device on tvOS 14.0

## Expected Results
Images should render

**Comment by olafurnsig** [comment]
Related to this react-native issue?

[Image cannot show image in iOS 14 #29279](https://github.com/facebook/react-native/issues/29279)

**Comment by dlowder-salesforce** [comment]
@olafurnsig thanks for the heads up.  I'll merge the core commit (https://github.com/facebook/react-native/commit/123423c2a9258c9af25ca9bffe1f10c42a176bf3) to the current release branch.

**Comment by dlowder-salesforce** [comment]
Fix is merged to the tvos-v0.63.1 branch, and will go out with the next release.  I've tested it with the RNTester project and verified that it works.

**Comment by iamcam** [comment]
@dlowder-salesforce When can we expect a release to NPM? I was mistakenly pointing to the NPM 0.63.1-1 source and wondering why it wasn't working - I had to switch to https to resolve the image loading issue.

**Comment by dlowder-salesforce** [comment]
Fixed in https://github.com/react-native-tvos/react-native-tvos/releases/tag/v0.63.1-2
