### ISSUE TITLE
multiline TextInput in tvOS is not getting focused

### ISSUE THREAD

**Issue by mehthabux** [react-native-tvos/react-native-tvos#109]
## Description
I tried adding a multiline TextInput in my app. its not getting focused in tvOS but working fine in android.

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 26.21 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Android TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: Not Found
    react-native-tvos:  0.62.2-1

**Comment by dlowder-salesforce** [comment]
Please provide an example that reproduces the issue 😊

**Comment by mehthabux** [comment]
Here is a small example which include TextInput with prop multiline

https://github.com/mehthabux/TestTvOS

**Comment by dlowder-salesforce** [comment]
@mehthabux I looked into this.  The `TextInput` component renders into a `UITextField` on iOS if it is single line, but `UITextView` if multiline.  Unfortunately, `UITextView` cannot be editable on tvOS (https://developer.apple.com/forums/thread/26540).  So tvOS can't support multiline input.

**Comment by dlowder-salesforce** [comment]
So the next question is, how should we render a multiline `TextInput`?
Possibilities:
- `<UnsupportedView />`
- Throw an error
- Force multiline to be false, so that the tvOS supported single line input shows
- Force multiline to be false and also show a `LogBox` warning

**Comment by mehthabux** [comment]
Hope, you will find an amazing solution for this one 🤗

**Comment by mehthabux** [comment]
@dlowder-salesforce  Another issue i faced in the TextInput in tvOS is that, fontSize and color is not getting reflected in TextInput. You can try adding fontSize and color to textinput in the same example repo .

Its only getting reflected in the view which comes when keyboard shows up.

**Comment by dlowder-salesforce** [comment]
See #22 ...

**Comment by dlowder-salesforce** [comment]
@mehthabux if you have time, can you review #117 and make sure you're ok with that fix?

**Comment by mehthabux** [comment]
@dlowder-salesforce disabling it ? if we don’t have any other option, this is fine. 👍

**Comment by dlowder-salesforce** [comment]
Yep, sadly it is the only option I can see

**Comment by dlowder-salesforce** [comment]
Just to be clear, after this change, the input still functions, but is only single line instead of multiline.

**Comment by dlowder-salesforce** [comment]
Fixed in https://github.com/react-native-tvos/react-native-tvos/releases/tag/v0.63.1-2
