### ISSUE TITLE
Discussion: Dimensions get reported as 1920x1080 on 4K ATV

### ISSUE THREAD

**Issue by olafurnsig** [react-native-tvos/react-native-tvos#111]
Just a discussion since I can't find anything reliable about this online.

I'm developing on a 4K AppleTV, but I'm only getting 1920 x 1080 from `Dimensions.get('window')` or` Dimensions.get('screen')`.

Is there some project setting that I need to add in Xcode, or are people just using `scale: 2` to tackle this?

**Comment by dlowder-salesforce** [comment]
This is related to #22 ..... yes there are some issues with scaling between different Apple TVs, and also Android TV.  The `scale` factor is probably the right approach for now, until there is some way to abstract out these differences.

**Comment by retyui** [comment]
@douglowder Is this link correct https://github.com/react-native-tvos/react-native-tvos/issues/22 ? `tvOS: TextInput backgroundColor style prop has inconsistent UI when highlighted. `

**Comment by douglowder** [comment]
@retyui yes that's the right issue, and it contains a link to the original issue in RN core.

**Comment by dmytro-ivonin** [comment]
> Is there some project setting that I need to add in Xcode, or are people just using `scale: 2` to tackle this?

What does that mean "using `scale: 2`", please let me know where or how I could apply that.

**Comment by paulsancer** [comment]
did anyone here figure out that `scale` factor mentioned by @douglowder ? really struggling on this issue

**Comment by paulsancer** [comment]
i was also using NativeWind but found it to make this issue bigger because i cannot apply multipliers to the classes like I do on styles, if you make it work please share with us here I would really appreciate it

thanks for the tip on those packages, will take a look
