### ISSUE TITLE
Discussion: previous screen still focusable when using react navigation modal

### ISSUE THREAD

**Issue by mehthabux** [react-native-tvos/react-native-tvos#114]
## Description
I added a react navigation modal in my app. once i navigate to modal screen, the previous screen touchable's is getting focused.

* This happens both in tvOS  and android tv

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 59.27 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Android TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: Not Found
    react-native-tvos:  0.63.1-1

## Steps To Reproduce
1. Add a navigation modal using stack navigator
2. Navigate to new modal screen and just move the focus to another touchable. you can notice that previous screen touchable's are also getting focused

## Test project git repo
https://github.com/mehthabux/TestTvOS

**Comment by dlowder-salesforce** [comment]
@mehthabux I believe this is the same issue as #43 ..... can you verify that the solutions discussed there will work for you?

**Comment by mehthabux** [comment]
@dlowder-salesforce #43 This solution works in case of tvOS but not in android.
After this i tried adding accessible = false and scrollEnabled = false to flatlist in previous screen, once i added accessible false touchable isnt getting focused in android but the flatlist still scrolls.

https://github.com/mehthabux/TestTvOS

but #43 is this a right solution? Because  if i have many buttons in the screen, i have to put a condition for every button right?

**Comment by dlowder-salesforce** [comment]
I think so. The way this is done in React Navigation, it seems that the buttons are still present but off screen, so the focus engine can still find them. The only other approach I can think of would be to place focus guides on the left and right sides to prevent navigation to off-screen elements.

**Comment by mehthabux** [comment]
oh okay, Please let us know if you find any other solution for this 👍 
 
What about the scrolling in android, it still scrolls even after passing scrollEnabled false in flatlist .

**Comment by nvolpe** [comment]
I just wanted to add my 2 cents for @mehthabux's android question. I have seen differences with focus on flatlists depending on if it is a horizontal or vertical list. Which I think can be explained by these 2 differences:

Vertical list has a setFocusable [method](https://github.com/react-native-community/react-native-tvos/blob/tvos-v0.63.1/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactScrollViewManager.java#L77)

Horizontal list [does not](https://github.com/react-native-community/react-native-tvos/blob/tvos-v0.63.1/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactHorizontalScrollViewManager.java#L78)

I think this might also relate to your question in #84. Perhaps if you patch your android code you might be able to disable the focus? I have not tested that.

**Comment by nvolpe** [comment]
Also, enableScreens() in react-navigation helped a lot with this problem.

**Comment by dlowder-salesforce** [comment]
For now, I'm going to mark this as a "discussion" issue, not a bug.  If it turns out that there is some safe change we can make inside the RN repo that would help, we can revisit this.
