### ISSUE TITLE
onMomentumScrollEnd not triggered in Android

### ISSUE THREAD

**Issue by mehthabux** [react-native-tvos/react-native-tvos#116]
## Description
I have a Flatlist with onMomentumScrollEnd props, when scrolling this function is not getting triggered in android, but working fine in tvOS 

## React Native version:
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 56.10 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Android TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: Not Found
    react-native-tvos:  0.63.1-1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Add a Flatlist with onMomentumScrollEnd prop
2. Scroll a lil bit and you can see that onMomentumScrollEnd is not triggered

## Code Example:
https://github.com/mehthabux/TestTvOS

**Comment by dlowder-salesforce** [comment]
@mehthabux is this the same as https://github.com/facebook/react-native/issues/26661 ?

**Comment by mehthabux** [comment]
yeah , its almost same, i guess the focus engine is calling scrollTo function

**Comment by dlowder-salesforce** [comment]
@mehthabux it looks like there is now a PR on RN core to fix this: https://github.com/facebook/react-native/pull/30367

Can you try that and see if it fixes the issue for you?  It hasn't been merged to core yet, but if it's solid, we can merge it here.

**Comment by anastely** [comment]
> @mehthabux it looks like there is now a PR on RN core to fix this: [facebook/react-native#30367](https://github.com/facebook/react-native/pull/30367)
> 
> Can you try that and see if it fixes the issue for you? It hasn't been merged to core yet, but if it's solid, we can merge it here.

Hey,
Maybe it's a dumb Q
But how can I use his PR in my current App to test if it works or not😅?

**Comment by dlowder-salesforce** [comment]
@anastely to test that PR, you would need to do these steps:

- clone this repo
- apply the patch from that PR to your cloned copy
- in the cloned copy, run `./gradlew :ReactAndroid:installArchives` to generate the android directory that is in releases
- copy that android directory into `node_modules/react-native` in your app project
- rebuild your app and install on Android device/simulator
