### ISSUE TITLE
Focus/blur on ScrollView?

### ISSUE THREAD

**Issue by adbl** [react-native-tvos/react-native-tvos#120]
This is not a bug report. More of advice/feature request. I can't figure out a way to detect when focus enters/exits a regular scroll view (flatlist) which contains other touchable elements.

- Say there is a vertical scrolling content view, with swimlanes of various content, I would like to be able to add tracking for when/how long the user is interacting with different swimlanes. Or maybe apply conditional styles to the swimlane when it's focused.
- An example more specific to my situation is I need to interact with a bridge API to show/hide a native tab bar component in particular ways (it should slide up/down depending on the focus). So the scrollview is the content in this case, but is overlayed by a parent tab bar.

I tried using `TVTextScrollView` / `isTVSelectable` which provides focus/blur events, but doesn't allow to focus on any touchables inside the scrollview. 

I have played around with adding `onFocus`/`onBlur` on all the touchables inside. That _can_ solve the focus problem. But not blur, I even experimented with adding and removing the `tag` to a `Set` upon focus/blur, and if the Set became empty it should mean focus has left the scrollview, but when swiping fast it seems the next onFocus gets delayed by over 500ms sometimes (in simulator at least), causing false positives. For the swimlane example I could move it up one level perhaps, but it gets quite messy.

I may be able to do something with onScroll. But again, messy... 

Somewhat related:
- `onScrollToTop` doesn't seem to trigger.

Can I solve this with existing features? If not, what would be a good solution? I'll be happy to contribute.

**Comment by dlowder-salesforce** [comment]
`ScrollView` should normally not be focusable, except for the specific case of `TVTextScrollView`.  One thing I would try is to add a thin focusable in the header and footer, and only look for `onFocus/onBlur` in those.  That way you won't be pushing events unnecessarily from all the other touchables in the `ScrollView`.
