### ISSUE TITLE
Unable to resolve peer dependencies

### ISSUE THREAD

**Issue by CodyDunlap** [react-native-tvos/react-native-tvos#124]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
To be quite honest, I'm not sure if this is a bug or if I'm just misunderstanding something. I'm fairly new to react/react-native and I am trying to build an app for AndroidTV and AppleTV. I've gone through all of the setup steps and the app runs on both platforms just fine. I started to add a few libraries, namely [React Navigation](https://reactnavigation.org/), and some have been unable to resolve peer dependencies when installing via npm. It appears the issue is related to the way this library, react-native-tvos, overrides the react-native dependency: 

```json
"react-native": "npm:react-native-tvos@0.63.1-2",
```

Is this truly a bug? Or am I simply missing something? I can move this to SO if it's not considered a bug with this library. 

## React Native version:
```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 1.02 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 21, 25, 26, 27, 28, 29
      Build Tools: 21.1.2, 23.0.2, 23.0.3, 24.0.0, 24.0.2, 25.0.0, 25.0.2, 26.0.0, 26.0.1, 26.0.2, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.0, 28.0.0, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3
      System Images: android-22 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 4.1
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_60 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.63.1-2 
  npmGlobalPackages:
    *react-native*: Not Found

```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Start with working base tvos app
2. Run `npm install @react-navigation/native`
3. Run `npm install react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view`

This last command should fail to install `@react-native-community/masked-view` because of the peer dependency mentioned above.

## Expected Results
Install the dependencies/peer dependencies correctly since react-native-tvos is built from react-native and is a version higher than the minimum for the peer dependency.

## Snack, code example, screenshot, or link to a repository:
![Screenshot](https://user-images.githubusercontent.com/3633741/97585291-fcc63800-19c6-11eb-8e8c-9413c8c035ee.png)

**Comment by dlowder-salesforce** [comment]
I would strongly recommend using `yarn` and not `npm install` to add dependencies.  I took a project created with `react-native init TestApp --template=react-native-tvos`, and then used yarn to add `@react-navigation/native`.  Got some warnings but no error.  (Note that other changes might be needed to actually get the add-ons to compile for tvOS, but that's a separate issue....)

```bash
$ yarn add @react-navigation/native
yarn add v1.22.5
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-native@0.63.1-2" has unmet peer dependency "@types/react-native@^0.63.17".
warning "react-native > use-subscription@1.5.0" has incorrect peer dependency "react@^17.0.0".
warning "@react-native-community/eslint-config > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 6 new dependencies.
info Direct dependencies
└─ @react-navigation/native@5.8.1
info All dependencies
├─ @react-navigation/core@5.13.1
├─ @react-navigation/native@5.8.1
├─ @react-navigation/routers@5.5.1
├─ query-string@6.13.6
├─ split-on-first@1.1.0
└─ strict-uri-encode@2.0.0
✨  Done in 58.41s.

```
