### ISSUE TITLE
Unable to locate react-native/tvos-types.d

### ISSUE THREAD

**Issue by fabdrol** [react-native-tvos/react-native-tvos#127]
## Description
I have followed the instructions in the Readme to get this up and running with typescript. Launching the simulator, it complains about not being able to locate `react-native/tvos-types.d`

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 479.98 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v10.19.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.63.1-2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. Create a new project following the instructions
2. Rename index.js to index.ts, App.js to App.tsx
3. Make necessary changes for Typescript 
4. Add `import react-native/tvos-types.d` to the top of index.ts

## Expected Results
I'd expect to see the example code running in the simulator, but it shows the following error instead

<img width="1884" alt="Screenshot 2020-11-06 at 09 35 56" src="https://user-images.githubusercontent.com/123201/98344395-7a1b2980-2013-11eb-998f-546695d00623.png">

**Comment by dlowder-salesforce** [comment]
@fabdrol actually never mind, I found the issue.  It's a typo in the react-native-tvos `package.json`.  You can work around this by taking the `tvos-types.d.ts` from the top level of this repo and putting in in `node_modules/react-native` in your project.  Please confirm that this fixes your issue and that there are no other problems. I'll have the typo fixed for the next release.

**Comment by fabdrol** [comment]
thanks @dlowder-salesforce :)

**Comment by dlowder-salesforce** [comment]
Fix is in 0.63.1-3
