### ISSUE TITLE
[androidTV] Scrollview still scrollable with dpad when scrollEnabled={false} #29774

### ISSUE THREAD

**Issue by prakash-altair** [react-native-tvos/react-native-tvos#128]
Description
A scrollview with the scrollEnabled prop set to false still scrolls on tv remote dpad input on androidTV.
Also onScroll events are fired when the list is scrolled this way.

React Native version:
  ##0.63.1-2

Expected Results
The scrollview should not scroll when scrollEnabled is set to false, regardless of touch, mouse or dpad input. 
facebook/react-native#29774

**Comment by prakash-altair** [comment]
[https://github.com/facebook/react-native/issues/29774](url)

**Comment by prakash-altair** [comment]
`  @ReactProp(name = "scrollEnabled", defaultBoolean = true)
  public void setScrollEnabled(ReactHorizontalScrollView view, boolean value) {
    view.setScrollEnabled(value);
    
    // Set focusable to match whether scroll is enabled. This improves keyboarding
    // experience by not making scrollview to scroll when scroll enabled is to false.
    view.setFocusable(value);
  }`

Adding `view.setFocusable(value);` to `ReactHorizontalScrollViewManager.java` will solve this issue.  Should i rise a PR for this to be added in the next release ?

**Comment by dlowder-salesforce** [comment]
Yes please send a PR for this!!! 😊

**Comment by prakashjais99** [comment]
#130

**Comment by prakashjais99** [comment]
@dlowder-salesforce 
Thanks for merging PR

**Comment by dlowder-salesforce** [comment]
@prakashjais99 no problem, thanks for the PR!  Once #129 is resolved, I'll do a new release.

**Comment by dlowder-salesforce** [comment]
Fixed in 0.63.1-4 release
