### ISSUE TITLE
Android: Soft keyboard does not open when focusing TextInput

### ISSUE THREAD

**Issue by henninghall** [react-native-tvos/react-native-tvos#129]
I am experiencing the same issue as this PR is trying to adress: https://github.com/react-native-tvos/react-native-tvos/pull/89 even when using version 0.63.1-1. 

Android specific. 

## Description
Soft keyboard is not showing when focusing text input. 

Right now you need to press OK on the d-pad to show the soft keyboard. In other words, it works as if the `showSoftInputOnFocus` prop were set to false when it isn't.

## React Native version:
react-native-tvos@0.63.1-3

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a TextInput field.
2. Run focus() on the reference

## Expected Results
Soft keyboard should open when focusing text input.

**Comment by dlowder-salesforce** [comment]
@henninghall I added a comment in PR #89 where I believe the issue is coming from, and have asked @vdmtrv to comment.

**Comment by henninghall** [comment]
@dlowder-salesforce I tried 0.63.1-4 and this works as expected now, thanks 👍
