### ISSUE TITLE
Android: Missing TVEventKeyAction.down

### ISSUE THREAD

**Issue by henninghall** [react-native-tvos/react-native-tvos#131]
## Description
After upgrading from 0.63.1-1 to 0.63.1-3, the TVEventKeyAction.down events are missing in on Android. Only the up events are being sent. 

## React Native version:
0.63.1-3

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.  useTVEventHandler(console.log);
2. Use arrow buttons and note how the down event is missing  

## Expected Results
A down event should be emitted

**Comment by dlowder-salesforce** [comment]
I made that change to avoid having multiple events sent unnecessarily for every press. Is this causing a regression for you?

**Comment by henninghall** [comment]
Alright, yes this removes the possibility to listen for the down event, which seems to be used in many android tv apps to make the clicks feel more responsive. With the down event we could for instance start the action directly when pressing down a button, not waiting for user the release the button.

I believe it would be better to keep both events so the developers can choose when to listen to what event. But if we only could keep one event I think it would be better to keep the down event. What do you think? I there a previous issue where the problems with this has been discussed?

**Comment by dlowder-salesforce** [comment]
Thanks for the explanation!  I guess we need both types of events for sure, so I'll revert that change.

**Comment by henninghall** [comment]
Awesome, thanks!
