### ISSUE TITLE
Regression in `v0.63.1-2`: `Invariant Violation: No callback found`

### ISSUE THREAD

**Issue by TrebuhD** [react-native-tvos/react-native-tvos#132]
## Description
First of all, thank you all for the amazing work on this library. I was very happy to see `nextFocusUp` implemented recently, so I updated to the latest version, but unfortunately it broke my app.

Since the upgrade, the app either refuses to launch or crashes. Here's the logcat with the error in question:

```
11-18 21:45:51.975 11649-11819/com.app_reactnative E/ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
11-18 21:45:52.125 11649-11819/com.app_reactnative E/ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
11-18 21:45:52.207 11649-11819/com.app_reactnative E/ReactNativeJS: Invariant Violation: No callback found with cbID 0 and callID 0 for module <unknown>. Args: '[{"app_state":"active"}]'
11-18 21:45:52.316 11649-11819/com.app_reactnative E/ReactNativeJS: Invariant Violation: No callback found with cbID 6 and callID 3 for module <unknown>. Args: '[{"app_state":"active"}]'
11-18 21:45:52.641 11649-11819/com.app_reactnative E/ReactNativeJS: Invariant Violation: No callback found with cbID 142 and callID 71 for module <unknown>. Args: '["{\"codeFrame\":{\"content\":\"\\u001b[0m \\u001b[90m 36 | \\u001b[39m      \\u001b[36mvar\\u001b[39m args \\u00...(truncated)..."]'
11-18 21:45:52.718 11649-11819/com.app_reactnative E/ReactNativeJS: Invariant Violation: No callback found with cbID 144 and callID 72 for module <unknown>. Args: '["{\"codeFrame\":{\"content\":\"\\u001b[0m \\u001b[90m 17 | \\u001b[39m  }\\u001b[0m\\n\\u001b[0m \\u001b[90m 18 |...(truncated)..."]'
11-18 21:45:52.790 11649-11819/com.app_reactnative E/ReactNativeJS: Invariant Violation: No callback found with cbID 146 and callID 73 for module <unknown>. Args: '["{\"codeFrame\":{\"content\":\"\\u001b[0m \\u001b[90m 36 | \\u001b[39m      \\u001b[36mvar\\u001b[39m args \\u00...(truncated)..."]'
11-18 21:45:52.860 11649-11819/com.app_reactnative E/ReactNativeJS: Invariant Violation: No callback found with cbID 148 and callID 74 for module <unknown>. Args: '["{\"codeFrame\":{\"content\":\"\\u001b[0m \\u001b[90m 17 | \\u001b[39m  }\\u001b[0m\\n\\u001b[0m \\u001b[90m 18 |...(truncated)..."]'
11-18 21:45:52.935 11649-11819/com.app_reactnative E/ReactNativeJS: Invariant Violation: No callback found with cbID 150 and callID 75 for module <unknown>. Args: '["{\"codeFrame\":{\"content\":\"\\u001b[0m \\u001b[90m 36 | \\u001b[39m      \\u001b[36mvar\\u001b[39m args \\u00...(truncated)..."]'
11-18 21:45:53.002 11649-11819/com.app_reactnative E/ReactNativeJS: Invariant Violation: No callback found with cbID 152 and callID 76 for module <unknown>. Args: '["{\"codeFrame\":{\"content\":\"\\u001b[0m \\u001b[90m 36 | \\u001b[39m      \\u001b[36mvar\\u001b[39m args \\u00...(truncated)..."]'
```

This message also shows up as an Exception in the app. There's one more error apart from this:

```
11-18 21:58:16.387 24190-24190/com.app_reactnative E/unknown:NativeViewHierarchyManager: Unable to update properties for view tag -1
    com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag -1 could not be found.

        at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:109)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:133)
        at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:291)
        at com.facebook.react.uimanager.UIManagerModule.synchronouslyUpdateViewOnUIThread(UIManagerModule.java:400)
        at com.facebook.react.animated.PropsAnimatedNode.restoreDefaultValues(PropsAnimatedNode.java:73)
        at com.facebook.react.animated.NativeAnimatedNodesManager.restoreDefaultValues(NativeAnimatedNodesManager.java:337)
        at com.facebook.react.animated.NativeAnimatedModule$19.execute(NativeAnimatedModule.java:440)
        at com.facebook.react.animated.NativeAnimatedModule$2.execute(NativeAnimatedModule.java:158)
        at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:571)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:917)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1028)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:48)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1088)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:779)
        at android.view.Choreographer.doCallbacks(Choreographer.java:592)
        at android.view.Choreographer.doFrame(Choreographer.java:559)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:767)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5604)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
``` 

I was able to trace the problem back to `v0.63.1-2` (it still works fine in `1-1`).

I don't have a reproducible example, but I can work on it if needed. Here's the [diff between v0.63.1-1 and v0.63.1-2.](https://github.com/react-native-tvos/react-native-tvos/compare/v0.63.1-1...v0.63.1-2).

## React Native version:
```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 542.63 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /var/folders/0g/h2n42hjj70lbz_r2_zw681bm0000gn/T/yarn--1605733585637-0.9636438045664422/node
    Yarn: 1.22.5 - /var/folders/0g/h2n42hjj70lbz_r2_zw681bm0000gn/T/yarn--1605733585637-0.9636438045664422/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 24.0.3, 25.0.0, 28.0.3, 29.0.2, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom, android-Q | Android TV Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
## Steps To Reproduce
I get this error right after running the app in debug mode on a physical Android Fire TV device.

**Comment by dlowder-salesforce** [comment]
`Podfile.lock` is an iOS file and should have no effect on Android functionality.

Do you have a repo that reproduces the issue that you can share?

Also thanks for the kind words 😊

**Comment by TrebuhD** [comment]
You're right about `Podfile.lock` not being the culprit - I edited my post ;). I don't have a reproducible example repository now, but since I don't know what's exactly causing this, maybe it'd be faster to debug it more to narrow the problem down a bit. I'll try it and get back to you soon!

**Comment by TrebuhD** [comment]
I've managed to narrow the problem down to [this commit](https://github.com/react-native-tvos/react-native-tvos/commit/18707efc3b0b2e5acb0b794d9831b797fc9553a9), which is kind of strange, because [it only contains type changes](https://github.com/react-native-tvos/react-native-tvos/compare/9156525531395a7eb7af5eacfc440d5377c94083...18707efc3b0b2e5acb0b794d9831b797fc9553a9).

Everything works fine in the commit before that (`9156525`), but `18707ef` only gives me a black screen. This message appears in the JS debugger console:

```
Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```

**Comment by dlowder-salesforce** [comment]
I don't see how the type changes could do this.  I suspect that the packager's cache has become invalid, and you need to clear `watchman` and restart the packager by doing `react-native start --reset-cache` (the issue seems similar to https://github.com/facebook/react-native/issues/26687).

**Comment by TrebuhD** [comment]
Thank you for your comment. Unfortunately this didn't help :/. To recap, here's what I did:

- `watchman watch-del-all`
- `react-native start --reset-cache`
- `./gradlew clean`
- `rm -rf node_modules` followed by `yarn`

It might be important that I'm using a yarn monorepo. Could it be that the `types` property inside this package's `package.json` is somehow interfering with this? Since I have no other hunch at the moment, I might fork this repository and check.

In any case, this doesn't seem strictly related to `react-native-tvos`. I'll post a solution here once I find it, but feel free to close this issue if you'd like.

**Comment by dlowder-salesforce** [comment]
Ok thanks for the update.... yes if you are in a monorepo you may want to make sure that `react-native-tvos` is used in place of `react-native` everywhere.   I'll close this for now, but please reopen if you still have problems and can supply a reproducible test case 👍

**Comment by raazatul7** [comment]
![Screenshot 2021-03-05 at 2 23 37 PM](https://user-images.githubusercontent.com/29301407/110091380-62379480-7dbe-11eb-847c-ecaa902a0c20.png)

Getting this^

**React Native version:**
System:
    OS: macOS 11.2.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 487.70 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.6.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 25, 26, 28, 29, 30
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-29 | Android TV Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.63.4-0 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by TrebuhD** [comment]
For me this was most likely related to having 2 versions of `react` inside my monorepo. Maybe make sure that you only have one version, remove your `yarn.lock` file, install again and see if you still get this issue.

**Comment by raazatul7** [comment]
I am not using yarn
Although I removed `package-lock.json` and did `npm i` 

I don't get your point 'having 2 versions of react inside my monorepo'
like from where can I check and make sure that I have only have one version ?

Also while running in Android emulator I am getting this -
![Screenshot 2021-03-05 at 5 46 26 PM](https://user-images.githubusercontent.com/29301407/110114463-b7819f00-7dda-11eb-91e0-d148b9f39a7e.png)


> For me this was most likely related to having 2 versions of `react` inside my monorepo. Maybe make sure that you only have one version, remove your `yarn.lock` file, install again and see if you still get this issue.

I am not using yarn
Although I removed `package-lock.json` and did `npm i` 
but getting the same error.
 
I don't get your point 'having 2 versions of react inside my monorepo'
like from where can I check and make sure that I have only have one version ?

Also while running in Android emulator I am getting this -
![Screenshot 2021-03-05 at 5 46 26 PM](https://user-images.githubusercontent.com/29301407/110114463-b7819f00-7dda-11eb-91e0-d148b9f39a7e.png)

**Comment by raazatul7** [comment]
Could you open the issue again?

**Comment by dlowder-salesforce** [comment]
You might be having a different issue. Please create a new issue, and if possible include a test case that reproduces the issue. It is recommended to use yarn for react-native based repos.
