### ISSUE TITLE
Touchable focus velocity - (discussion)

### ISSUE THREAD

**Issue by olafurnsig** [react-native-tvos/react-native-tvos#136]
Could not find this documented anywhere, is there a way to make Touchable* have more "gravity/stickyness"?

What I mean is that once the Touchable is highlighted, more motion than normal is required to exit it? 

My use case is that I have a constant Sidemenu visible, but it's too easy to accidentally jump from it when scrolling down.

What I'd like to be able to do is having a higher requirement on L/R motion to jump from those items.

**Comment by dlowder-salesforce** [comment]
@olafurnsig which platform is having the issue?  Apple TV or Android TV?

**Comment by olafurnsig** [comment]
@dlowder-salesforce - its not actually an issue, perhaps my text was confusing :) 

I'm looking to ADD some sort of gravity to a Touchable, so it requires more effort to exit it than normally.

So say I have some layout like this:

|  SideNav |   MainView |
| Nav1.       |.   FlatList.   |
| Nav2.       |.   FlatList.   |
| Nav3.       |.   FlatList.   |
| Nav4.       |.   FlatList.   |

When the focus hits one of the SideNav Touchables, I'd like to require a "stronger" swipe to the right to jump from the SideNav to the FlatList containing Touchables.

I hope this makes more sense?

**Comment by NickAVolpe** [comment]
My guess is that you are using the Apple TV remote which is very sensitive and you need a nimble thumb to navigate well. I personally tend to tap on the remote rather than swipe now. It likely would not be an issue on Android TV without swipe gestures. 

I'm have not done anything like this, but the work done to add Pressable support looks exciting and might be a good place to start: https://github.com/react-native-tvos/react-native-tvos/pull/126

**Comment by olafurnsig** [comment]
What I was apparently trying to get into words, is somehow being able to manipulate how much touch velocity is needed to exit a Focusable item, this is somewhat covered in Apple's tvOS guidelines but I need to dig a bit more into it.

**Comment by dlowder-salesforce** [comment]
@olafurnsig thanks for the clarification.... that does sound like a very useful enhancement for Apple TV RN users 👍

**Comment by crewtaylorfd** [comment]
Is there a solution to this? I am running into a similar problem. I am using the `TVEventHandler` and the `swipeUp` and `swipeDown` events are sometimes not triggered even when the focus engine changes the focused element. The `TVEventHandler` and the focus engine do not have the same threshold for triggering a swipe event on an ATV remote. I think a _velocity_ prop would fix this or get them closer at least.

**Comment by douglowder** [comment]
The events from TVRemoteHandler and from the focus change handler in RCTTVView are separately generated, so there is no guarantee about their relative timing.
