### ISSUE TITLE
multiple fire of onPress on single press of the remote on Android

### ISSUE THREAD

**Issue by aakashsigdel** [react-native-tvos/react-native-tvos#138]
First of all I would like to say thank you for great work on this repo

## Description
When you attach a onPress handler on a TouchableOpacity it is fired multiple time on single press of remote in android. In tvOS it works fine. 

This is happening because we attach a new listener for TV platform on componentDidMount of TouchableOpacity.js
In android, there is already a listener through the pressability config and in CDM we add an additional listener.

## React Native version:
```
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.27 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.0 - /usr/local/lib/ruby/gems/2.7.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.63.1-4
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Create an empty app with just a TouchableOpacity with onPress handler
2. run it on androidTv
3. click on the button with the remote

## Expected Results
The onPress callback should only be fired once, but instead is fired multiple time

## Snack, code example, screenshot, or link to a repository:
https://github.com/aakashsigdel/rn-test-touchableopacity

I will submit a PR to fix this

**Comment by aakashsigdel** [comment]
it is interesting that a new commit on September 29 removes all of the tvOS related code from react-native repo. This also removes the `componentDidMount` function from the `TouchableOpacity.js` file. 
I am wondering if we are going to add it back here in this repo. If indeed that is the case this problem will still be there. 

Let me know if I can help out in somehow

**Comment by dlowder-salesforce** [comment]
We will not be merging that commit here.  The removal of tvOS code from RN core was done so that it would be clear that all Apple TV (and Android TV) support will be in this repo.

**Comment by mehthabux** [comment]
@aakashsigdel i think you need to `Platform.OS !== 'android'` in TVTouchable.js. even i had the same issue adding `Platform.OS !== 'android'` fixed my issue

`'use strict';

import invariant from 'invariant';
import ReactNative from '../../Renderer/shims/ReactNative.js';
import type {
  BlurEvent,
  FocusEvent,
  PressEvent,
} from '../../Types/CoreEventTypes';
import Platform from '../../Utilities/Platform';
import TVEventHandler from '../../Components/AppleTV/TVEventHandler';

type TVTouchableConfig = $ReadOnly<{|
  getDisabled: () => boolean,
  onBlur: (event: BlurEvent) => mixed,
  onFocus: (event: FocusEvent) => mixed,
  onPress: (event: PressEvent) => mixed,
|}>;

export default class TVTouchable {
  _tvEventHandler: TVEventHandler;

  constructor(component: any, config: TVTouchableConfig) {
    invariant(Platform.isTV, 'TVTouchable: Requires `Platform.isTV`.');
    this._tvEventHandler = new TVEventHandler();
    this._tvEventHandler.enable(component, (_, tvData) => {
      tvData.dispatchConfig = {};
      if (ReactNative.findNodeHandle(component) === tvData.tag) {
        if (tvData.eventType === 'focus') {
          config.onFocus(tvData);
        } else if (tvData.eventType === 'blur') {
          config.onBlur(tvData);
        } else if (tvData.eventType === 'select' && Platform.OS !== 'android') {
          if (!config.getDisabled()) {
            config.onPress(tvData);
          }
        }
      }
    });
  }

  destroy(): void {
    this._tvEventHandler.disable();
  }
}
`

**Comment by aakashsigdel** [comment]
@mehthabux  Thanks, this is what I did as well. I will create a PR here
