### ISSUE TITLE
Generation of `android` directory does not include Javadoc archive

### ISSUE THREAD

**Issue by dlowder-salesforce** [react-native-tvos/react-native-tvos#14]
In order to have a release that works for Android, it is required that 

```sh
./gradlew :ReactAndroid:installArchives
```

be run before publishing to NPM.

Generation of the binary and source archives work, but Javadoc archive generation fails due to missing dependencies.  (See #7 and https://github.com/facebook/react-native/issues/25625)

Javadoc generation is temporarily disabled for this repo until this issue is resolved.

**Comment by brodybits** [comment]
I would classify this as an enhancement since I think generating Javadoc for Android is not a goal of this fork project.

**Comment by dlowder-salesforce** [comment]
@brodybits : if we are focused only on Apple TV, you are correct.

However, there is a possibility that Android TV fixes and enhancements may go into this repo.  (See comments in #7 )  If this happens, then a complete Android archive generation (including Javadocs) would become more important......

**Comment by brodybits** [comment]
> However, there is a possibility that Android TV fixes and enhancements may go into this repo.

Wow another TV OS, open source this time:)

So this would be a bigger fork, in a similar fashion to the way Expo has its own fork (except that Expo seems to fall behind, argh!)

I still don't really understand the motivation behind generating Javadoc from a custom fork. I would assume the React Native Java API should not be any different for Android TV, or am I missing something here?

**Comment by brodybits** [comment]
I think it would be ideal if we can get this fixed.

Alternative solution may be to just document that there is no custom Javadoc that is needed to be made on this fork.

**Comment by brodybits** [comment]
Can this be pinned to avoid closure from the stale bot?
