### ISSUE TITLE
React Native Perf Monitor displays incorrectly when tvOS is set to dark mode

### ISSUE THREAD

**Issue by olafurnsig** [react-native-tvos/react-native-tvos#140]
Tested on a AppleTV non-4K.

UI settings set to Dark in Settings -> General, when the Dark mode is enabled, RAM, JSC, Views part of the perf monitor are not visible.

tvOS 14.2 (18K57)
react-native-tvos@6.3.1-4

**Comment by dlowder-salesforce** [comment]
@olafurnsig I'll take a look -- I will also check to see if this is also an issue on iOS.  If so, an issue should be raised in the core repo.

**Comment by dlowder-salesforce** [comment]
Interesting... this problem does not happen on iOS.  I'll find the perf monitor code and add the required checks for tvOS.

**Comment by dlowder-salesforce** [comment]
OK I have a fix

**Comment by dlowder-salesforce** [comment]
I'll get this into the next patch release @olafurnsig

**Comment by olafurnsig** [comment]
Thanks for being so incredibly responsive @dlowder-salesforce , I'll have to have my colleagues buy you a beer the next time Dreamforce held! :)

**Comment by dlowder-salesforce** [comment]
This fix is in https://github.com/react-native-tvos/react-native-tvos/releases/tag/v0.63.3-0
