### ISSUE TITLE
Unable to get UIRequiredDeviceCapabilities correct

### ISSUE THREAD

**Issue by viktorbk** [react-native-tvos/react-native-tvos#143]
## Description
I'm trying to publish the app to TestFlight but i am unable to get by this error:
![image](https://user-images.githubusercontent.com/358725/102006970-53909280-3d25-11eb-8262-8c5bcf542c29.png)
I tried all possible values for UIRequiredDeviceCapabilities
```
  <key>UIRequiredDeviceCapabilities</key>
  <array>
    <string>arm64</string>
  </array>
```
## React Native version:
System:
    OS: macOS 11.0.1
    CPU: (20) x64 Intel(R) Xeon(R) W-2150B CPU @ 3.00GHz
    Memory: 52.82 GB / 128.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.1, 29.0.2, 30.0.1
      System Images: android-27 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_241 - /Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.63.1-4 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Create new App and try to validate the ipa

## Expected Results
Is there anyone which have had similar problem?

**Comment by dlowder-salesforce** [comment]
Sorry you are having this issue... I do see that there are others (possibly not React Native developers) who have hit this problem. https://stackoverflow.com/questions/64688364/tvos-uirequireddevicecapabilities-issue

**Comment by dlowder-salesforce** [comment]
I did notice that for newly created projects, the required device capabilities is actually set to `armv7` on the tvOS target, which is wrong.  It should be `arm64`.  Could you check to see if that is true in your project?

**Comment by viktorbk** [comment]
Thanks for your input. UIRequiredDeviceCapabilities was not included in info.plist but i added it and tried all possible combinations of arm64 and armv7. Also i tried adding others like telphony, sms etc. without success.

**Comment by asharafshahi** [comment]
I am experiencing the same issue.  When creating a new project it is initially set to armv7, I did change it to arm64, but continue to get the same error.

**Comment by mattallard123** [comment]
For the record, changing from armv7 to arm64 in the TV OS target Info.plist worked for me after experiencing this error in my react native project. @douglowder

**Comment by ali-sao** [comment]
Make sure you change it inside `info` tab while selecting the project-tvOS target as well.
