### ISSUE TITLE
tvOS: Performance issues and delays in parallax effects with list of focusables

### ISSUE THREAD

**Issue by prakashjais99** [react-native-tvos/react-native-tvos#145]
## Description
In tvOS focus navigation is based on scale change on focus/blur. Due to touchpad navigation in tvOS scaling after on focus callback is creating a visible delay in scale and its clearly visible when we do fast swipes in touch pad 

## React Native version:
0.63.1-4

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Flatlist with list of touchables which scales on focus
2. Do a fast swipe

## Expected Results
Scaling should be smooth similar to opacity change 

## Proposal 
Can we add a new TouchbleScale similar to TouchableOpacity which changes scale factor before calling focus in the framework

**Comment by dlowder-salesforce** [comment]
The scale change actually happens as part of the native tvOS view code, specifically in `React/Views/RCTTVView.m`:

```objc
- (void)didUpdateFocusInContext:(UIFocusUpdateContext *)context
       withAnimationCoordinator:(UIFocusAnimationCoordinator *)coordinator
{
  if (context.previouslyFocusedView == context.nextFocusedView) {
    return;
  }
  if (context.nextFocusedView == self && self.isTVSelectable ) {
    [self becomeFirstResponder];
    [coordinator addCoordinatedAnimations:^(void){
      [self addParallaxMotionEffects];
      [self sendFocusNotification:context];
    } completion:^(void){}];
  } else {
    [coordinator addCoordinatedAnimations:^(void){
      [self sendBlurNotification:context];
      [self removeParallaxMotionEffects];
    } completion:^(void){}];
    [self resignFirstResponder];
  }
}
```

One thing you could try is to move the calls to `[self sendFocusNotification:context]` and `[self sendBlurNotification:context]` to their respective completion handlers, and see if that improves the behavior.

**Comment by prakashjais99** [comment]
@dlowder-salesforce thanks for the answer. But for android parallax effect will not work. 
We should have a common solution for scale as this is what mostly used in TV's
I can create a PR for the same if it is ok?

**Comment by dlowder-salesforce** [comment]
Yes it would be great if you can create a separate issue or PR for adding parallax effects to Android.  Let's keep this issue for fixing the performance issues with tvOS.

**Comment by olafurnsig** [comment]
@prakashjais99  Have you fully optimized the FlatList component, with getItemLayout and windowSize, numItemsToRender, and the actual ListItems as PureComponents.

I noticed a huge change in performance after doing as much optimizing as I could do. I still have slight hiccups if the lists are gigantic like 300 items though.
