### ISSUE TITLE
[HOWTO] - Autoscroll FlatList to certain position

### ISSUE THREAD

**Issue by ericlifs** [react-native-tvos/react-native-tvos#153]
I have a screen which is basically a FlatList (that renders some blocks) and at the very bottom of the screen I have a **Scroll to Top** button that just scrolls that FlatList to the y = 0 position. That's working fine. 

The thing is that (after coding for tvos for some months -all of these concepts are new to me-) I noticed that focus and scroll are different things, since even after scrolling to the very top of the screen (and the first component is shown) the focus was still on the Button that was pressed at the very bottom.

I wanted to know if there is a way of doing both things (scrolling and focusing at the first element) at the same time?

---

Also, as a proposal, I would recommend extending the focus documentation since it appears to be the most unknown zone of the tvos based on the issues being created. I would love to contribute in doing this.

---

Thanks!

**Comment by dlowder-salesforce** [comment]
If you have a ref to the first element, your button can set the `hasTVPreferredFocus` prop on the element to force focus to move to that element.

**Comment by ericlifs** [comment]
Sorry, how do I do that? Does the ref.current have a function for dynamically set the `hasTVPreferredFocus` prop? Or do you mean setting the prop to the Component itself within the return statement?

**Comment by olafurnsig** [comment]
@ericlifs - You can have some state variable :

`this.state = {scrollToTopFocus: false}`

then on the list item you want to move the focus to:

```
<View
   hasTVPreferredFocus={this.state.scrollToTopFocus}
   >
.....
</View>
```

Then when you scroll the list to index: 0, also do:


`
this.setState({scrollToTopFocus: true});
`

Something along these lines should work I think
