### ISSUE TITLE
Focus element is not persisted after we come back from another screen

### ISSUE THREAD

**Issue by mehthabux** [react-native-tvos/react-native-tvos#156]
## Description
Im having a list of touchable elements and onPressing a particular item , we navigate to another screen. so when once i move to a particular element in the list and press it we move to another screen and after that once i pressed the back button, the previously focused element is not getting focused. the focus goes to the first element in the list.

**Comment by dlowder-salesforce** [comment]
@mehthabux is this happening on Apple TV, Android TV, or both?  Is this using React Navigation, or some other stack?

**Comment by mehthabux** [comment]
@dlowder-salesforce Hi, this is happening in both Platforms, and yeah im using React navigation

**Comment by mehthabux** [comment]
@dlowder-salesforce have you got the chance to look into this issue ?

**Comment by dlowder-salesforce** [comment]
I did spend a little time looking into the issue.... it looks like we would have to expose `remembersLastFocusedIndexPath` to have this work on Apple TV.  (https://developer.apple.com/documentation/uikit/uicollectionview/1618022-rememberslastfocusedindexpath)

If the list view is being rerendered when the user navigates back, then this might not work, and the app might have to keep track of what is focused and programmatically focus the correct view when the user navigates back.

**Comment by mehthabux** [comment]
@dlowder-salesforce so we don't have any other option 😔 ?

**Comment by dlowder-salesforce** [comment]
I don't think so.  However, if you have an example of an app that shows the problem, I can see if `remembersLastFocusedIndexPath` will actually work or not.

**Comment by olafurnsig** [comment]
@mehthabux 

I had the same issue, and I "solved" it by adding a wasClicked state variable for the item in the list.

If it's pressed (and navigated to the content) , the wasClicked variable is set to true.

the component has:

`...
hasTvPreferredFocus={this.state.wasClicked}
....
`

When the user then goes back, the last item gets re-focused.

I'm also using react-navigation, and react-native-screens.

**Comment by olafurnsig** [comment]
Some other convoluted way to achieve a similar result could possibly be to keep the id/unique identifier of the item clicked in redux or something, and then change the **hasTvPreferredFocus** on that item when the screen gets re-mounted.

**Comment by olafurnsig** [comment]
Video:
[![](http://img.youtube.com/vi/JKFu_LSLhZ0/0.jpg)](http://www.youtube.com/watch?v=JKFu_LSLhZ0 "refocus demo")

**Comment by dlowder-salesforce** [comment]
Thanks @olafurnsig !!!
