### ISSUE TITLE
Can't build tvOS app on Apple Silicon M1

### ISSUE THREAD

**Issue by roidy** [react-native-tvos/react-native-tvos#157]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Unable to build tvOS app on Apple Silicon M1, build fails with

ld: in /Users/roidy/Documents/Projects/RoidyTV/ios/Pods/OpenSSL-Universal/tvos/lib/libcrypto.a(cryptlib.o), building for tvOS Simulator, but linking in object file built for tvOS, file '/Users/roidy/Documents/Projects/RoidyTV/ios/Pods/OpenSSL-Universal/tvos/lib/libcrypto.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Follow Read.ME build changes to create a new tvOS app

## Expected Results
App to build without errors

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by dlowder-salesforce** [comment]
To solve this issue, go into `ios/Podfile` in your new project, and remove or comment out the lines

```
  use_flipper_tvos!
```

Then execute `pod install` in the `ios` directory.  This will remove the prebuilt Flipper libraries from your build, and the compile should succeed.

**Comment by roidy** [comment]
Thanks, that fixes the build however now the app launches in the simulator but displays nothing but a white screen.

**Comment by dlowder-salesforce** [comment]
Can you provide Xcode console logs?  The white screen is what I would expect if the app is not able to connect to the packager.  Is the packager running?

**Comment by roidy** [comment]
The packager seems to be running
<img width="1440" alt="Screenshot 2021-02-03 at 19 13 49" src="https://user-images.githubusercontent.com/4118048/106797045-0ad5c580-6654-11eb-9fab-f76f29a6b355.png">
What logs do you need and where do I find them, thanks.

**Comment by roidy** [comment]
Anybody got any ideas? I'd really like to get react native working on tvOS.

**Comment by dlowder-salesforce** [comment]
Can you open `ios/roidyapp1.xcworkspace` in Xcode, and run the `roidyapp-tvOS` target in the simulator from there?  Hopefully you'll see a bit more debugging info.  I have seen that React Native core users are hitting issues with M1 development machines (https://github.com/facebook/react-native/issues/30599), I wonder if you are seeing the same thing.

**Comment by roidy** [comment]
Unfortunately what I posted before is everything XCode outputs when running the tvOS target from Xcode, nothing else is output.

**Comment by tomdyson** [comment]
This isn't a solution - sorry @roidy - but FWIW I'm able to run tvOS apps on the simulator on my Apple Silicon M1, without making any changes from the instructions.
