### ISSUE TITLE
tvOS feature: additional Siri remote gestures (especially the pan gesture)

### ISSUE THREAD

**Issue by douglowder** [react-native-tvos/react-native-tvos#16]
It would be good to support some of the additional gestures available on the Apple TV remote trackpad, particuarly the pan gesture.  This is already supported in a separate module (https://github.com/respectTheCode/react-native-tvos-controller).  This issue is to track work for merging some or all of that module's features into this repo.

Discussed earlier in https://github.com/respectTheCode/react-native-tvos-controller/pull/2

**Comment by vdmtrv** [comment]
I was also contemplating a similar side project as the current react-native `TVEventHandler` doesn't really support remote gesture events that don't pass the threshold. I guess we can extend and build upon the current `TVEventHandler` in this project now that there's an official fork.

**Comment by brodybits** [comment]
?
-- 
Sent from my mobile

**Comment by brodybits** [comment]
Can we pin this issue?

**Comment by nriccar** [comment]
Any news?

**Comment by nnomadic** [comment]
Any updates on this issue?

**Comment by douglowder** [comment]
Ok ok now that 0.68 is out I will take another look at getting this done. :)

**Comment by douglowder** [comment]
I have this working with commit https://github.com/react-native-tvos/react-native-tvos/commit/958134dcdb03d54c33ff98316246359b72caadbe -- now figuring out the best way to allow it to be turned on and off (probably the same one we use to enable/disable menu key).

**Comment by nnomadic** [comment]
> I have this working with commit [958134d](https://github.com/react-native-tvos/react-native-tvos/commit/958134dcdb03d54c33ff98316246359b72caadbe) -- now figuring out the best way to allow it to be turned on and off (probably the same one we use to enable/disable menu key).

Sounds perfect mate, you're a life saver thank you!
