### ISSUE TITLE
Unexpected behavior and style on TextInput automatic focus

### ISSUE THREAD

**Issue by kech37** [react-native-tvos/react-native-tvos#161]
## Description
When trying to use any type of automatic focus in the `TextInput`, the component has an unexpected style and behaviour.
## React Native version:
```
System:
    OS: macOS 11.2.1
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 2.59 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.63.4-0 
  npmGlobalPackages:
    *react-native*: Not Found
```
## Steps To Reproduce
1. Launch App
2. Insert any text on the username `TextInput`
3. Press `next` button 

Watch that:
- The insert text does not show in the input because the colour and size of it is not correct. It should be like the attached screenshot. [1] 
- After pressing `next` the password TextInput should be focused. Instead, the username TextInput is closed and the screen is presented. [2]

## Expected Results
1. User launches the app;
2. Username TextInput is automatically focused;
3. The user inserts the text in the input;
4. The inserted text shows with the correct TextInput style;
5. The user presses the `next` button;
6. The password TextInput is automatically focused;

### Actual Results
1. User launches the app;
2. Username TextInput is automatically focused;
3. The user inserts the text in the input;
4. The inserted text does not show with the correct TextInput style; [1]
5. The user presses the `next` button;
6. The Username TextInput is closed and the app screen is presented; [2]

## Adicional information
- I tried different methods of automatic focus in the TextInput. I tried with the `autoFocus` flag on the `TextInput` component and tried to use the `setNativeProps`. The result is the same.
- If I disabled the automatic focus on the username `TextInput` the style is correct and the expected behaviour accours.
- If after step 6 in the current result flow, select the username `TextInput` again, the text style will be correct and the expected behaviour will occur. [3]
## Snack, code example, screenshot, or link to a repository:
https://github.com/kech37/react-native-tvos-auto-focus-test

## Attachements
[1]
![Screenshot 2021-02-11 at 10 14 58](https://user-images.githubusercontent.com/14061754/107627209-e0d56200-6c56-11eb-83d3-39068201fb26.png)
[2]
![Screenshot 2021-02-11 at 10 15 05](https://user-images.githubusercontent.com/14061754/107627211-e29f2580-6c56-11eb-8e73-7eaee9746615.png)
[3]
![Screenshot 2021-02-11 at 10 15 21](https://user-images.githubusercontent.com/14061754/107628053-01ea8280-6c58-11eb-869c-192163868334.png)

**Comment by dlowder-salesforce** [comment]
I looked into this today, and found the following:
- The autofocus does not work on tvOS -- very likely it is interfering with the tvOS focus engine.  I tried a hack to use the code that implements `hasTVPreferredFocus` on regular focusable views, but that does not work.  My advice would be to not use autofocus on tvOS for now.
- The `TextInput` styling issues are discussed in #22

**Comment by kech37** [comment]
> I looked into this today, and found the following:
> 
> * The autofocus does not work on tvOS -- very likely it is interfering with the tvOS focus engine.  I tried a hack to use the code that implements `hasTVPreferredFocus` on regular focusable views, but that does not work.  My advice would be to not use autofocus on tvOS for now.
> * The `TextInput` styling issues are discussed in #22

Thank you for the feedback
