### ISSUE TITLE
Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication) 

### ISSUE THREAD

**Issue by supagu** [react-native-tvos/react-native-tvos#162]
## Description
Creating initial ios TV app results in errors, with the first error being:
**Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)** 

## React Native version:
4.14.0

% react-native doctor
warn Package react has been ignored because it contains invalid configuration. Reason: Cannot find module 'react/package.json'
Require stack:
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/config/resolveNodeModuleDir.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/releaseChecker/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/runServer.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/start.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/bin.js
warn Package react-native has been ignored because it contains invalid configuration. Reason: Cannot find module 'react-native/package.json'
Require stack:
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/config/resolveNodeModuleDir.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/releaseChecker/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/runServer.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/start.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/bin.js
warn Package @babel/core has been ignored because it contains invalid configuration. Reason: Cannot find module '@babel/core/package.json'
Require stack:
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/config/resolveNodeModuleDir.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/releaseChecker/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/runServer.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/start.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/bin.js
warn Package @babel/runtime has been ignored because it contains invalid configuration. Reason: Cannot find module '@babel/runtime/package.json'
Require stack:
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/config/resolveNodeModuleDir.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/releaseChecker/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/runServer.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/start.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/bin.js
warn Package @react-native-community/eslint-config has been ignored because it contains invalid configuration. Reason: Cannot find module '@react-native-community/eslint-config/package.json'
Require stack:
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/config/resolveNodeModuleDir.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/releaseChecker/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/runServer.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/start.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/bin.js
warn Package babel-jest has been ignored because it contains invalid configuration. Reason: Cannot find module 'babel-jest/package.json'
Require stack:
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/config/resolveNodeModuleDir.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/releaseChecker/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/runServer.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/start.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/bin.js
warn Package eslint has been ignored because it contains invalid configuration. Reason: Cannot find module 'eslint/package.json'
Require stack:
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/config/resolveNodeModuleDir.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/releaseChecker/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/runServer.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/start.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/bin.js
warn Package jest has been ignored because it contains invalid configuration. Reason: Cannot find module 'jest/package.json'
Require stack:
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/config/resolveNodeModuleDir.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/releaseChecker/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/runServer.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/start.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/bin.js
warn Package metro-react-native-babel-preset has been ignored because it contains invalid configuration. Reason: Cannot find module 'metro-react-native-babel-preset/package.json'
Require stack:
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/config/resolveNodeModuleDir.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/releaseChecker/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/runServer.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/start.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/bin.js
warn Package react-test-renderer has been ignored because it contains invalid configuration. Reason: Cannot find module 'react-test-renderer/package.json'
Require stack:
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/config/resolveNodeModuleDir.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/tools/releaseChecker/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/runServer.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/start/start.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/commands/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/index.js
- /usr/local/lib/node_modules/@react-native-community/cli/build/bin.js
Common
 ✓ Node.js
 ✓ npm
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 29.0.2
 ✖ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ● ios-deploy - Required for installing your app on a physical device with the CLI

Errors:   2
Warnings: 1

Usage
 › Press f to try to fix issues.
 › Press e to try to fix errors.
 › Press w to try to fix warnings.
 › Press Enter to exit.
Common
 ✓ Node.js
 ✓ npm
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 29.0.2
 ✖ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ● ios-deploy - Required for installing your app on a physical device with the CLI

Errors:   2
Warnings: 1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

Follow steps here: https://github.com/react-native-tvos/react-native-tvos:

# Make sure you have the CLI installed globally (this only needs to be done once on your system)
npm install -g @react-native-community/cli
# Init an app called 'TestApp', note that you must not be in a node module (directory with node_modules sub-directory) for this to work
react-native init TestApp --template=react-native-tvos@latest
# Now start the app in the tvOS Simulator - this will only work on a macOS machine
cd TestApp && react-native run-ios  --simulator "Apple TV" --scheme "TestApp-tvOS"

## Expected Results
To be able to run the app on Apple TV

## Snack, code example, screenshot, or link to a repository:
Sample project: [https://drive.google.com/file/d/1JjmP7u8RlXJJ9xm7Nd9HZcikee2t1XqK/view?usp=sharing](https://drive.google.com/file/d/1JjmP7u8RlXJJ9xm7Nd9HZcikee2t1XqK/view?usp=sharing)

**Comment by supagu** [comment]
This is the same bug as reported here: https://github.com/react-native-tvos/react-native-tvos/issues/132
I tried older versions but every version I tried I had the same problem.
PS. Recently upgraded to Big Sur so not sure if it might be related to that

**Comment by dlowder-salesforce** [comment]
I just did the following:

- pulled your zip file
- Ran `yarn` from the top level directory to install the node dependencies
- Changed to ios directory
- Removed the `Podfile.lock` file, which did not appear to be the one I would expect for react-native-tvos (did you try a different Podfile at some point?)
- Ran `pod install`
- Went back to the top level directory
- Ran `react-native run-ios --scheme="sanfl_tv-tvOS" --simulator="Apple TV"`

The project ran successfully on the tvOS simulator.

**Comment by supagu** [comment]
Following your steps today it works perfectly. Maybe I just needed to restart my mac! Closing.
