### ISSUE TITLE
Discussion: TV remote events order (question)

### ISSUE THREAD

**Issue by ivodaveiga** [react-native-tvos/react-native-tvos#163]
## Description
Consider the code bellow. In the tvOS when navigating up and down with the remote I'm getting the following order of events:

```
LOG      focus
LOG      blur
LOG      blur
LOG      blur
LOG      blur
LOG      down
```

Shouldn't it be the other way arround? Fire the remote tap first, then fire the blur event and finally the focus? 

## React Native version:
```
info Fetching system and libraries information...
System:
    OS: macOS 11.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 69.52 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.63.4-0 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Code example:
```
const App = () => {
  const myTVEventHandler = (evt) => {
    console.log(evt.eventType);
  };

  useTVEventHandler(myTVEventHandler);

  return (
    <View>
      <Button label="Button 1" />
      <Button label="Button 2" />
    </View>
  );
};
```

**Comment by dlowder-salesforce** [comment]
The different blur events are actually coming from different views.  Try the following:

```js
import React from 'react';
import {
  View,
  Button,
  useTVEventHandler
} from 'react-native';

const App = () => {
  const myTVEventHandler = (evt) => {
    console.log("Type: " + evt.eventType + ", Tag = " + evt.tag);
  };

  useTVEventHandler(myTVEventHandler);

  return (
    <View>
      <Button title="Button 1" />
      <Button title="Button 2" />
    </View>
  );
};

export default App;
```

This will show you the React tags for the views that are firing the focus and blur events:

```
[Thu Feb 25 2021 16:46:28.719]  LOG      Type: down, Tag = undefined
[Thu Feb 25 2021 16:46:29.920]  LOG      Type: focus, Tag = 9
[Thu Feb 25 2021 16:46:29.920]  LOG      Type: blur, Tag = 23
[Thu Feb 25 2021 16:46:29.930]  LOG      Type: blur, Tag = 25
[Thu Feb 25 2021 16:46:29.930]  LOG      Type: blur, Tag = 27
[Thu Feb 25 2021 16:46:29.940]  LOG      Type: blur, Tag = 19
[Thu Feb 25 2021 16:46:29.180]  LOG      Type: up, Tag = undefined
[Thu Feb 25 2021 16:46:31.622]  LOG      Type: focus, Tag = 19
[Thu Feb 25 2021 16:46:31.623]  LOG      Type: blur, Tag = 23
[Thu Feb 25 2021 16:46:31.623]  LOG      Type: blur, Tag = 25
[Thu Feb 25 2021 16:46:31.624]  LOG      Type: blur, Tag = 27
[Thu Feb 25 2021 16:46:31.625]  LOG      Type: blur, Tag = 9
[Thu Feb 25 2021 16:46:31.687]  LOG      Type: down, Tag = undefined
[Thu Feb 25 2021 16:46:58.162]  LOG      Type: focus, Tag = 9
[Thu Feb 25 2021 16:46:58.163]  LOG      Type: blur, Tag = 23
[Thu Feb 25 2021 16:46:58.163]  LOG      Type: blur, Tag = 25
[Thu Feb 25 2021 16:46:58.164]  LOG      Type: blur, Tag = 27
[Thu Feb 25 2021 16:46:58.164]  LOG      Type: blur, Tag = 19
[Thu Feb 25 2021 16:46:58.228]  LOG      Type: up, Tag = undefined

```

**Comment by ivodaveiga** [comment]
Hi @dlowder-salesforce, thanks for the response. My question here is really about the event order.

Let's say we want to know when the user pressed a direction key when on a button. 

Since the focus event fires before the tv remote key, in the example below if we enter the app an press 3 times down we're going to get

```
LOG      You've pressed down on button 2
LOG      You've pressed down on button 3
LOG      You've pressed down on button 3
```

instead of

```
LOG      You've pressed down on button 1
LOG      You've pressed down on button 2
LOG      You've pressed down on button 3
```

or there is another way to accomplish this?


## Code example:
```
import React, { useState } from "react";
import { View, useTVEventHandler, Text, TouchableOpacity } from "react-native";
import "react-native/tvos-types.d";

class Button extends React.Component<any> {
  render() {
    return (
      <TouchableOpacity
        activeOpacity={0.7}
        onPress={this.props.onPress}
        onFocus={this.props.onFocus}
      >
        <Text>{this.props.title}</Text>
      </TouchableOpacity>
    );
  }
}

const App = () => {
  const [state, setState] = useState(0);

  const myTVEventHandler = (evt) => {
    if (evt.eventType === "down") {
      console.log("You've pressed down on button " + state);
    }
    if (evt.eventType === "up") {
      console.log("You've pressed up on button " + state);
    }
  };

  useTVEventHandler(myTVEventHandler);

  return (
    <View>
      <Button onFocus={() => setState(1)} onPress={() => {}} title="Button 1" />
      <Button onFocus={() => setState(2)} onPress={() => {}} title="Button 2" />
      <Button onFocus={() => setState(3)} onPress={() => {}} title="Button 3" />
    </View>
  );
};

export default App;
```

**Comment by dlowder-salesforce** [comment]
I do see the problem with event ordering.  In order to accomplish what you want, I think we would want to make some changes in the iOS/tvOS native code to include the direction information in the focus event.  We are already using this direction information in the implementation of `nextFocusUp`, `nextFocusDown`, etc.  See this code in `React/Views/RCTTVView.m`, which uses the `focusHeading` property of the focus event context:

```objc
- (BOOL) shouldUpdateFocusInContext:(UIFocusUpdateContext *)context {
  if (self.isFocused) {
    if (_nextFocusUp != nil && context.focusHeading == UIFocusHeadingUp) {
      self->_nextFocusActiveTarget = _nextFocusUp;
      [self setNeedsFocusUpdate];
      return false;
    }
    if (_nextFocusDown != nil && context.focusHeading == UIFocusHeadingDown) {
      self->_nextFocusActiveTarget = _nextFocusDown;
      [self setNeedsFocusUpdate];
      return false;
    }
    if (_nextFocusLeft != nil && context.focusHeading == UIFocusHeadingLeft) {
      self->_nextFocusActiveTarget = _nextFocusLeft;
      [self setNeedsFocusUpdate];
      return false;
    }
    if (_nextFocusRight != nil && context.focusHeading == UIFocusHeadingRight) {
      self->_nextFocusActiveTarget = _nextFocusRight;
      [self setNeedsFocusUpdate];
      return false;
    }
    self->_nextFocusActiveTarget = nil;
    return true;
  }
  self->_nextFocusActiveTarget = nil;
  return true;
}

```

**Comment by dlowder-salesforce** [comment]
I made the changes needed to propagate the `context.focusHeading` value up to the JS app layer... see branch https://github.com/react-native-tvos/react-native-tvos/tree/focusdirection-test

With this branch, I ran this example:

```js
import React from 'react';
import {
  View,
  Button,
  useTVEventHandler
} from 'react-native';

const App = () => {

  const myTVEventHandler = (event) => {
    console.log('' + event.eventType + ' ' + event.direction + ' ' + event.tag);
  };

  useTVEventHandler(myTVEventHandler);

  return (
    <View>
      <Button
        title="Button 1" />
      <Button
        title="Button 2" />
    </View>
  );
};

export default App;
```

and see that focus and blur events now have the direction (down, up, etc.) of the gesture that caused the change.

Will this work for your use case?

**Comment by ivoveiga** [comment]
Thanks for the reply and the test branch!

I've done some experiments with that branch and seems we still cannot identify when there was a down tap in the last button.

With the example you've provided, this is the logs it generates hen entering the app and tap down twice.

```
focus down 19
blur down 23
blur down 25
blur down 27
blur down 9
down undefined undefined
down undefined undefined
```

the first down generates the first 6 log lines, and the second generates the last line. Now we know when down was tapped while on 1st button by listening to its blur event ( `blur down 9` ) but for the second button since there is no element bellow, there is no blur event, and no way to know if down was tapped in this button.

Probably a way to workaround this will be register when the button was focused and add a counter of the times down is tapped and discard the first 'down' event. When the button is blurred, reset the counter. But it will not work if the button received focus from other way than the remote. Have to think a bit more how to workaround this.

The onFocus and onBlur events on the Button component are a nice addiction.

**Comment by dlowder-salesforce** [comment]
When you are on the second button, there is nothing focusable below it, so no focus events are received when you swipe down from there.  The down event is not associated with any view -- it is generated from a gesture handler in the root view, and just tells you that the down gesture happened, and nothing else. So yes if you need to know that, a workaround would be needed.

**Comment by Humza-7** [comment]
when I use useTvEventHandler or even TVEventHandler it is throwing an error 
(0, _reactNative.useTVEventHandler) is not a function. (In '(0, _reactNative.useTVEventHandler)(myTVEventHandler)', '(0, _reactNative.useTVEventHandler)' is undefined)

what would I do

**Comment by Aure77** [comment]
> when I use useTvEventHandler or even TVEventHandler it is throwing an error (0, _reactNative.useTVEventHandler) is not a function. (In '(0, _reactNative.useTVEventHandler)(myTVEventHandler)', '(0, _reactNative.useTVEventHandler)' is undefined)
> 
> what would I do

Most of TV OS code as been removed on RN 0.64 release (https://github.com/facebook/react-native/pull/29407). But actual doc is not clear...
