### ISSUE TITLE
Discussion: How to vertically center focused element?

### ISSUE THREAD

**Issue by ericlifs** [react-native-tvos/react-native-tvos#164]
Is there a way of vertically center the element that gets focused? I have several components that have different heights and I started seeing that when it gets focused it's not centered to the middle of the viewport. Also, if you are scrolling from bottom to top the position of the focused element is not the same as if you are scrolling from top to bottom.

Thank you very much!

**Comment by dlowder-salesforce** [comment]
OK I have some questions:

- Is the element that needs to be centered inside a list (e.g. FlatList)?
- Is the issue happening on Apple TV, Android TV, or both?

In general, the scrolling you are seeing is not done by React Native, it's a feature of the native tvOS or Android focus engine.

**Comment by ericlifs** [comment]
Hey @dlowder-salesforce thanks for answering!

Yes, all the blocks are within a FlatList and the issue is happening on apple tv.

Thanks,

Eric!

**Comment by ericlifs** [comment]
@dlowder-salesforce is there a way of managing this?

**Comment by dlowder-salesforce** [comment]
The first thing you should try is implementing `onFocus()` for the element, and do a `scrollToIndex()` or `scrollToItem()` on your FlatList to position the list where you want it.  https://reactnative.dev/docs/flatlist#scrolltoindex

**Comment by ericlifs** [comment]
It worked perfectly!! Thanks @dlowder-salesforce, you rock!
