### ISSUE TITLE
[HOWTO] Is it possible to convert an existing RN project to support tvOS? 

### ISSUE THREAD

**Issue by ahmedsu** [react-native-tvos/react-native-tvos#181]
## Description
I have an existing app running for both Android and iOS devices. Is it possible to convert that project to support tvOS builds so I can run it for the tvOS also?

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 336.38 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 7.7.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_202-release - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: npm:react-native-tvos@latest => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

I already tried to add "npm:react-native-tvos@latest " to react-native import in my package.json

<img width="1580" alt="image" src="https://user-images.githubusercontent.com/20888827/117847465-a776b780-b282-11eb-9502-dc7c9e51167c.png">

**Comment by dlowder-salesforce** [comment]
This is certainly possible, but you would need to make other changes besides the react-native version.  The Podfile and Xcode projects for a react-native-tvos project are very different from those in RN core -- the Xcode project has additional targets for tvOS, and the Podfile has a separate section for the tvOS targets.  It also looks like you are on RN 0.64, but the tvOS repo is still on 0.63.4, so there is a difference in the React version as well.

There are a couple of approaches you can take:

1) Take a look at the template files in this repo (e.g. [package.json](https://github.com/react-native-tvos/react-native-tvos/blob/tvos-v0.63.4/template/package.json) and [Podfile](https://github.com/react-native-tvos/react-native-tvos/blob/tvos-v0.63.4/template/ios/Podfile) and copy over the relevant sections to your existing project.  You would also have to manually add tvOS targets to your existing Xcode project.

2) Create a new tvOS supported project (see instructions for that in the README file in this repo).  Then copy your code from the old project to the new one.

If you already have a very complex Xcode project, (1) might be best, but if this is a project you recently created using the react native CLI, and most of your code is Javascript, I'd recommend (2).

**Comment by Barteque** [comment]
Hi @dlowder-salesforce 
Are You (or RNTVOS Community) planing to make 0.64.0 release of React Native TVOS ?

**Comment by dlowder-salesforce** [comment]
Yes

**Comment by pprabhu-ng** [comment]
Hi @dlowder-salesforce 
Glad to know there is 0.64.0 release coming up !! When do you think it can be expected to happen?

**Comment by dlowder-salesforce** [comment]
@pprabhu-ng I should be able to start some time in July, based on expected completion of some current projects.

**Comment by dlowder-salesforce** [comment]
@pprabhu-ng FYI I've started the preliminary work for a 0.64.2 release, and tracking this in #188

**Comment by pprabhu-ng** [comment]
@dlowder-salesforce Great !! Thanks for updating. Will check this.
