### ISSUE TITLE
Both buttons getting focused for Alert in TvOS

### ISSUE THREAD

**Issue by mehthabux** [react-native-tvos/react-native-tvos#186]
My current version is react-native-tvos@0.62.2-1
![IMG_20210601_100705](https://user-images.githubusercontent.com/69464250/120281687-de1a7d80-c2d6-11eb-898b-0a8e153e66e7.jpg)

**Comment by dlowder-salesforce** [comment]
@mehthabux two questions:

- Is this Apple TV or Android TV?
- Does the issue reproduce in the latest release (0.63.4-0)?

**Comment by mehthabux** [comment]
@dlowder-salesforce its Apple Tv
sorry i didnt try this with 0.63.4-0

**Comment by dlowder-salesforce** [comment]
All right thanks @mehthabux .... if it still reproduces with 0.63.4, maybe post a sample App.js that shows the bug?

**Comment by mehthabux** [comment]
ok let me try that 👍

**Comment by dlowder-salesforce** [comment]
@mehthabux does this still happen on 0.64.2-0?

**Comment by mehthabux** [comment]
@dlowder-salesforce hi sorry i didnt try that , will try it once and let you know 👍

**Comment by dlowder-salesforce** [comment]
@mehthabux I just updated to 0.64.2-1 to fix a regression in Touchable, please use that for testing
