### ISSUE TITLE
Upgrade to RN 0.64.2

### ISSUE THREAD

**Issue by dlowder-salesforce** [react-native-tvos/react-native-tvos#188]
Here I'm tracking the effort to move the TV version of React Native to 0.64.2.

**Comment by dlowder-salesforce** [comment]
- Created base branch https://github.com/react-native-tvos/react-native-tvos/tree/branch-v0.64.2 that is an exact copy of the commits in RN core 0.64.2
- Created new release branch https://github.com/react-native-tvos/react-native-tvos/tree/tvos-v0.64.2 from that
- Started by reverting https://github.com/facebook/react-native/pull/29407, then start cherry-picking this repo's 0.63 commits in order

**Comment by dlowder-salesforce** [comment]
Finished cherry picking all the 0.63 commits from this repo that were not already part of core.  Fixed some merge issues, and several new tvOS compile breakages in core code -- now RNTester at least compiles successfully.

**Comment by dlowder-salesforce** [comment]
Ok RNTester now runs in the tvOS simulator.  Fixed some UI issues, and added a "TV" example category.

Now attempting to bring up Hermes JS engine.  Core is using podspecs with prebuilt libraries and without tvOS support for `hermes-engine` and `libevent`, so I'm rolling my own in the `third-party-podspecs` directory.

**Comment by dlowder-salesforce** [comment]
Progress: I have a release testing branch that works well on Apple TV (no Hermes support yet). Android TV is having some compile issues, I'm looking into those.

**Comment by danielkalen** [comment]
@dlowder-salesforce Any progress on this? Do you need assistance in getting this tested/moved further?

**Comment by dlowder-salesforce** [comment]
@danielkalen I've resolved the Android compile issues.  Fixed up the tvOS tests and some issues with RNTester.  I'm checking Android tests now.

**Comment by dlowder-salesforce** [comment]
Ok it's shipped :)

- Release notes: https://github.com/react-native-tvos/react-native-tvos/releases/tag/v0.64.2-0
- NPM package: https://www.npmjs.com/package/react-native-tvos

Of course file issues if you see any regressions.

**Comment by Barteque** [comment]
https://media.giphy.com/media/yyZRSvISN1vvW/giphy.gif

**Comment by danielkalen** [comment]
Hey @dlowder-salesforce, amazing speed on getting this shipped out. Out of curiosity, what is the blocker for having Hermes work on tvOS? Maybe I can provide assistance with that?

**Comment by dlowder-salesforce** [comment]
@danielkalen if you would be willing to work on Hermes tvOS support, that would be awesome.  The support for iOS that is currently there for Hermes (see https://github.com/facebook/hermes/pull/332) does not include build targets for tvOS.  So that would all have to be added in the Hermes repo, then this repo would need to be modified to pick up the new Hermes build and included tvOS support.  Hermes itself may have external dependencies that don't yet support tvOS, which if so would add further complexity :)

**Comment by danielkalen** [comment]
Sounds good. I can't guarantee ownership and completion of this, but I will try my best. I'm assuming that we don't want to work with forks of Hermes and want the tvOS support shipped on an official Hermes release?

**Comment by danielkalen** [comment]
@dlowder-salesforce please confirm on my last question.

**Comment by dlowder-salesforce** [comment]
@danielkalen a fork of Hermes is the way to go. This repo was created because Facebook no longer wanted to support tvOS in RN core. I doubt they would be willing to add it to the main Hermes repo now.
