### ISSUE TITLE
react-native-svg will not compile in a new tvOS project

### ISSUE THREAD

**Issue by douglowder** [react-native-tvos/react-native-tvos#190]
## Description

If the `react-native-svg` package is added to a `react-native-tvos` project, the tvOS target will not compile.  Thanks very much to @GantMan for finding this issue and bringing it to my attention!

## React Native version:
0.63.4-0

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

```bash
react-native init TestSVG --template=react-native-tvos
cd TestSVG
yarn add react-native-svg
cd ios
pod install
cd ..
react-native run-ios --scheme='TestSVG-tvOS' --simulator='Apple TV'
```

## Expected Results
New app should compile and launch in the tvOS simulator.

## Actual Results
Compilation fails with several errors

**Comment by dlowder-salesforce** [comment]
Root cause: The SVG package has been recently updated to support MacOS, but the MacOS specific files have not been excluded from the tvOS platform in the podspec.

Solution: Patch the podspec as below, then rerun `pod install`.

```diff
diff --git a/node_modules/react-native-svg/RNSVG.podspec b/node_modules/react-native-svg/RNSVG.podspec
index 28eb91a..f06c66a 100644
--- a/node_modules/react-native-svg/RNSVG.podspec
+++ b/node_modules/react-native-svg/RNSVG.podspec
@@ -13,6 +13,7 @@ Pod::Spec.new do |s|
   s.source            = { :git => 'https://github.com/react-native-community/react-native-svg.git', :tag => "v#{s.version}" }
   s.source_files      = 'apple/**/*.{h,m}'
   s.ios.exclude_files = '**/*.macos.{h,m}'
+  s.tvos.exclude_files = '**/*.macos.{h,m}'
   s.osx.exclude_files = '**/*.ios.{h,m}'
   s.requires_arc      = true
   s.dependency          'React'
```

**Comment by adkaushik** [comment]
Downgrading the react-native-svg to version `12.1.0` fixes the issue for now

**Comment by douglowder** [comment]
@adkaushik that's probably the best solution for those not needing the latest version, thanks!

If you do need the latest, I recommend using the truly awesome [patch-package](https://www.npmjs.com/package/patch-package), and adding a file `patches/react-native-svg+12.1.1.patch` to your project, with the diff shown in my earlier comment.

**Comment by douglowder** [comment]
@brentvatne is there any chance that a new bugfix release of `react-native-svg` can be generated with the fix for this issue (plus the Xcode 12 fix)?

Commits needed:
- https://github.com/react-native-svg/react-native-svg/commit/686930b1c6e1b957449e6d6e632647b4e13325d6
- https://github.com/react-native-svg/react-native-svg/commit/e8ed5e943f761ecfad9fa83e17d08ebe3a694fa0

**Comment by brentvatne** [comment]
i'm not the best person for this, but it seems that react-native-svg finds itself without a maintainer so i checked out the repo to give it a shot ... it looks like it's not in a great state right now. i can't get the repo to build - i tried cloning and running `npm install` which led to a series of errors in build, and almost 200 type errors. i don't have time to look into this further unfortunately, so if anyone wants to help on react-native-svg it would be appreciated

**Comment by douglowder** [comment]
@brentvatne I'll take a look and see if I can fix those issues

**Comment by douglowder** [comment]
Amazing I brought it down to 15 type errors just by updating to latest types/react and types/react-native :)

**Comment by douglowder** [comment]
https://github.com/react-native-svg/react-native-svg/pull/1628

**Comment by douglowder** [comment]
This issue is resolved in https://www.npmjs.com/package/react-native-svg/v/12.2.0 -- closing.
