### ISSUE TITLE
Regression in Touchable TVEventHandler usage in 0.64.2-0

### ISSUE THREAD

**Issue by dlowder-salesforce** [react-native-tvos/react-native-tvos#196]
## Description

When testing an existing project in `react-native-tvos@0.64.2-0`, an error occurs if `TouchableOpacity` or `TouchableHighlight` is used:

<img width="602" alt="Screen Shot 2021-07-08 at 6 04 57 PM" src="https://user-images.githubusercontent.com/6577821/125008380-40be1200-e017-11eb-9fe3-1388f2439362.png">

The error is due to a missing import in `Touchable.js`.

**Comment by dlowder-salesforce** [comment]
This is fixed and will appear in the `0.64.2-1` release.

**Comment by dlowder-salesforce** [comment]
I'll leave this issue open until `0.64.2-1` has been released.

**Comment by methineeinkan** [comment]
+ 1

**Comment by dlowder-salesforce** [comment]
> how to fix

@methineeinkan fix it by adding the missing import line as in https://github.com/react-native-tvos/react-native-tvos/commit/e531db0a81932c1ad1c7f10b2a90ef014cf4a75b

**Comment by dlowder-salesforce** [comment]
`0.64.2-1` release is out now, so closing this.
