### ISSUE TITLE
Navigator Stack doesn't work because of "RNReanimated" dependency

### ISSUE THREAD

**Issue by oscadev** [react-native-tvos/react-native-tvos#202]
## Description
Pod Install fails with error message : 
`[!] Unable to find a specification for `React-RCTActionSheet` depended upon by `RNReanimated``

## React Native version
```
System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 107.31 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.8.0 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.64.2-1 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Make a new build using `react-native init TestApp --template=react-native-tvos@latest`
2. yarn add @react-navigation/native
3. pod install (success)
4. yarn add react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view
5. pod install (fails with "Unable to find a specification for `React-RCTActionSheet" error)

## Expected Results
It should successfully pod install. This error does not occur in normal ios react native projects.

**Comment by iyevpak** [comment]
same issue

**Comment by oscadev** [comment]
> same issue

It used to work, so I will try older versions of either RN-tvos or RNreanimated.

**Comment by dlowder-salesforce** [comment]
I have been testing Reanimated on TV this week, and found this issue.  I'm not sure why the dependency is there.  If I remove the ActionSheet and Vibration dependencies from the Reanimated podspec, everything compiles just fine.  I am considering whether or not to submit this as a bug on react-native-reanimated.

**Comment by oscadev** [comment]
> I have been testing Reanimated on TV this week, and found this issue. I'm not sure why the dependency is there. If I remove the ActionSheet and Vibration dependencies from the Reanimated podspec, everything compiles just fine. I am considering whether or not to submit this as a bug on react-native-reanimated.

It pod installs successfully if I use ^1.0.0 version of reanimated, but I cannot test if it builds because build is failing with now another Navigator Stack related error (dont know if I missed it before, or if I am doing something wrong now). Now im getting several build fail errors related to "react-native-screens" and things being "unavailable to tvOS" like "'searchTextField' is unavailable: not available on tvOS". 
![Screen Shot 2021-07-18 at 7 19 21 PM](https://user-images.githubusercontent.com/56416772/126089299-69b278a7-d8d1-4a44-9b8b-aec6a44682e0.png)

**Comment by oscadev** [comment]
> same issue

see my post above for workarounds that work until a fix is made.

**Comment by dlowder-salesforce** [comment]
`react-native-screens` has never compiled on tvOS without some patches, as far as I know.

In order to help people get past this and other issues with Reanimated, I've started a demo project, https://github.com/dlowder-salesforce/TVReanimated . It has the patches needed for Reanimated, screens, and svg packages, so that the tvOS target will compile and run at least some of the Reanimated examples.

**Comment by dlowder-salesforce** [comment]
The demo project https://github.com/react-native-tvos/TVReanimated now works correctly with the 2.2.0 version of `react-native-reanimated` and the latest `react-navigation`, on iOS, tvOS, and Android phone and TV.  The project uses `patch-package` to apply the small podspec and source code changes needed for Apple TV on a few packages.
