### ISSUE TITLE
Android Box Focus notwork

### ISSUE THREAD

**Issue by methineeinkan** [react-native-tvos/react-native-tvos#203]
OS: macOS 11.4
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 63.24 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.2.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.20.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 26, 28, 29, 30
      Build Tools: 23.0.1, 27.0.3, 28.0.3, 29.0.2, 30.0.2
      System Images: android-19 | ARM EABI v7a, android-27 | Google APIs Intel x86 Atom, android-29 | Android TV Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_271 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.64.2-1 
    

android box is not working

**Comment by dlowder-salesforce** [comment]
Please provide an example showing the issue, and state what should happen if things are working correctly. Also, did this issue occur in earlier releases of this repo?

**Comment by methineeinkan** [comment]
I can press the move button on android tv but can't move buttons or move things on android box

**Comment by dlowder-salesforce** [comment]
A quick search about Android Box issues suggests that the remote control for the Android Box you are using is not recognized as a d-pad by the React Native Android implementation. It will probably be difficult to help you with this without having the actual hardware...

**Comment by methineeinkan** [comment]
botton move but not focus style

**Comment by dlowder-salesforce** [comment]
@methineeinkan I'll do some more research on this, but technically Android TV boxes aren't using the Android TV OS underneath, and are usually heavily customized, so this repo may not be able to provide support for them in general.

**Comment by douglowder** [comment]
Closing this, as we don't actually support Android Box.
