### ISSUE TITLE
Airplay casting on tvOS

### ISSUE THREAD

**Issue by ericlifs** [react-native-tvos/react-native-tvos#208]
## Description
I want to know if there is a way of checking from the tvOS side if someone is casting via airplay. I'm using this library https://github.com/disjfa/react-native-airplay-btn for casting from the mobile app side to the tvOS device I have, but now I want to do the other way around (checking is someone is already connected to the tvOS).

I'm doing some pocs by adding that library to my tvOS app but I'm not sure how to check if it works (as I cannot cast to the simulator).

Thank you very much,

Eric.

**Comment by douglowder** [comment]
I have looked around, and the only examples I have found are those which check the other way (the iOS device can see if it is casting to the Apple TV).
