### ISSUE TITLE
Is TabBarIOS safe to use?

### ISSUE THREAD

**Issue by nriccar** [react-native-tvos/react-native-tvos#213]
Im trying to replicate the same behaviour with a custom TabBarIOS but testing the original one is far more native feeling than the one that Im accomplishing to create.

Is tabbarios stable to use? I see its deprecated. In case the answer is no, is there any alternative for it?

Thanks for reading

**Comment by douglowder** [comment]
Yes it is safe to use on tvOS.  Best example is probably https://github.com/douglowder/RNAppleTVTalk ... I will try to make a smaller and simpler demo project at some point.

**Comment by nriccar** [comment]
Thank you for the quick response!
