### ISSUE TITLE
[feature request] Adding tvos parallax focus on touchables

### ISSUE THREAD

**Issue by nriccar** [react-native-tvos/react-native-tvos#215]
This is a feature request, not a bug report.

It would be really nice to add the tvos parallax "light reflection" effect to touchables, don't you think?

I evaluated adding it as a native module, but it should be on top of the touchable module, and Im getting a little lost right there.

Here's and example: https://github.com/PGSSoft/ParallaxView

Is it feasible?  

Thanks

**Comment by douglowder** [comment]
If you want to add more parallax code, the place to do it is in `RCTTVView.m`, specifically `addParallaxMotionEffects()` and `removeParallaxMotionEffects()`.  You will also need to add new props for light reflection to `TVParallaxPropertiesType` in `Libraries/Components/AppleTV/TVViewPropTypes.js`, and new defaults for those props in `defaultTVParallaxProperties` (also in `RCTTVView.m`)

**Comment by nriccar** [comment]
Thanks for the quick response. Ill check it out!
