### ISSUE TITLE
UI Layout is incorrect whenever we use TVFocusGuideView in tvOS projects.

### ISSUE THREAD

**Issue by Ganesh-Kumar-Reddy-M** [react-native-tvos/react-native-tvos#216]
## Description
The **TVFocusGuideView** uses two views internally to properly set up the **FocusGuide** and it accepts the **'style'** prop along with other view props. But the problem is that, the **TVFocusGuideView** applies the same 'style' prop to both same props to both parent and child views, which is causing the UI issue.
For example, if the client specifies **'marginLeft'** property in the **style** prop, then the **TVFocusGuideView** will apply the **'marginLeft'** for both parent and child, and so, left margin is getting added twice and UI becomes incorrect. The same is applicable for other layout properties.

## React Native version:
react-native-tvos@0.64.2-2

## Steps To Reproduce
1. Use **TVFocusGuideView** in ReactNative tvOS project.
2. Specify the layout related properties like **'marginLeft'**, **'marginTop'** in the **'style'** prop and pass it to the **TVFocusGuideView**.
3. Now observe layout properties will be applied twice and UI looks incorrect.

## Expected Results
UI should be should be laid out as specified in the 'style' prop.

## Code example:
<TVFocusGuideView
          destinations={destinations}
          style={{marginLeft: 20, marginTop: 20, width: 600, height: 200}}>
         .....
 </TVFocusGuideView>

**Comment by douglowder** [comment]
I have one other issue I'm working on at the moment -- once I've merged the fix for that as well, I will create a release and close this.

**Comment by douglowder** [comment]
Fixed in 0.64.2-3.
