### ISSUE TITLE
tvOS: TextInput backgroundColor style prop has inconsistent UI when highlighted.

### ISSUE THREAD

**Issue by keshavkaul** [react-native-tvos/react-native-tvos#22]
<img width="543" alt="Screenshot 2019-10-18 at 2 59 37 PM" src="https://user-images.githubusercontent.com/3319809/67083148-4414c880-f1b8-11e9-8cdb-c1569aea90ba.png">

React Native version: react-native-tvos@0.60.4-6

## Code 

```tsx
<TextInput style={styles.textInput} placeholder="Email Address" />
```
```ts
const styles = StyleSheet.create({
    textInput: {
        backgroundColor: '#D5D5D5',
        height: 72,
        textAlign: 'center',
        fontSize: 32,
        fontWeight: '300',
        marginBottom: 28,
  },
})
```

Describe what you expected to happen:

TextInput has default tvOS UI experience that I need to customize. Providing styling to TextInput should disable that default tvOS UI experience.

Snack, code example, screenshot, or link to a repository:

**Comment by keshavkaul** [comment]
unfocused and focused UI
<img width="533" alt="Screenshot 2019-10-18 at 3 11 58 PM" src="https://user-images.githubusercontent.com/3319809/67083916-a4f0d080-f1b9-11e9-9553-dde8fff99af8.png">

**Comment by dlowder-salesforce** [comment]
This seems to be a long-standing issue with RN, where styles supported in `<Text/>` are not necessarily supported in `<TextInput/>`.  https://github.com/facebook/react-native/issues/7070

**Comment by keshavkaul** [comment]
Any recommendations on how to customise text input? Or if i have to fix this, where to look for this issue?

**Comment by dlowder-salesforce** [comment]
The one suggestion I saw that made sense was to try to wrap a Text inside the TextInput, e.g.

```js
         <TextInput
            onChangeText={text => onChangeText(text)}
            >
            <Text
              style={styles.textInput}
              >
                {value}
            </Text>
          </TextInput>
```

It seems to work, but has some odd behaviors on tvOS.  Could you try in your environment and see what happens?

**Comment by keshavkaul** [comment]
Thanks, i tried your suggestion but notice that in tvOS's native text input screen, the text is applied a vertical offset and appears cut off.

**Comment by danychi** [comment]
> I have been working on demos for an upcoming medium article on React Native TV user input. As part of this work, I found that there are issues on Android TV with having TextInput get the focus from a Touchable when navigating with the DPad.
> 
> The technique below seems to solve that issue, and wrapping the TextInput in a Touchable seems to restore the styling that you would expect.
> 
> ```js
> const App = () => {
>   const [inputText, setInputText] = useState('');
>   const textInputRef = useRef();
>   return (
>     <SafeAreaView style={styles.container}>
>       <ScrollView
>         style={[styles.container, {backgroundColor: colors.background}]}>
>             <TouchableOpacity
>               style={{flex: 1}}
>               onPress={() => textInputRef?.current?.focus()}>
>               <TextInput
>                 ref={textInputRef}
>                 label="Text Input"
>                 value={inputText}
>                 onChangeText={(src) => setInputText(src)}
>               />
>             </TouchableOpacity>
>       </ScrollView>
>     </SafeAreaView>
>   );
> };
> ```

This workaround seems to partially work, but when the `TouchableOpacity` uses a light background like "white" and the Text uses a "black" color, then the text is not visible as can be seen in this screenshot:

Black background - White text

![Screenshot 2022-08-03 at 16 04 46](https://user-images.githubusercontent.com/45874461/182628528-a0828463-542e-460a-8acd-c18b79982cbf.png)

White background - Black text

![Screenshot 2022-08-03 at 16 05 27](https://user-images.githubusercontent.com/45874461/182628598-569226c6-62ae-457e-9aca-d1b3e9d8debf.png)

**Comment by geroale** [comment]
We have the same issue

**Comment by wouterds** [comment]
Closing this issue as it is not a react-native-tvos specific issue but rather an issue upstream in react-native core.
