### ISSUE TITLE
React Native 0.65 (& 0.66)?

### ISSUE THREAD

**Issue by wouterds** [react-native-tvos/react-native-tvos#228]
Hi,

I'm sorry for abusing issues but found no other way to reach out. Are there any plans to upgrade to react-native 0.65, or even 0.66 anytime soon? Is there a specific reason why it's still on 0.64? Always trailing 2 versions behind or ..?

Kind regards,
Wouter

**Comment by douglowder** [comment]
@wouterds I just published the 0.66 release, see https://github.com/react-native-tvos/react-native-tvos/releases/tag/v0.66.3-0

**Comment by wouterds** [comment]
Happy new year & thank you!
