### ISSUE TITLE
TVEventHandler and useTVEventHandler captured event repetition

### ISSUE THREAD

**Issue by ali-sao** [react-native-tvos/react-native-tvos#233]
## Description
Hello and thank you for the support; 
I am building a sliding component using TVEventHandler on **Android TV** when I noticed that a single event is logged twice, I used the useTVEventHandler hook for the same purpose, same side effect. 

<img width="966" alt="Screen Shot 2021-10-29 at 8 57 11 PM" src="https://user-images.githubusercontent.com/6895166/139489359-35ae23dd-33ab-41cf-b2f8-7c7d8ec914d5.png">

## React + Native /Deps info:
`System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 299.29 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-Q | Android TV Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7621141
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home/bin/javac
  npmPackages:
    react: 17.0.1 => 17.0.1
    react-native-tvos:  0.64.2-4`

## Steps To Reproduce
use the example mentioned in this repo readme on a boilerplate app. [https://github.com/react-native-tvos/react-native-tvos#code-changes](url)

## Expected Results
To log the event once. 

## Code example
`import React from "react";
  import {View,Text,useTVEventHandler,TouchableOpacity} from "react-native";

const App =() => {
  const [lastEventType, setLastEventType] = React.useState("");
  const myTVEventHandler = evt => { 
    console.log(evt.eventType)
    setLastEventType(evt.eventType)
  };
  useTVEventHandler(myTVEventHandler);
  return (
    <View >
      <TouchableOpacity hasTVPreferredFocus={true} />
      <Text>{lastEventType}</Text>
      <TouchableOpacity />
    </View>
  );
};
export default App;`

## Personal Observation
The behaviour is similar to keyup and keydown web events difference, whenever I press any of the 4 directions on the remote, an event is fired, when I release the button immediately after, same event logged again.

**Comment by douglowder** [comment]
I do see this, and the events appear to be real (i.e. multiple firings of the key event handler in ReactRootView in the Android native code). I'll look into this to see if it is actually a bug, or just a feature of the way Android works.

**Comment by wouterds** [comment]
Can confirm this issue, we currently wrapped our button actions with a debounce to work around this.

**Comment by mhovanisian** [comment]
I have the same issue with TvEventHandler

**Comment by douglowder** [comment]
Found the issue. For arrow keys, Android is sending both key up and key down events. Probably just need to have `TVEventHandler` filter out the key down events and we should be ok.

**Comment by douglowder** [comment]
I'm going to look into modifying the Android code to send key events only when key up happens.  In the meantime, developers can filter out the key down event by looking for the `eventKeyAction` in the TV events.  The value will be 0 for key down, 1 for key up. So on Android, only run your event handler when the value is 1.

**Comment by ali-sao** [comment]
Brilliant, thank you so much @douglowder

**Comment by douglowder** [comment]
In further investigation, I find that this was introduced in https://github.com/facebook/react-native/pull/25300 , and is mentioned in https://github.com/facebook/react-native/issues/25979 as a problem. The change doesn't look like it is going to be useful, especially for TV, so I'm backing it out for this repo.

**Comment by douglowder** [comment]
Fixed in 0.64.2-5.

**Comment by NikitaGura** [comment]
Hello @douglowder, would be great to have info about key up/down for ATV and TVOS as well. I will wait impatiently. Thanks for your work :)

**Comment by douglowder** [comment]
@NikitaGura after this change, we are only sending keyUp events on Android. tvOS has never sent key up or key down events. It is using a gesture recognizer that emits an event when a tap gesture is detected for arrow keys, menu key, etc.

**Comment by NikitaGura** [comment]
@douglowder  thanks for answer. I created custom long press logic in js code which worked with keyUp and KeyDown. In new version unfortunately this not work. 
For TVOS I just added keyUp and KeyDown and patch react-native, but for ATV I faced with problem of patching. Application did not recognise changed java code in node module react-native. Do you know how rebuild react native module for android?

**Comment by douglowder** [comment]
Clone this repo, then in the `react-native-tvos` directory, do `npm install` or `yarn`, then `gradlew :ReactAndroid:installArchives`.

This will create Android artifacts in the `android` directory. This should be used to replace the existing `node_modules/react-native/android` directory in your project.

**Comment by PDabek-StreamitApp** [comment]
In our project we are also facing problems due to these changes. I have tried the solution you have suggested with building `android` directory separately, but it seems to be quite problematic to maintain. 

Is there any other way to fix/patch this?

Huge fan of this repo anyway!

**Comment by douglowder** [comment]
@etiennelab @PDabek-StreamitApp @NikitaGura I will look into making the keyDown events optional. It seems like there are scenarios like yours where they are useful, but they cause problems in other use cases. I'll create a new issue for this.

**Comment by PDabek-StreamitApp** [comment]
Thanks @douglowder ! looking forward to this!

**Comment by 1stmuse** [comment]
how can i import TVEvenHandler from "react-native"

**Comment by douglowder** [comment]
@etiennelab @PDabek-StreamitApp @NikitaGura please see #258 for my proposed fix.

**Comment by PDabek-StreamitApp** [comment]
Looks great - thanks!

**Comment by karan883** [comment]
> Hi @douglowder Am trying to import TVEventHandler from react native app and getting this error while giving run-android **TypeError: 0, _reactNative.useTVEventHandler is not a function (it is undefined)**
> 
> Myself developing an app for Android TV. Am using a react-native core package.
> 
> Please help to do this. If i get any reference repo means very helpful

Facing Same issue. Please help @douglowder

**Comment by douglowder** [comment]
You need to use this package, not react-native core package:

```
{
  "dependencies": {
    "react-native": "npm:react-native-tvos@0.73.4-0"
  }
}
```

**Comment by ZuhairRaza665** [comment]
hey, so i am importing tvhandler and it is working import all right , but when i run the code on tv and press the button on my tv remote nothing seem to be happening while i have set it to alert on every key. Can someone please provide me the demo code for simply just alerting which ever key is pressed. Thanks :)

**Comment by douglowder** [comment]
I'm not sure you want to alert on every key... here is an example that displays the last 6 event types observed by the event handler.

```jsx
'use strict';

import React from 'react';
import ReactNative from 'react-native';
const {Platform, View, Text, TouchableOpacity, useTVEventHandler} = ReactNative;

const App = () => {
  const [eventLog, setEventLog] = React.useState([]);

  const isAndroid = Platform.OS === 'android';

  const appendEvent = (eventType, eventKeyAction) => {
    const limit = 6;
    const newEventLog = eventLog.slice(0, limit - 1);
    if (isAndroid) {
      newEventLog.unshift(`type=${eventType}, action=${eventKeyAction !== undefined ? eventKeyAction : '' }`);
    } else {
      newEventLog.unshift(`type=${eventType}`);
    }
    setEventLog(newEventLog);
  };

  useTVEventHandler((evt) => {
    appendEvent(evt.eventType, evt.eventKeyAction);
  });

  return (
    <View>
      <TouchableOpacity onPress={() => {}}>
        <Text>
          This example enables an instance of TVEventHandler to show the last
          event detected from the Apple TV Siri remote or from a keyboard.
        </Text>
      </TouchableOpacity>
      {eventLog.map((e, ii) => (
        <Text style={{color: 'blue'}} key={ii}>
          {e}
        </Text>
       ))}
    </View>
  );
};
```
