### ISSUE TITLE
Different focus order tvOS/Android

### ISSUE THREAD

**Issue by sinewave440hz** [react-native-tvos/react-native-tvos#235]
## Description

In tvOS: We have a custom `GoBack` component on a screen which is getting focus before the screen's `useFocusEffect` is run, causing the screen to lose focus immediately it is shown, effectively rendering it inaccessible.

In Android: The same `GoBack`does not get focus until the user actively backs out of the screen.

But why the different focus behaviour? Does it indicate a bug or that we are doing something wrong here?

NB: We're still currently unable to proceed beyond 0.63.4-0 at the moment so bear with us on that, if possible :/ 

## React Native version:
Run `react-native info` in your terminal and copy the results here.

info Fetching system and libraries information...
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 127.72 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.10.0 - ~/.nvm/versions/node/v15.10.0/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v15.10.0/bin/yarn
    npm: 7.6.3 - ~/.nvm/versions/node/v15.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Android TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 3.7.3 - /Users/aa/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.63.4-0 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. Run the app in tvOS, navigate to the event details screen. Notice that you are pulled instantly back to the "swim lanes" view.
2. Run the app in android, navigate to the event details screen. Notice that you can view the screen then back out to the "swim lanes" view at your leisure.

## Expected Results

I expect that both platforms should handle the focus events in the same order.

## Snack, code example, screenshot, or link to a repository:

This Royal Opera House project, as you may recall, is fully out in the open :)

I have added [a workaround ](https://github.com/royaloperahouse/stream-tv-app/blob/0523291690634dc9fd02a677eab12ce8013bef81/src/screens/EventDetailsScreen/index.tsx#L136) in [this](https://github.com/royaloperahouse/stream-tv-app/tree/fix/menu-nav-tvos) branch. I hide the `GoBack`component until we are sure the useFocusEffect has run, essentially.

**Comment by douglowder** [comment]
I'll take a look today

**Comment by douglowder** [comment]
There are some differences in the way Android TV and Apple TV handle focus.

I had thought that React Navigation's `useFocusEffect()` runs when a navigation screen is shown.  I'm surprised it is affected by the TV focus engine since that is a completely separate thing!

I'll have to set things up so I can actually run the app... I can provide my IP address but that may not be helpful since I'm in a corporate VPN most of the time.

**Comment by sinewave440hz** [comment]
Thanks @douglowder. I'll check internally about what can be done access-wise. In the same branch, there is one other blocking issue - In tvOS, once I have navigated to the main menu, I can't navigate away from it again. It also seems like a focus issue and may even be the same issue. Clearly though I'll need to dive a bit deeper and look at the focusing differences between the two platforms.

**Comment by douglowder** [comment]
I did get access to work so I can now run the app.... I'll keep you posted

**Comment by douglowder** [comment]
I do see that in Apple TV, your app won't be able to use the menu key for navigating back, without enabling the menu key gesture handler using the `TVMenuControl` utility. I believe the changes you want are in https://github.com/douglowder/stream-tv-app/commit/e07c43ffa72f944437c71fb113d430734de49d77

I'm continuing to look at the focus ordering issue.

**Comment by douglowder** [comment]
I see that Android TV and Apple TV both work fine if you wait to activate <GoBack /> until useFocusEffect() runs, and I think that's probably what you want for React Navigation... don't show the back UI until after the screen has the navigation focus.  https://github.com/douglowder/stream-tv-app/commit/2bb4918fa5e6b750f5c0d603c353dd2c81fb21b1

**Comment by sinewave440hz** [comment]
Thanks for both of these suggestions @douglowder, very useful. The original issue is solved with this. However, there is this issue with the nav menu where I can't navigate away from it, once it has focus. I suspect that tracking this would be useful for others too...shall I create a new issue for that?

**Comment by douglowder** [comment]
I think the problem that you are having is that once you move to the nav menu, you are near the top and there are no focusables directly to the right -- the focusables are all way down below.  In this case, you may want to create a `UIFocusGuideView` for Apple TV, or use the `nextFocusRight` API for Android TV.  If this is not the problem, then go ahead and create a new issue for it.

**Comment by douglowder** [comment]
For example, I think this hack (which makes the entire Preview component focusable) actually makes it so you can navigate away from the left hand menu. https://github.com/douglowder/stream-tv-app/commit/fd4e1282ead8f8d8bbae031853d275aef0dea578

**Comment by sinewave440hz** [comment]
Aha, yes, that's great thank you. Following your suggested hack gets me away from the menu, but doesn't quite give me the focus behaviour I need; We need focus going straight to the top swim lane in this case. I should be able to get that to work using something similar. 

Is there a convenient way of debugging focus issues like this? Some way of presenting a list of current focusables, such that one can visualise problems such as you described two comments ago?

**Comment by sinewave440hz** [comment]
Still not sure actually whether I should create a new issue for this. To clarify a bit, the android navigation away from the menu works correctly - I expect that nextFocusRight is used correctly there by react-navigation. In tvOS however, we are relying on `hasTVPreferredFocus` being updated correctly per `DigitalEventItem`, which isn't happening when the menu item changes. Looking at how to get that to happen...

**Comment by douglowder** [comment]
Yes please create a new issue for this. The right way to fix this is with `TVFocusGuideView`, but it seems tricky to get that to work correctly in this app for some reason.
