### ISSUE TITLE
Upgrade to 0.66.2?

### ISSUE THREAD

**Issue by sidferreira** [react-native-tvos/react-native-tvos#240]
I just found out about `react-native-tvos`, but our project is based on `rn 0.66.2`.
I wonder if it is possible to monorepo it or something, or an "easy" way to apply the current changes to newer RN branches...
Or that's actually "too different to reconcile"?

**Comment by douglowder** [comment]
This subject is covered in the first item in the FAQ: https://github.com/react-native-tvos/react-native-tvos/wiki/FAQs

Among other things, supporting tvOS requires an additional tvOS Xcode scheme to be added to the Xcode project for your app. This and a number of other changes would be difficult to support as a patch.

I will move this repo to 0.66.x in the near future, after dealing with some other issues.

**Comment by sidferreira** [comment]
@douglowder our project is very old, we still have a tvOS scheme there 😄 I just want to avoid a 2nd repo just for TV...

**Comment by frankenthumbs** [comment]
i have an iteration of upgrading to 0.66.4 here: https://github.com/frankenthumbs/react-native-tvos/tree/tvos-v0.66.4
i'm stuck on running `./scripts/tvos-test.sh`, most of the tests seems fine.

some of the color tests are failing (i believe its failing on this repo as well)
```
    ✗ testGenerateFallbacks, ((red1) equal to (red2)) failed: ("120") is not equal to ("255")
    ✗ testGenerateFallbacks, ((green1) equal to (green2)) failed: ("120") is not equal to ("255")
    ✗ testGenerateFallbacks, ((blue1) equal to (blue2)) failed: ("128") is not equal to ("255")
    ✗ testGenerateFallbacks, ((red1) equal to (red2)) failed: ("60") is not equal to ("0")
    ✗ testGenerateFallbacks, ((green1) equal to (green2)) failed: ("60") is not equal to ("0")
    ✗ testGenerateFallbacks, ((blue1) equal to (blue2)) failed: ("67") is not equal to ("0")
    ✗ testGenerateFallbacks, ((alpha1) equal to (alpha2)) failed: ("76") is not equal to ("102")
    ✗ testGenerateFallbacks, ((red1) equal to (red2)) failed: ("120") is not equal to ("255")
    ✗ testGenerateFallbacks, ((green1) equal to (green2)) failed: ("120") is not equal to ("255")
    ✗ testGenerateFallbacks, ((blue1) equal to (blue2)) failed: ("128") is not equal to ("255")
    ✗ testGenerateFallbacks, ((red1) equal to (red2)) failed: ("116") is not equal to ("255")
    ✗ testGenerateFallbacks, ((green1) equal to (green2)) failed: ("116") is not equal to ("255")
    ✗ testGenerateFallbacks, ((blue1) equal to (blue2)) failed: ("128") is not equal to ("255")
    ✗ testGenerateFallbacks, ((red1) equal to (red2)) failed: ("60") is not equal to ("0")
    ✗ testGenerateFallbacks, ((green1) equal to (green2)) failed: ("60") is not equal to ("0")
    ✗ testGenerateFallbacks, ((blue1) equal to (blue2)) failed: ("67") is not equal to ("0")
    ✗ testGenerateFallbacks, ((red1) equal to (red2)) failed: ("60") is not equal to ("0")
    ✗ testGenerateFallbacks, ((green1) equal to (green2)) failed: ("60") is not equal to ("0")
    ✗ testGenerateFallbacks, ((blue1) equal to (blue2)) failed: ("67") is not equal to ("0")
    ✗ testGenerateFallbacks, ((alpha1) equal to (alpha2)) failed: ("76") is not equal to ("102")
    ✗ testGenerateFallbacks, ((red1) equal to (red2)) failed: ("60") is not equal to ("0")
    ✗ testGenerateFallbacks, ((green1) equal to (green2)) failed: ("60") is not equal to ("0")
    ✗ testGenerateFallbacks, ((blue1) equal to (blue2)) failed: ("67") is not equal to ("0")
    ✗ testGenerateFallbacks, ((alpha1) equal to (alpha2)) failed: ("45") is not equal to ("51")
    ✗ testGenerateFallbacks, ((red1) equal to (red2)) failed: ("118") is not equal to ("255")
    ✗ testGenerateFallbacks, ((green1) equal to (green2)) failed: ("118") is not equal to ("255")
    ✗ testGenerateFallbacks, ((blue1) equal to (blue2)) failed: ("128") is not equal to ("255")
```
as well as the more concerning UI snapshot tests. I believe we need to get new snapshots of these tests but i'm not sure how the snapshots are taken:
```
    ✗ testLayoutExample, Test failed (NSInternalInconsistencyException)
    ✗ testScrollViewExample, Test failed (NSInternalInconsistencyException)
    ✗ testTextExample, Test failed (NSInternalInconsistencyException)
    ✗ testTVFocusGuideExample, RedBox errors: (
    ✗ testViewExample, Test failed (NSInternalInconsistencyException)
```
from the `png`s found in `react-native/packages/rn-tester/RNTesterIntegrationTests/ReferenceImages/RNTester-js-RNTesterApp.ios` it seems like some of the views got upgraded:

screenshot taken from the app:
![Uploading Screen Shot 2021-12-20 at 10.22.02 AM.png…]()

screenshot from main:
https://github.com/frankenthumbs/react-native-tvos/blob/tvos-v0.66.4/packages/rn-tester/RNTesterIntegrationTests/ReferenceImages/packages-rn-tester-js-RNTesterApp.ios/testTextExample_1-iOS15_tvOS.png

gonna try integrating with our applications and see if everything is working there.
But it would be nice to get the snapshot UI tests working as I know this is something Doug makes sure on every iteration

**Comment by douglowder** [comment]
Thanks @frankenthumbs for the work and for the heads up about the test failures. I've got a branch going for the upgrade (tvos-v0.66.3) and did notice that the commits for RNTester are not applying cleanly, seems that there have been quite a few changes there. I'll be looking into that next and hopefully figure it out.

**Comment by frankenthumbs** [comment]
Hey @douglowder thank you for your quick response during the holiday season and all your work. I think i'll keep working on that branch just for my own edification but we'll probably end up going with your branch :D 

Please let us know if we can help in any way.

**Comment by douglowder** [comment]
@frankenthumbs After fixing some merge issues, I now have all the tests working. The failures in the color tests were due to the fact that some of the colors in the list don't exist on tvOS.  There's still a bit more work to do but things are looking up :)

**Comment by douglowder** [comment]
I have all the TV patches from the 0.64 release train applied, and all RNTester integration and unit tests pass. Here is a test build:
[react-native-tvos-0.66.3-0.tar.gz](https://github.com/react-native-tvos/react-native-tvos/files/7798407/react-native-tvos-0.66.3-0.tar.gz) I'll be testing this with the React Native CLI new project generator, the React Native TV Typescript template, and various other demo projects.

**Comment by douglowder** [comment]
Release looks good and is published to NPM. See release notes at https://github.com/react-native-tvos/react-native-tvos/releases/tag/v0.66.3-0

**Comment by miblanchard** [comment]
@douglowder - Thanks again for your great work with this.

**Comment by douglowder** [comment]
@miblanchard You're welcome!
