### ISSUE TITLE
TvEventHandler eventKeyAction to 0

### ISSUE THREAD

**Issue by mhovanisian** [react-native-tvos/react-native-tvos#249]
Looks like the tvEventHandler no more trigger eventKeyAction to zero like before
![Capture d’écran du 2022-01-03 16-54-47](https://user-images.githubusercontent.com/87751719/147951765-1d75b87a-a27f-4a0d-8f34-cd2db878b4db.png)

**Comment by douglowder** [comment]
This is expected, and is a side effect of the fix implemented for #233 .

**Comment by mansilaad** [comment]
Still facing same issue...
