### ISSUE TITLE
[Question] AppleTV Compatibility

### ISSUE THREAD

**Issue by sidferreira** [react-native-tvos/react-native-tvos#253]
What AppleTV devices were tested and known to work?

**Comment by douglowder** [comment]
Referring to the list of models on https://support.apple.com/en-us/HT200008 :

Tested and known to work:

- Apple TV HD (A1625)
- Apple TV 4K 1st generation (A1842)
- Apple TV 4K 2nd generation (A2169)

I believe RN should also work on Apple TV 3rd generation (A1427 or A1469), but am not 100% certain.

Not sure it will work on Apple TV 2nd generation (A1378).

It will not work on Apple TV 1st generation (A1218).
