### ISSUE TITLE
Adding latest Expo modules (v44) to react-native-tvos

### ISSUE THREAD

**Issue by beauner69** [react-native-tvos/react-native-tvos#261]
Headline: It doesn't build unless you limit your Podfile to iOS or tvOS target (not both)

## Description

I am trying to get the latest expo-modules working with the latest release of react-native-tvos. From what I understand they should be generally compatible.

The expo modules installation method has changed:
https://docs.expo.dev/bare/installing-expo-modules/

My goal is to get it to build correctly. 

Build fails with expo added to both the iOS and tvOS targets - 
Fails with message:

~/Library/Developer/Xcode/DerivedData/TestApp-aqfbzlikdgqvcnfdesjdsqhzdzvq/Build/Intermediates.noindex/Pods.build/Debug-appletvsimulator/ExpoModulesCore-tvOS.build/DerivedSources/ExpoModulesCore-Swift.h:353:32: Cannot find interface declaration for 'RCTViewManager', superclass of 'ViewModuleWrapper'; did you mean 'EXViewManager'?

Build passes if you completely remove either iOS or tvOS target from the Podfile - Although obviously only works for the remaining target.

Searching for solutions led me to this issue:
https://github.com/expo/expo/issues/15622#issuecomment-998680225

This issue mentions interaction between swift and objc in “the latest new way of doing modules”, how cocoapods sets up its projects, mentions of header files being angle-brackets instead of quotes, and problems when Xcode tries to generate its own interim files.

I don’t know enough about cocoapods and the Xcode build process but I think this might be related since in digging around a lot of the issues resonated.

As I said, if you use only one target you can get a successful build. Since I have a monorepo I can have an iOS app and a tvOS app and build them separately. I recommend this for people who want to get on with their work. Would be ideal to solve this problem though so I’d appreciate any help.

## React Native version:
Run react-native info in your terminal and copy the results here.
info Fetching system and libraries information...
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 135.63 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.15.1 - /usr/local/bin/npm
    Watchman: 2021.12.27.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.9 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.66.3-1 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

See repo section below. The following is a summary how I made it.

react-native init TestApp --template=react-native-tvos@latest
npx install-expo-modules

Modify Podfile to include use_expo_modules! for both targets
Patch various modules to make them build under TVOS

Load up Xcode and try to build the iOS version

## Expected Results
One single Podfile with both iOS and tvOS targets, building either target without incident.

## Snack, code example, screenshot, or link to a repository:

Based on this repo: 
https://github.com/beauner69/react-native-unimodules-example

I made a PR:
https://github.com/react-native-tvos/react-native-unimodules-example/pull/1

It is set up in the failure state.

```
yarn install
cd ios
pod install
xed .
```
Build either target and experience the failure.

To try different modes change the Podfile - choose from
Podfile-ios
Podfile-tvos
Podfile-both

Thank you to anyone who has a look at this!

**Comment by douglowder** [comment]
I'll take a look (may be a few days), and track the issue in your PR, as it is expo-specific.

**Comment by beauner69** [comment]
I can confirm that, once you get it to build on tvOS (by removing iOS from the podspec), the following modules work properly in tvOS:

expo-font
expo-keep-awake
expo-linear-gradient
expo-blur

**Comment by douglowder** [comment]
This is something I am now actively working on, and I will post updates here as I make progress.

**Comment by mdrokz** [comment]
Are there any updates on this ?
