### ISSUE TITLE
[Android TV] D-pad navigation scrolls list instead of of focusing on next item (large lists only)

### ISSUE THREAD

**Issue by yuriazevedo11** [react-native-tvos/react-native-tvos#263]
## Description
Hey @douglowder, first off, huge fan of the work here 👏 .
Can you help me out with this one?

I'm having the exact same problem stated on both issues on the core repo, but this is also happens on react-native-tvos (tested on latest version, 0.66.3-1):
- https://github.com/facebook/react-native/issues/26133
- https://github.com/facebook/react-native/issues/20099

Unfortunatly I wasn't able to find a solution. I thought about setting nextFocusDirection on each element, however, this would require applying the same logic on all directions on a Grid list for example, it will become unmanageable and very hard to maintain this code in the future

## React Native version:
System:
    OS: macOS 11.6.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 1.04 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /var/folders/th/9r1rl9gx4pn9p74l961g7nyc0000gp/T/yarn--1645212920682-0.8213002760484727/node
    Yarn: 1.22.17 - /var/folders/th/9r1rl9gx4pn9p74l961g7nyc0000gp/T/yarn--1645212920682-0.8213002760484727/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2021.10.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 26, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
      System Images: android-25 | Android TV Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-29 | Android TV Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.14.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.66.3-1 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by douglowder** [comment]
I'll take a look!

- Do you have a working example I can start up and try?
- Have you tried setting `focusable={false}` on the ScrollView?

**Comment by yuriazevedo11** [comment]
Still doesn't work with `focusable={false}`. I'll create an example based on the screen we are working on

**Comment by yuriazevedo11** [comment]
Created a new react-native-tvos project with template `react-native-template-typescript-tv`
![Screen Shot 2022-02-18 at 18 57 17](https://user-images.githubusercontent.com/51724047/154766775-43882339-09aa-4a82-bfae-fa6dad2fcb95.png)


Using emulator: ![Screen Shot 2022-02-18 at 18 55 44](https://user-images.githubusercontent.com/51724047/154766604-79ed1238-ef00-476b-8d97-dc10413bfeb7.png)

```tsx
import React, {useState} from 'react';
import {
  StyleSheet,
  ScrollView,
  View,
  Text,
  TouchableOpacity,
} from 'react-native';

import 'react-native/tvos-types.d';

const PROGRAMS_LIST = new Array(100)
  .fill(0)
  .map((_, index) => `Program ${index + 1}`);

interface FilterProps {
  text: string;
  initialFocus?: boolean;
}

const Filter = ({text, initialFocus}: FilterProps) => {
  const [isFocused, setIsFocused] = useState(false);

  const onFocusChange = () => {
    setIsFocused((state) => !state);
  };

  return (
    <TouchableOpacity
      hasTVPreferredFocus={initialFocus}
      style={{...styles.filter, ...(isFocused ? styles.focusedItem : {})}}
      onFocus={onFocusChange}
      onBlur={onFocusChange}
      activeOpacity={1}>
      <Text style={styles.filterText}>{text}</Text>
    </TouchableOpacity>
  );
};

const Sidebar = () => {
  return (
    <View style={styles.sidebar}>
      <Text style={styles.title}>Search programs</Text>

      <View style={styles.textField}>
        <Filter text="Fake text field" initialFocus />
      </View>

      <Text style={styles.filterGroupTitle}>Group 1</Text>
      <View style={styles.filterGroup}>
        <Filter text="Filter 1" />
        <Filter text="Filter 2" />
        <Filter text="Filter 3" />
      </View>

      <Text style={styles.filterGroupTitle}>Group 2</Text>
      <View style={styles.filterGroup}>
        <Filter text="Filter 4" />
        <Filter text="Filter 5" />
        <Filter text="Filter 6" />
      </View>

      <Text style={styles.filterGroupTitle}>Group 3</Text>
      <View style={styles.filterGroup}>
        <Filter text="Filter 7" />
        <Filter text="Filter 8" />
        <Filter text="Filter 9" />
      </View>
    </View>
  );
};

const CARD_HEIGHT = 150;
const CARD_WIDTH = 270;

const ProgramCard = ({name}: {name: string}) => {
  const [isFocused, setIsFocused] = useState(false);

  const onFocusChange = () => {
    console.log(isFocused ? `blur: ${name}` : `focus: ${name}`);
    setIsFocused((state) => !state);
  };

  return (
    <TouchableOpacity
      style={{...styles.card, ...(isFocused ? styles.focusedItem : {})}}
      onFocus={onFocusChange}
      onBlur={onFocusChange}
      activeOpacity={1}>
      {/* Image background */}
    </TouchableOpacity>
  );
};

const Content = () => {
  return (
    <View style={styles.content}>
      <ScrollView contentContainerStyle={styles.scrollView} focusable={false}>
        <Text style={styles.contentTitle}>
          Programs ({PROGRAMS_LIST.length})
        </Text>

        <View style={styles.programGrid}>
          {PROGRAMS_LIST.map((program) => (
            <ProgramCard key={program} name={program} />
          ))}
        </View>
      </ScrollView>
    </View>
  );
};

const App = () => {
  return (
    <View style={styles.container}>
      <Sidebar />
      <Content />
    </View>
  );
};

const styles = StyleSheet.create({
  focusedItem: {
    borderColor: 'orange',
  },
  container: {
    flexDirection: 'row',
    flex: 1,
  },
  sidebar: {
    height: '100%',
    width: '33%',
    backgroundColor: '#2e2d2d',
    paddingVertical: 20,
    paddingHorizontal: 30,
  },
  content: {
    width: '67%',
    backgroundColor: '#1c1c1c',
  },
  scrollView: {
    paddingVertical: 20,
    paddingHorizontal: 30,
    flexGrow: 1,
  },
  title: {
    color: 'white',
    fontSize: 20,
    marginBottom: 10,
  },
  contentTitle: {
    color: 'white',
    fontSize: 20,
  },
  filterGroup: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  filterGroupTitle: {
    marginTop: 10,
    color: 'white',
    fontSize: 18,
  },
  filter: {
    borderWidth: 1,
    borderColor: 'transparent',
    padding: 10,
    marginTop: 10,
    marginRight: 10,
    backgroundColor: '#1c1c1c',
  },
  filterText: {
    color: 'white',
    fontSize: 14,
  },
  card: {
    borderWidth: 1,
    height: CARD_HEIGHT,
    width: CARD_WIDTH,
    marginTop: 20,
    marginRight: 20,
    borderColor: 'transparent',
    backgroundColor: '#2e2d2d',
  },
  programGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  textField: {
    marginBottom: 20,
  },
});

export default App;

```

**Comment by douglowder** [comment]
Well for me, the focus does indeed move to the next item as expected. I'm seeing correct behavior (as far as I can tell) on Android TV emulator.

**Comment by douglowder** [comment]
Here is what I am seeing...

https://user-images.githubusercontent.com/6577821/154773919-70005e71-81ef-42d2-af11-c693026d10e8.mov

(I made a couple of minor changes to your app for correct initialization and easier visibility of the cells...)

```diff
--- App.tsx.orig	2022-02-18 15:23:31.000000000 -0800
+++ App.tsx	2022-02-18 15:20:02.000000000 -0800
@@ -19,7 +19,7 @@
 }
 
 const Filter = ({text, initialFocus}: FilterProps) => {
-  const [isFocused, setIsFocused] = useState(false);
+  const [isFocused, setIsFocused] = useState(initialFocus);
 
   const onFocusChange = () => {
     setIsFocused((state) => !state);
@@ -88,6 +88,9 @@
       onBlur={onFocusChange}
       activeOpacity={1}>
       {/* Image background */}
+      <Text style={styles.filterText}>
+        {name}
+      </Text>
     </TouchableOpacity>
   );
 };
```

**Comment by yuriazevedo11** [comment]
Which Android version is your emulator running?

This problem only happens on versions: 7 ~ 8, it works as expected on 9+. My bad if I wasn't clear about it

**Comment by douglowder** [comment]
Yikes I will fire up a different emulator then. May not be fixable but we'll give it a shot.

**Comment by douglowder** [comment]
Wow it is really messed up on API 26. Looks like it might be related to https://stackoverflow.com/questions/54904603/android-tv-focus-moved-to-view-in-scrollview-that-is-outside-visible-part-of-sc 

I'll try a few things.

**Comment by yuriazevedo11** [comment]
Where should I set `accessible={false}`? I tryed using it on the ScrollView, no changes (API 25)

**Comment by douglowder** [comment]
Hmm I set `accessible={false} focusable={false}` on API 26, and do see an improvement. I'll test API 25.

**Comment by douglowder** [comment]
Ok API 25 still shows bad behavior with ScrollView.  Best solution: use FlatList. :)

For FlatList, you have to specify the number of columns, which appears to be 2 for your layout and component sizes on Android TV.

```diff
--- App.tsx.orig	2022-02-18 15:23:31.000000000 -0800
+++ App.tsx	2022-02-20 18:24:26.000000000 -0800
@@ -1,10 +1,11 @@
 import React, {useState} from 'react';
 import {
   StyleSheet,
-  ScrollView,
+  FlatList,
   View,
   Text,
   TouchableOpacity,
+  ListRenderItem,
 } from 'react-native';
 
 import 'react-native/tvos-types.d';
@@ -19,7 +20,7 @@
 }
 
 const Filter = ({text, initialFocus}: FilterProps) => {
-  const [isFocused, setIsFocused] = useState(false);
+  const [isFocused, setIsFocused] = useState(initialFocus);
 
   const onFocusChange = () => {
     setIsFocused((state) => !state);
@@ -88,6 +89,7 @@
       onBlur={onFocusChange}
       activeOpacity={1}>
       {/* Image background */}
+      <Text style={styles.filterText}>{name}</Text>
     </TouchableOpacity>
   );
 };
@@ -95,17 +97,19 @@
 const Content = () => {
   return (
     <View style={styles.content}>
-      <ScrollView contentContainerStyle={styles.scrollView} focusable={false}>
-        <Text style={styles.contentTitle}>
-          Programs ({PROGRAMS_LIST.length})
-        </Text>
-
-        <View style={styles.programGrid}>
-          {PROGRAMS_LIST.map((program) => (
-            <ProgramCard key={program} name={program} />
-          ))}
-        </View>
-      </ScrollView>
+      <FlatList
+        contentContainerStyle={styles.scrollView}
+        data={PROGRAMS_LIST}
+        renderItem={({item}) => {
+          return <ProgramCard key={item} name={item} />;
+        }}
+        ListHeaderComponent={() => (
+          <Text style={styles.contentTitle}>
+            Programs ({PROGRAMS_LIST.length})
+          </Text>
+        )}
+        numColumns={2}
+      />
     </View>
   );
 };
```

**Comment by yuriazevedo11** [comment]
Cool, I'll try this

**Comment by yuriazevedo11** [comment]
Sorry for the late response, worked like a charm :)

Still don't know exactly why this problem happens on these API levels, but thanks alot, it was a huge help

**Comment by StevenPurn** [comment]
Sorry to resurrect an old issue but I'm able to reproduce this behavior on `0.71.12-0` using a `FlatList` while `ScrollView` seems to work as expected. Based on my understanding of this thread, that's the opposite of what I should anticipate. I'm happy to open a new issue if that's preferred.

Here is an example demonstrating that on an Android emulator (running tiramisu API level 33)
- ScrollView always scrolls newly focused items into view
- FlatList with `removeClippedSubviews` set to `true` (the default setting on Android) will exhibit the behavior described in the original message in this thread
- FlatList with `removeClippedSubviews` set to `false` will also always scroll newly focused items into view

Note that on tvOS the desired behavior of scrolling the newly focused item into view is exhibited in all cases.

[android-scroll-example.webm](https://github.com/react-native-tvos/react-native-tvos/assets/8118591/c9358a2d-81d9-430d-b952-24f17b43ebfe)

So I have a few questions to clarify the expectations here. 

1. Is the exhibited behavior expected?
2. If not, is the recommendation to always set `removeClippedSubviews` to `false`?

Here is a gist with the relevant code used in the example, most of it is taken from this thread but slightly modified.
https://gist.github.com/StevenPurn/9d8b7d99fdf537455df8001be95ae3f3

**Comment by Diyaa-2324** [comment]
I need to Keep the focus on first item of the list and scroll the list using android studio(java)
please help me out..
