### ISSUE TITLE
[Discussions and Proposals]Is there any way to control focus move to specific button on android?

### ISSUE THREAD

**Issue by lnwanghao** [react-native-tvos/react-native-tvos#264]
## Description
Sometimes, there will be some requirements that specify the focus. For example，4 buttons on the page,  ABCD；I want to move focus from A to D directly; 

![image](https://user-images.githubusercontent.com/17587836/155289650-3e5d8787-edff-4604-afa0-956156bd2683.png)

TouchableHighlight nextFocus are inconvenient to use。

**Comment by lnwanghao** [comment]
> I think you have to use the nextFocus implementation.
> 
> If not, you can try on the event blur of the component A to set the hasTVPreferredFocus to true on the component D.
I've tried this before.But the button has default behavior, for example，foucs is on A now and click right, B gets the focus first, and then D gets the focus.

**Comment by lnwanghao** [comment]
> I think you have to use the nextFocus implementation.
> 
> If not, you can try on the event blur of the component A to set the hasTVPreferredFocus to true on the component D.

I've tried this before.But the button has default behavior, for example，foucs is on A now and click right, B gets the focus first, and then D gets the focus.

**Comment by lnwanghao** [comment]
> I think you have to use the nextFocus implementation.
> 
> If not, you can try on the event blur of the component A to set the hasTVPreferredFocus to true on the component D.

I've tried this before.But the button has default behavior, for example，focus is on A now and click right, B gets the focus first, and then D gets the focus.

**Comment by nriccar** [comment]
I see. Thats the expected behaviour, I think.

But! for the nextFocus that should not happen, as I see it it should focus directly the D component

**Comment by lnwanghao** [comment]
> I see. Thats the expected behaviour, I think.
> 
> But! for the nextFocus that should not happen, as I see it it should focus directly the D component

Can you provide some code examples about how to use nextFocus？I was confused with [https://reactnative.dev/docs/view#nextfocusdown-android](react native document).
Thanks~

**Comment by nriccar** [comment]
I think there's an example on https://github.com/react-native-tvos/react-native-tvos/blob/740fecdaef5ebc3460e312685228f6501efe53db/packages/rn-tester/js/examples/DirectionalNextFocus/DirectionalNextFocusExample.js

Basically, what you need to do is store the ref of the component you want to force focus to, in this case D:
```
import {
  TouchableOpacity,
  findNodeHandle,
} from 'react-native'

...

<TouchableOpacity
 ref={(component) => {
            const nextFocus = findNodeHandle(component)
          }
        }}
/>
```

And from the component you want to force the next focus, in this case A:
```
<TouchableOpacity
 nextFocusDown={nextFocus}
/>
```

I recommend having a global state manager so that this is easily achievable from different components nested in your components tree..

I was able to manage it by having a focus context and saving the forced next focus directions with this schema:
```
{
    up: null,
    right: null,
    down: null,
    left: null,
}
```

And on the component:
```
<TouchableOpacity
 nextFocusDown={focus.down}
/>
```

for example..

Hope it helps!

**Comment by lnwanghao** [comment]
> I think there's an example on https://github.com/react-native-tvos/react-native-tvos/blob/740fecdaef5ebc3460e312685228f6501efe53db/packages/rn-tester/js/examples/DirectionalNextFocus/DirectionalNextFocusExample.js
> 
> Basically, what you need to do is store the ref of the component you want to force focus to, in this case D:
> 
> ```
> import {
>   TouchableOpacity,
>   findNodeHandle,
> } from 'react-native'
> 
> ...
> 
> <TouchableOpacity
>  ref={(component) => {
>             const nextFocus = findNodeHandle(component)
>           }
>         }}
> />
> ```
> 
> And from the component you want to force the next focus, in this case A:
> 
> ```
> <TouchableOpacity
>  nextFocusDown={nextFocus}
> />
> ```
> 
> I recommend having a global state manager so that this is easily achievable from different components nested in your components tree..
> 
> I was able to manage it by having a focus context and saving the forced next focus directions with this schema:
> 
> ```
> {
>     up: null,
>     right: null,
>     down: null,
>     left: null,
> }
> ```
> 
> And on the component:
> 
> ```
> <TouchableOpacity
>  nextFocusDown={focus.down}
> />
> ```
> 
> for example..
> 
> Hope it helps!

It works well! I think the point is how to store each ref the button want to move and how to update it.
Thanks!

**Comment by nriccar** [comment]
Yes! The main thins is being clean storing the refs.

Glad it helped!
