### ISSUE TITLE
Android TV: hardware keyboard events are not fired unless a ScrollView is in current view heirarchy

### ISSUE THREAD

**Issue by joeflateau** [react-native-tvos/react-native-tvos#303]
### Description

Hardware keyboard events (aka TVEvents) are not fired unless there is a ScrollView in the current hierarchy. In my use case, the actual video player screen listens to a "up" event to show a tray/overlay but it does not work on Android because "up" is never triggered. The keyboard events are also not fired if you attempt to listen to them through the `NativeAppEventEmitter` class, ie: 

```tsx
NativeAppEventEmitter.addListener('onHWKeyEvent', (ev) => console.log({ ev }));
```

### Version

tvos-0.68.1-1

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 213.42 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.4 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.1-1 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Minimal repro here: https://github.com/joeflateau/react-native-tvos-AndroidTVHWKBEventsRepro

Launch in Android TV (`npm run android`) and attempt to navigate with your remote control or keyboard. You will not get any feedback on screen nor events logged to console. Now comment out the `<View />` and uncomment the `<ScrollView />` in `./App.tsx` and try again, you will get key events logged and displayed on screen.

### Snack, code example, screenshot, or link to a repository

https://github.com/joeflateau/react-native-tvos-AndroidTVHWKBEventsRepro

**Comment by douglowder** [comment]
This is definitely reproducible -- will take a look.

**Comment by joeflateau** [comment]
cool, I would try to help but I haven't figured out how to run react-native-tvos from source yet

**Comment by douglowder** [comment]
Ok I did some digging and there are two ways to modify the app to get the HW events back, without making any native changes or using `<ScrollView />`:

- Adding at least one control (`<TouchableOpacity />`, `<Pressable />`, etc.)
- Setting `accessible={true}` on the `<View />`

It may be that what you are seeing is an optimization, where key events are not implemented unless actually needed.

**Comment by joeflateau** [comment]
interesting... so this strikes me as either a bug in react-native (not react-native-tvos) or just working as intended, sound right to you?

**Comment by douglowder** [comment]
I'm inclined to think that indeed this is working as designed. The HW events are only needed if there is actually something on the screen to interact with (scroll view, control, or text input).

I'll go ahead and close this. Feel free to reopen if you see any other related issues and I'll take a look.
