### ISSUE TITLE
No v0.68.1-x release in rn-diff-purge-tv

### ISSUE THREAD

**Issue by joeflateau** [react-native-tvos/react-native-tvos#304]
### New Version

0.66.3-0

### Old Version

0.68.1-1

### Build Target(s)

N/A

### Output of `react-native info`

N/A

### Issue and Reproduction Steps

My understanding is that the rn-diff-purge-tv release branches are created as a result of publishing releases to this repo, however, neither of 0.68.1-0 or 0.68.1-1 releases have release branches in the https://github.com/react-native-tvos/rn-diff-purge-tv repo. I'm assuming a Github Action was inadvertently removed or something along those lines

**Comment by douglowder** [comment]
@joeflateau this should be fixed now -- please verify and close if the upgrade is working now.

**Comment by joeflateau** [comment]
@douglowder much appreciated, it does seem to be working now 🤘

**Comment by joeflateau** [comment]
oops, missed the part where you asked me to close this after verifying, sorry
