### ISSUE TITLE
nextFocusDown, nextFocusLeft and nextFocusUp not working

### ISSUE THREAD

**Issue by aman-singh-unthinkable** [react-native-tvos/react-native-tvos#306]
### Description

In tvOS nextFocusDown, nextFocusLeft and nextFocusUp not working only nextFocusRight is working but in android all are working.

### Version

react-native-tvos@0.68.1-1

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 675.79 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.1-1 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

.

**Comment by douglowder** [comment]
This has to do with the way this feature is implemented in tvOS; nextFocusLeft only works if there is already a focusable view to the left (similarly for the other nextFocus methods). Android TV does not have this limitation, it is directly using the corresponding native APIs.

I have an idea about how to make this work as intended on tvOS and will take a look this week.
