### ISSUE TITLE
 Error: Unable to find node on an unmounted component.

### ISSUE THREAD

**Issue by MathieuHERY** [react-native-tvos/react-native-tvos#315]
### Description

Hi, 

I have a side menu with differents components which i use to display once user has pressed the icon. 
I have a search component at the bottom of the side menu which is used by user to search content related to his query. 
Input field is hidden in the side menu and focus on the input field is triggered once user has pressed the search icon. 
Once done, we present all the results. 
If the user pressed again the search icon, we trigger again the input field. 
But when users wants to go back and press the home icon on the side menu, i got an error ' Error: Unable to find node on an unmounted component.'

thanks for your help :)

<img width="955" alt="Capture d’écran 2022-06-20 à 15 59 56" src="https://user-images.githubusercontent.com/81353097/174618975-e7f80291-2cde-4071-8c90-2fc7e804f71a.png">
<img width="1472" alt="Capture d’écran 2022-06-20 à 16 00 43" src="https://user-images.githubusercontent.com/81353097/174619027-3aac9f03-d617-4386-ab2c-f1be67ed69c6.png">
<img width="1467" alt="Capture d’écran 2022-06-20 à 16 01 51" src="https://user-images.githubusercontent.com/81353097/174619196-8a3dfd8c-1d75-4fcb-bad6-cfb79cef4f91.png">

### Version

react-native-cli: 2.0.1 react-native: 0.68.1-1

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 5.66 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.9.0 - /opt/homebrew/bin/npm
    Watchman: 2022.06.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.14.0 => 16.14.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.1-1 

### Steps to reproduce

I have a side menu with differents components which i use to display once user has pressed the icon. 
I have a search component at the bottom of the side menu which is used by user to search content related to his query. 
Input field is hidden in the side menu and focus on the input field is triggered once user has pressed the search icon. 
Once done, we present all the results. 
If the user pressed again the search icon, we trigger again the input field. 
But when users wants to go back and press the home icon on the side menu, i got an error ' Error: Unable to find node on an unmounted component.'

**Comment by douglowder** [comment]
I would recommend that you move to 0.68.2-1. If that does not fix the problem, I would need a code sample from you that reproduces the issue.

**Comment by MathieuHERY** [comment]
thanks @douglowder for your feedback.  The issue seems fixed. I can't reproduce after upgrading react-native tvOS version.
