### ISSUE TITLE
Unable to find a specification for `React-RCTFabric` depended upon by `RNGestureHandler`

### ISSUE THREAD

**Issue by pisacode** [react-native-tvos/react-native-tvos#316]
### Description

Hi,

After upgrading from react-native-tvos 66 to 68.2-1 I can no longer do a `pod install` It always throws this error

```
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `fmt` from `../node_modules/react-native/third-party-podspecs/fmt.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] Unable to find a specification for `React-RCTFabric` depended upon by `RNGestureHandler`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.


[!] [Codegen] warn: using experimental new codegen integration
```

I have tried updating other librarys too but no luck.

My pod file is like this 
```
platform :tvos, '12.0'
workspace 'TvApp'
project 'TvApp.xcodeproj'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/react-native-tvos/react-native-tvos-podspecs.git'
source 'https://cdn.cocoapods.org/'
install! 'cocoapods', :deterministic_uuids => false



target 'TvApp' do
  # Uncomment for Swift
  # use_frameworks!

  config = use_native_modules!

    use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
    )

end


post_install do |installer|
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end

```

### Version

68

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 194.27 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 6.14.16 - /opt/homebrew/bin/npm
    Watchman: 2022.02.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.2-1 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

-

**Comment by douglowder** [comment]
There is definitely something bizarre going on. After the upgrade, it appears that you have enabled the React Native new architecture (Fabric) somehow. That's the source of the message
```
[!] [Codegen] warn: using experimental new codegen integration
```

Try modifying your Podfile as
```rb
    use_react_native!(
    :path => config[:reactNativePath],
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
    )
```
then delete your Pods and rerun `pod install`.
