### ISSUE TITLE
 Manual  hasTVPreferredFocus not working fine

### ISSUE THREAD

**Issue by aniketgupta8960** [react-native-tvos/react-native-tvos#320]
### Description

We are using hasTVPreferredFocus to focus on button in scrollview but the focus is not happening smoothly .First the default button is highlighted and after some milliseconds the manual highlighting happens which makes the UI experiences not good.we are doing focus of button by own and tvos doing it also. So how we can stop default focus of button inside scrollview
<img width="1440" alt="Screenshot 2022-07-07 at 8 54 26 PM" src="https://user-images.githubusercontent.com/74759255/177813032-949b8c87-0af1-464c-8113-6251fd1f9d86.png">
<img width="1440" alt="Screenshot 2022-07-07 at 8 54 43 PM" src="https://user-images.githubusercontent.com/74759255/177813086-a3de06db-6b90-4aaf-9421-45232c235780.png">
![Uploading Screenshot 2022-07-07 at 8.55.02 PM.png…]()

### Version

0.68.1

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 42.96 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/‘~/.npm-global/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 21, 23, 25, 27, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.1-1 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

When we go to scrollview and press the up key then this happens

### Snack, code example, screenshot, or link to a repository

<img width="1440" alt="Screenshot 2022-07-07 at 8 54 26 PM" src="https://user-images.githubusercontent.com/74759255/177813527-225518d2-c339-41ff-a50a-1a99fd4a49a2.png">
<img width="1440" alt="Screenshot 2022-07-07 at 8 54 43 PM" src="https://user-images.githubusercontent.com/74759255/177813555-7bb43f25-9338-465e-8787-2bfa853134f9.png">
<img width="943" alt="Screenshot 2022-07-07 at 8 55 02 PM" src="https://user-images.githubusercontent.com/74759255/177813572-4016f2db-c3ea-421d-8fce-98b274f89263.png">

Uploading Screen Recording 2022-07-07 at 9.05.31 PM.mov…

**Comment by aniketgupta8960** [comment]
@douglowder  Can you Please help me with this issue

**Comment by douglowder** [comment]
Sorry for the delay in response. My comments:

- It looks like you are trying to use `isTVPreferredFocus()` in a way it really isn't intended to be used. What you are trying to do looks exactly like the problem that `nextFocusLeft`, `nextFocusRight`, `nextFocusUp`, and `nextFocusDown` solve for you. I would strongly recommend that you change your implementation to use those APIs.
- You will want to move to release version 0.68.2-2, as there are important fixes and enhancements there for focus handling on both Apple TV and Android TV. For example, `TVFocusGuideView` now works on both platforms, and the nextFocus APIs now accept view refs instead of only view tags.

**Comment by aniketgupta8960** [comment]
Hi @douglowder  I checked the documentation but nextFocusLeft, nextFocusRight, nextFocusUp, and nextFocusDown is only supported on the android and  for Apple TV we have to use isTVPreferredFocus() 
<img width="1440" alt="Screenshot 2022-07-19 at 2 19 46 PM" src="https://user-images.githubusercontent.com/74759255/179711344-c083fbf8-5a1e-43ff-bf9e-3138fc4cf923.png">
So how we can use it in appleTv .I have also shifted to latest version
.

**Comment by douglowder** [comment]
I actually did build the Apple TV implementation of the nextFocus APIs so I can confirm that they work :) Sorry those documentation comments were not updated, I'll take care of that soon.

You use the nextFocus APIs on Apple TV the same as on Android. See https://github.com/react-native-tvos/react-native-tvos/blob/tvos-v0.68.2/packages/rn-tester/js/examples/DirectionalNextFocus/DirectionalNextFocusExample.js

**Comment by aniketgupta8960** [comment]
Hi @douglowder 
We have implemented the nextFocus api and it is working fine when using without the view but when we use it inside the scrollView then the default navigation of the tvOs starts to happen.
This is a level Array which is rendered:
<img width="1440" alt="Screenshot 2022-07-27 at 11 51 35 PM" src="https://user-images.githubusercontent.com/74759255/181344750-b487b90b-4733-456f-99f1-46229299dd6f.png">

<img width="576" alt="Screenshot 2022-07-27 at 1
<img width="1440" alt="Screenshot 2022-07-27 at 11 51 28 PM" src="https://user-images.githubusercontent.com/74759255/181344736-46c514a0-bd4c-4129-b8d1-b8d04b7d5b3c.png">

<img width="1440" alt="Screenshot 2022-07-27 at 11 49 17 PM" src="https://user-images.githubusercontent.com/74759255/181344613-f5fad92c-9bd3-4551-8ddd-da8fa5d854b3.png">
1 41 09 PM" src="https://user-images.githubusercontent.com/74759255/181344580-c160a7e6-75b2-4145-a5e6-d28b854cc74b.png">
<img width="1440" alt="Screenshot 2022-07-27 at 11 49 40 PM" src="https://use
<img width="1440" alt="Screenshot 2022-07-27 at 11 49 48 PM" src="https://user-images.githubusercontent.com/74759255/181344708-b68d23db-c69d-478f-91d2-3e67ba41d8ed.png">
r-images.githubusercontent.com/74759255/181344676-7ce3b432-5489-4ef9-92be-560267bf0185.png">
