### ISSUE TITLE
Android TV - intermittent crash A/libc: Fatal signal 4 (SIGILL), code 1 (ILL_ILLOPC)

### ISSUE THREAD

**Issue by MathieuHERY** [react-native-tvos/react-native-tvos#322]
### Description

Hello, 

I am experiencing a crash on Android TV which occurs randomly, sometimes at the launch, sometimes later on some screen or when reloading the app. It's difficult to provide steps to reproduce. Occurs on both emulator and real devices. Could you please take a look? 

I'm sorry but i don't have enough ouput from the log to identify what's wrong. 
Not sure if it's related but i'm working on a Mac M1 Pro ship.

Thanks for your help. 

-- ERROR --

A/libc: Fatal signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x7141eb4180 in tid 6519 (mqt_js), pid 6470 (com.inreestv)

-- ALL LOG -- 

07/12 12:13:15: Launching 'app' on Android TV (4K).
Install successfully finished in 364 ms.
$ adb shell am start -n "com.inreestv/com.inreestv.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 6470 on device 'Android_TV_4K_ [emulator-5554]'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
V/studio.deploy: Startup agent attached to VM
V/studio.deploy: No existing instrumentation found. Loading instrumentation from instruments-962d6e1a.jar
W/com.inreestv: DexFile /data/data/com.inreestv/code_cache/.studio/instruments-962d6e1a.jar is in boot class path but is not in a known location
V/studio.deploy: Applying transforms with cached classes
W/com.inreestv: Redefining intrinsic method java.lang.Thread java.lang.Thread.currentThread(). This may cause the unexpected use of the original definition of java.lang.Thread java.lang.Thread.currentThread()in methods that have already been compiled.
W/com.inreestv: Redefining intrinsic method boolean java.lang.Thread.interrupted(). This may cause the unexpected use of the original definition of boolean java.lang.Thread.interrupted()in methods that have already been compiled.
D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10097; state: ENABLED
W/ziparchive: Unable to open '/data/app/~~K8110sK0KxppIIazNKDgRw==/com.inreestv-EwZa2V1qrVhm5adIDUFnsg==/base.dm': No such file or directory
W/ziparchive: Unable to open '/data/app/~~K8110sK0KxppIIazNKDgRw==/com.inreestv-EwZa2V1qrVhm5adIDUFnsg==/base.dm': No such file or directory
V/GraphicsEnvironment: ANGLE Developer option for 'com.inreestv' set to: 'default'
V/GraphicsEnvironment: ANGLE GameManagerService for com.inreestv: false
V/GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.inreestv/lib-main
I/fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.inreestv/lib-main
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.inreestv/lib-main
D/SoLoader: libjscexecutor.so not found on /data/data/com.inreestv/lib-main
D/SoLoader: libjscexecutor.so found on /data/app/~~K8110sK0KxppIIazNKDgRw==/com.inreestv-EwZa2V1qrVhm5adIDUFnsg==/lib/arm64
D/SoLoader: Not resolving dependencies for libjscexecutor.so
D/JavaScriptCore.Version: 250230.2.1
D/SoLoader: libfbjni.so not found on /data/data/com.inreestv/lib-main
D/SoLoader: libfbjni.so found on /data/app/~~K8110sK0KxppIIazNKDgRw==/com.inreestv-EwZa2V1qrVhm5adIDUFnsg==/lib/arm64
D/SoLoader: Not resolving dependencies for libfbjni.so
D/SoLoader: libflipper.so not found on /data/data/com.inreestv/lib-main
D/SoLoader: libflipper.so found on /data/app/~~K8110sK0KxppIIazNKDgRw==/com.inreestv-EwZa2V1qrVhm5adIDUFnsg==/lib/arm64
D/SoLoader: Not resolving dependencies for libflipper.so
D/TrafficStats: tagSocket(80) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats: tagSocket(88) with statsTag=0xffffffff, statsUid=-1
W/unknown:ReconnectingWebSocket: Couldn't connect to "ws://localhost:8081/message?device=sdk_google_atv64_amati_arm64%20-%2012%20-%20API%2032&app=com.inreestv&clientid=BridgeDevSupportManager", will silently retry
W/unknown:InspectorPackagerConnection: Couldn't connect to packager, will silently retry
W/com.inreestv: Accessing hidden field Landroid/view/View;->mKeyedTags:Landroid/util/SparseArray; (unsupported, reflection, allowed)
W/com.inreestv: Accessing hidden field Landroid/view/View;->mListenerInfo:Landroid/view/View$ListenerInfo; (unsupported, reflection, allowed)
W/com.inreestv: Accessing hidden field Landroid/view/View$ListenerInfo;->mOnClickListener:Landroid/view/View$OnClickListener; (unsupported, reflection, allowed)
I/flipper: flipper: FlipperClient::addPlugin Inspector
I/flipper: flipper: FlipperClient::addPlugin React
I/flipper: flipper: FlipperClient::addPlugin Databases
I/flipper: flipper: FlipperClient::addPlugin Preferences
I/flipper: flipper: FlipperClient::addPlugin CrashReporter
I/flipper: flipper: FlipperClient::addPlugin Network
D/libEGL: loaded /vendor/lib64/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib64/egl/libGLESv2_emulation.so
W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
D/TrafficStats: tagSocket(86) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats: tagSocket(90) with statsTag=0xffffffff, statsUid=-1
W/unknown:ReactNative: The packager does not seem to be running as we got an IOException requesting its status: Failed to connect to localhost/127.0.0.1:8081
W/com.inreestv: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
W/com.inreestv: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
D/SoLoader: libreactnativejni.so not found on /data/data/com.inreestv/lib-main
D/SoLoader: libreactnativejni.so found on /data/app/~~K8110sK0KxppIIazNKDgRw==/com.inreestv-EwZa2V1qrVhm5adIDUFnsg==/lib/arm64
D/SoLoader: Not resolving dependencies for libreactnativejni.so
W/unknown:ReactContext: initializeMessageQueueThreads() is called.
W/unknown:ReactNative: Packager connection already open, nooping.
D/HostConnection: createUnique: call
D/HostConnection: HostConnection::get() New Host Connection established 0xb40000726e060310, tid 6511
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
W/OpenGLRenderer: Failed to initialize 101010-2 format, error = EGL_SUCCESS
D/EGL_emulation: eglCreateContext: 0xb40000726e063250: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0xb40000726e063250: ver 3 0 (tinfo 0x7486e22080) (first time)
I/Gralloc4: mapper 4.x is not supported
D/HostConnection: createUnique: call
D/HostConnection: HostConnection::get() New Host Connection established 0xb40000726e063490, tid 6511
D/goldfish-address-space: allocate: Ask for block of size 0x100
D/goldfish-address-space: allocate: ioctl allocate returned offset 0x1e9ff0000 size 0x8000
W/Gralloc4: allocator 4.x is not supported
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
W/Parcel: Expecting binder but got null!
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
W/unknown:ReactNative: Packager connection already open, nooping.
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.unimplementedview.ReactUnimplementedViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.BV.LinearGradient.LinearGradientManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.th3rdwave.safeareacontext.SafeAreaProviderManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.th3rdwave.safeareacontext.SafeAreaViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.th3rdwave.safeareacontext.SafeAreaViewShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenContainerViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenStackViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenStackHeaderConfigViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenStackHeaderSubviewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.SearchBarManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$GroupViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$RenderableShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$PathViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$CircleViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$EllipseViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$LineViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$RectViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$TextViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$TSpanViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$TextPathViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$ImageViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$ClipPathViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$DefsViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$UseViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$SymbolManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$LinearGradientManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$RadialGradientManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$PatternManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$MaskManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$ForeignObjectManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager$MarkerManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.SvgViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.brentvatne.react.ReactVideoViewManager
W/unknown:ReactContext: initializeMessageQueueThreads() is called.
D/SoLoader: libyoga.so not found on /data/data/com.inreestv/lib-main
D/SoLoader: libyoga.so found on /data/app/~~K8110sK0KxppIIazNKDgRw==/com.inreestv-EwZa2V1qrVhm5adIDUFnsg==/lib/arm64
D/SoLoader: Not resolving dependencies for libyoga.so
I/flipper: flipper: FlipperClient::addPlugin Fresco
D/SoLoader: libreactnativeblob.so not found on /data/data/com.inreestv/lib-main
D/SoLoader: libreactnativeblob.so found on /data/app/~~K8110sK0KxppIIazNKDgRw==/com.inreestv-EwZa2V1qrVhm5adIDUFnsg==/lib/arm64
D/SoLoader: Not resolving dependencies for libreactnativeblob.so
I/WebViewFactory: Loading com.google.android.webview version 101.0.4951.15 (code 495151534)
W/com.inreestv: Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (unsupported, reflection, allowed)
W/com.inreestv: Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (unsupported, reflection, allowed)
W/com.inreestv: Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (unsupported, reflection, allowed)
W/com.inreestv: Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (unsupported, reflection, allowed)
W/com.inreestv: Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (unsupported, reflection, allowed)
I/cr_WVCFactoryProvider: Loaded version=101.0.4951.15 minSdkVersion=29 isBundle=false multiprocess=true packageId=2
I/cr_LibraryLoader: Successfully loaded native library
I/cr_CachingUmaRecorder: Flushed 8 samples from 8 histograms.
D/TrafficStats: tagSocket(131) with statsTag=0xffffffff, statsUid=-1
W/ReactNativeJS: ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.
I/ReactNativeJS: Running "InreesTV" with {"rootTag":1}
D/TrafficStats: tagSocket(103) with statsTag=0xffffffff, statsUid=-1
W/ReactNativeJS: Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
        in NetworkStatus (at navigations.js:88)
        in EnsureSingleNavigator (at BaseNavigationContainer.tsx:430)
        in BaseNavigationContainer (at NavigationContainer.tsx:132)
        in ThemeProvider (at NavigationContainer.tsx:131)
        in NavigationContainerInner (at navigations.js:86)
        in AppNavigation (at App.js:14)
        in Provider (at App.js:13)
        in App (at renderApplication.js:50)
        in RCTView (at View.js:32)
        in View (at AppContainer.js:92)
        in RCTView (at View.js:32)
        in View (at AppContainer.js:119)
        in AppContainer (at renderApplication.js:43)
        in InreesTV(RootComponent) (at renderApplication.js:60)
D/TrafficStats: tagSocket(131) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats: tagSocket(138) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats: tagSocket(139) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats: tagSocket(138) with statsTag=0xffffffff, statsUid=-1
A/libc: Fatal signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x7141eb4180 in tid 6519 (mqt_js), pid 6470 (com.inreestv)

### Version

0.68.2-1

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 727.25 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.9.0 - /opt/homebrew/bin/npm
    Watchman: 2022.06.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.2-1 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Hello, 

I am experiencing a crash on Android TV which occurs randomly, sometimes at the launch, sometimes later on some screen or when reloading the app. It's difficult to provide steps to reproduce. Occurs on both emulator and real devices. Could you please take a look? 

I'm sorry but i don't have enough ouput from the log to identify what's wrong. 
Not sure if it's related but i'm working on a Mac M1 Pro ship.

Thanks for your help.

**Comment by douglowder** [comment]
It looks like there is a bug in your application's Javascript somewhere....

```
Warning: Functions are not valid as a React child. This may happen if you return a Component instead of from render. Or maybe you meant to call this function rather than return it.
```

If you have a working example that reproduces the crash (even intermittently), please provide that and I'll take a look.
