### ISSUE TITLE
Apple Remote Swipe left or right causing button to move left 

### ISSUE THREAD

**Issue by aniketgupta8960** [react-native-tvos/react-native-tvos#325]
### Description

We are using Pressable component as Button but when we use apple remote and try to swipe left or right it causes the button to move from its position and doesn't stay at its original position which also makes navigation left and right quite difficult. We want to fix the button position and do not want the remote swipe left and right causing the button to move from its position.

https://user-images.githubusercontent.com/74759255/182549022-cc1c3952-a4a4-4a25-9af1-8a7c42bea770.mov

### Version

0.68.2-2

### Output of `npx react-native info`

OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 48.06 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/‘~/.npm-global/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 21, 23, 25, 27, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.2-2 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1- Create a button with image background 
2- Use apple remote and swipe left and right ,it will cause the image to move 

### Snack, code example, screenshot, or link to a repository

 return (
    <Pressable onPress={onPress} 
    ref={ref}
    nextFocusUp={props.nextFocusUp}
    nextFocusDown={props.nextFocusDown}
    nextFocusLeft={props.nextFocusLeft}
    nextFocusRight={props.nextFocusRight}
    style={styles.container} 
    hasTVPreferredFocus={hasTVPreferredFocus?hasTVPreferredFocus:false}
    >
      {({ pressed, focused }) => (
        <>
          {pressed || focused ? (
            <ImageBackground
              source={imageOnPress}
              style={[styles.imageStyle, imageStyle]}>
              {buttonText1 && (
                <View style={textViewStyle}>
                  <Text style={[styles.textStylePressed, textStyle]}>
                    {buttonText1}
                  </Text>
                  {buttonText2 &&
                    <Text style={[styles.textStylePressed, text2Style]}>
                      {buttonText2}
                    </Text>
                  }
                </View>
              )}
            </ImageBackground>
          ) : (
            <ImageBackground
              source={image}
                style={[styles.imageStyle, imageStyle, normalImageStyle]}>
              {buttonText1 && (
                <View style={textViewStyle}>
                  <Text style={[styles.textStyle, textStyle]}>
                    {buttonText1}
                  </Text>
                  {buttonText2 &&
                    <Text style={[styles.textStyle, text2Style]}>
                      {buttonText2}
                    </Text>
                  }
                </View>
              )}
            </ImageBackground>
          )}
        </>
      )}
    </Pressable>
  );

**Comment by nriccar** [comment]
Checkout the tvParallaxProperties of the `TouchableOpacity` - not sure if its there for the other touchables. 

You can disable parallax effects, or customise them.

**Comment by douglowder** [comment]
@nriccar is correct. Those properties should be available for the other touchables as well.

**Comment by aniketgupta8960** [comment]
Thank you for your help
