### ISSUE TITLE
Native UITableView/UICollectionView - cells can be focused but not selected

### ISSUE THREAD

**Issue by TiagoLira** [react-native-tvos/react-native-tvos#326]
### Description

I'm wrapping a tvOS native view of our framework in a native module, following the ReactNative guides.

All regular buttons work well, but I found an issue in all the UITableView and UICollectionView elements.
Tapping a cell does not work with the simulator remote control. The native `didSelectCellAt` is never called.

Controlling the simulator with the hardware keyboard, it works only if I select the cell _immediately_ after focusing it. If I take half a second and then select it, it doesn't work.

The view works well in native projects, so I suspect that something in react-native is interfering with the touch events. Does anyone have an idea what could cause it? Any hint is very appreciated.

### Version

0.68.2-2

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 292.56 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2021.09.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.2-2 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1 - Create a native view with a UITableView or UICollectionView inside it
2 - Add an action on cell selection
3 - Wrap the view in a native module inside a react-native-tvos project
4 - Run in the simulator, see that the cell selection cannot be triggered

**Comment by douglowder** [comment]
On `RCTTVView`, if the view is focusable and selectable, a `UITapGestureRecognizer` is added with press type `UIPressTypeSelect`. You might need to do something like that for your cells.

Without seeing your code, it's hard for me to say more about what the issue might be. It is true that RN is setting up gesture recognizers on the root view for many of the remote control events.

**Comment by TiagoLira** [comment]
@douglowder Thank you for your suggestion, I appreciate it. Adding a tap gesture recognizer to each cell works well as a workaround.

For others who may have the same issue, here is my code:
(I added the reactCompatMode flag on my library configuration, so that it works both on RN and native projects)

```
public func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    // ... create and configure cell
        
    if MyLibrary.reactCompatMode {
        cell.gestureRecognizers?.removeAll()
        let tap = UITapGestureRecognizer(target: self, action: #selector(cellTap(recognizer:)))
        tap.allowedPressTypes = [NSNumber(value: UIPress.PressType.select.rawValue)]
        cell.addGestureRecognizer(tap)
        cell.tag = indexPath.row
    }
    return cell
}

public func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    if !MyLibrary.reactCompatMode {
        // ... selection action (for native projects)
    }
}

@objc func cellTap(recognizer: UITapGestureRecognizer?) {
    guard let tag = recognizer?.view?.tag else { return }   //cell index
    // ... selection action (for native projects)
}
```
