### ISSUE TITLE
Unable to programmatically focus on TextInput using ref and trigger keyboard

### ISSUE THREAD

**Issue by pkaneriendeavor** [react-native-tvos/react-native-tvos#328]
### Description

Hi, firstly thanks for all the work on the repo, it's been great to use. 

I've run into an issue trying to make the focus of the TextInput automatically proceed to the next one, if the user inserts a valid entry. 

This is almost exactly like the following: https://stackoverflow.com/questions/49028339/change-the-focus-automatically-to-the-next-textinput-in-react-native 

The specific issue I'm seeing is that while the TextInput appears to receive focus and fire the onFocus callback, the keyboard doesn't appear and the TextInput can not be selected either using the arrow keys. I'm doing this by setting a ref on the TextInput I want to set focus on, and firing a ref.current.focus when the previous TextInput has text typed into it.

In the repo I've created, I've also implemented https://reactnative.dev/docs/direct-manipulation#setnativeprops-to-edit-textinput-value to show that the focus can be applied and the keyboard opened using an onPress event. 

Any help would be much appreciated!

### Version

react-native-tvos@0.68.2-5

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 25.47 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
    Watchman: 2022.05.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.3, 30.0.2, 30.0.3, 32.0.0, 32.1.0
      System Images: android-32 | Google APIs ARM 64 v8a, android-Tiramisu | Google TV ARM 64 v8a
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.2-5 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

https://user-images.githubusercontent.com/106078405/185592160-52a8fab7-f323-4c9b-af4b-5d6fa7ee629c.mov

### Snack, code example, screenshot, or link to a repository

https://github.com/pkaneriendeavor/TestTVApp

**Comment by douglowder** [comment]
There are definitely some issues with `TextInput` in RN, and they are also present in the core repo.

I recommend wrapping the `TextInput` in a `Touchable` -- this also provides a workaround for styling issues (`TextInput` often ignores its styling).

Example:

```js
const WrappedTextInput = (props) => {
  const textInputRef = React.useRef();
  return (
    <TouchableOpacity
      activeOpacity={0.8}
      onPress={() => textInputRef?.current?.focus()}>
      <TextInput
        {...props}
        autoComplete="off"
        ref={textInputRef}
      />
    </TouchableOpacity>
  );
};
```

If you do something like the above in your repo, does the keyboard come up when the input is focused?

**Comment by pkaneriendeavor** [comment]
Hi Doug, thanks for your reply. So while it does work and the keyboard comes up when using an onPress method, what doesn't work is changing the focus programatically when some text has been entered in a previous TextInput. So taking your code block above, something like the below. Is there a different way to achieve the same thing below, without using the call to `.focus()`? 

```javascript
export function App(props) {

  const inputRef1 = React.useRef();
  const inputRef2 = React.useRef();

  return (
    <View>
      <TouchableOpacity
        activeOpacity={0.8}
        onPress={() => inputRef1?.current?.focus()}>
        <TextInput
          // not working
          onChangeText={text => text && inputRef2?.current?.focus()}
          blurOnSubmit={false}
          autoFocus={false}
          autoComplete="off"
          ref={inputRef1}
        />
      </TouchableOpacity>
      <TouchableOpacity
        activeOpacity={0.8}
        onPress={() => inputRef2?.current?.focus()}>
        <TextInput
          blurOnSubmit={false}
          autoFocus={false}
          autoComplete="off"
          ref={inputRef2}
        />
      </TouchableOpacity>
    </View>
  );

}  

```

**Comment by nriccar** [comment]
You can use the onFocus method for the TouchableOpacity, that way, the TextInput will be automatically focused and the keyboard will be opened

**Comment by pkaneriendeavor** [comment]
Hi @nriccar unfortunately that approach still doesn't seem to work in changing focus and opening the keyboard on the second TextInput from the first TextInput. It also means when you have manually focused onto the second TextInput using the keys, it is firing the `onFocus` callback and forcing the keyboard to open which causes the focus to be stuck on that second TextInput.

**Comment by nriccar** [comment]
You could store in a state if it was first opened, or something similar.
I have this implementation on a project, let me check it

**Comment by douglowder** [comment]
I will set this up and try a few things. The video shows the problem on Apple TV -- is Android TV also having this issue?

**Comment by nriccar** [comment]
I solved it for Apple TV this way:
```javascript
const [inputs, setInputs] = useState({
  text: ''
})

const [willFocus, setWillFocus] = useState(false)

const textinput1 = useRef()
const textinput2 = useRef()

<TouchableOpacity onFocus={() => textinput1?.current?.focus()}>
  <TextInput 
    ref={textinput1}
    onChangeText={e => setInputs({
      text: e
    })}
    onBlur={() => {
      if (inputs.text) {
        setWillFocus(true)
      }
    }}
  />
</TouchableOpacity>


<TouchableOpacity hasTVPreferredFocus={willFocus} onFocus={() => textinput2?.current?.focus()}>
  <TextInput 
    ref={textinput2}
    onBlur={() => {
      setWillFocus(true)
    }}
  />
</TouchableOpacity>
```

**Comment by douglowder** [comment]
What @nriccar is doing looks like the right way to solve the issue on Apple TV.

The problem I'm seeing is that if you immediately try to call `focus()` on the second input, you have an issue where the view being focused is actually not in the native view hierarchy.  I'm seeing Xcode console messages like this:

```sh
2022-08-23 14:03:41.745579-0700 TestTVApp-tvOS[23041:2757946] [UIFocus] Found invalid pending focus update request for environment <_UIKBCompatInputView: 0x145624f40> in focus system <UIFocusSystem: 0x6000014382c0>.
2022-08-23 14:03:42.251684-0700 TestTVApp-tvOS[23041:2757946] [Presentation] Attempt to present <UISystemInputViewController: 0x14606a600> on <UISystemInputViewController: 0x155831800> (from <UISystemInputViewController: 0x155831800>) whose view is not in the window hierarchy.
```

**Comment by nriccar** [comment]
@douglowder do you suggest setting a timeout for a workaround?

**Comment by douglowder** [comment]
@nriccar I tried that and it did not work -- however, even if I made the timeout work, I think your solution is actually better and less hacky.

**Comment by pkaneriendeavor** [comment]
Hello, thanks for the suggestions! 

@nriccar Does the approach above not require some kind of keyboard confirmation entry by the user like 'next' or 'done'? I tried to play around with that approach by doing something like the following for what I am trying to achieve:

```javascript
    <View>
          <TouchableOpacity onPress={() => textinput1?.current?.focus()}>
          <TextInput
            style={styles.input}
            ref={textinput1}
            onBlur={() => {
              setWillFocus(true);
            }}
            onChangeText={e => {
              setInputs({
                text: e,
              });
              textinput1.current.blur();
            }}
          />
        </TouchableOpacity>
        <TouchableOpacity
          hasTVPreferredFocus={willFocus}
          onPress={() => textinput2?.current?.focus()}
          onFocus={() => {
            willFocus && textinput2?.current?.focus();
          }}>
          <TextInput
            style={styles.input}
            onFocus={() => console.log('onFocus')}
            ref={textinput2}
            onBlur={() => setWillFocus(false)}
            onChangeText={() => setWillFocus(false)}
          />
        </TouchableOpacity>
      </View>

```

but that didn't seem to trigger an 'onFocus' event on the second TextInput even though hasTVPreferredFocus={willFocus} is true. How were you able to achieve this?

Doug based on your feedback there, just to sort of test it out, I was able to get it to sort of work using a timeout by doing something like this:

```javascript

<TouchableOpacity
          activeOpacity={0.8}
          onPress={text => text && inputRef1?.current?.focus()}>
          <TextInput
            style={styles.input}
            onChange={e => {
              if (e.nativeEvent.text) {
                e.persist();
                inputRef1.current.blur();
                setTimeout(() => setFocusOn(true), 500);
              }
            }}
            blurOnSubmit={false}
            autoFocus={false}
            autoComplete="off"
            ref={inputRef1}
          />
        </TouchableOpacity>
        {focusOn && (
          <TextInput
            style={styles.input}
            blurOnSubmit={false}
            autoFocus={true}
            onFocus={() => console.log('is focused on')}
            onChangeText={text => {
              console.log({text});
              setFocusOn(false);
            }}
            onEndEditing={() => setFocusOn(false)}
            autoComplete="off"
            ref={ref => (inputRef2.current = ref)}
          />
        )}
        {!focusOn && (
          <TouchableOpacity
            activeOpacity={0.8}
            onPress={() => inputRef3.current.focus()}>
            <TextInput
              style={styles.input}
              blurOnSubmit={false}
              autoFocus={false}
              onChangeText={() => {}}
              autoComplete="off"
              ref={ref => (inputRef3.current = ref)}
            />
          </TouchableOpacity>
        )}

```

Like you said quite hacky but does seem like there is some kind of frame transition going on (perhaps with the keyboard closing) in the native code that isn't being waited for. Not too familiar with the native side of it but will try to see if I can change the way the focus is applied.
