### ISSUE TITLE
Custom font link issue

### ISSUE THREAD

**Issue by avishka-codimite** [react-native-tvos/react-native-tvos#329]
### Description

I want to add custom fonts for my project. So, like adding fonts to ios, it was added to this too. but nothing changes the font family. 

### Version

0.68.2-5

### Output of `npx react-native info`

```
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 102.30 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.2-5 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. add fonts font in an asset folder `PROJECT-DIRECTORY/assets/fonts`
2. Add the configuration to the project (_**react-native.config.js**_)
3. Link the assets to the project `npx react-native link`

### Snack, code example, screenshot, or link to a repository

**react-native.config.js**

```
module.exports = {
  project: {
    ios: {},
    android: {},
  },
  assets: ['./assets/fonts'], 
};
```
<img width="345" alt="Screenshot 2022-08-23 at 11 58 11 AM" src="https://user-images.githubusercontent.com/111336101/186086368-abd91aca-8cf7-4a73-9773-b8f1eb80bcca.png">

Info.plist

<img width="968" alt="Screenshot 2022-08-23 at 11 54 36 AM" src="https://user-images.githubusercontent.com/111336101/186085763-b37f6ec0-f4d1-4992-9d9c-b8324a4a431d.png">

**Comment by douglowder** [comment]
That `Info.plist` appears to be the one for iOS. Check the `ios/PROJECT_NAME-tvOS/Info.plist` and make sure your fonts are listed there as well.

**Comment by avishka-codimite** [comment]
I checked that. fonts are not listed there. 

<img width="759" alt="Screenshot 2022-08-24 at 10 02 49 AM" src="https://user-images.githubusercontent.com/111336101/186329544-36c98cb2-41e4-4dc6-9a76-bde901d52846.png">

**Comment by douglowder** [comment]
If you add them there, and also make sure they are included in the ApollotvOS-tvOS target, then they should show up on the Apple TV.

**Comment by avishka-codimite** [comment]
Yeah, I was able to fix the issue according to the instruction by @natestone given here.  [https://github.com/facebook/react-native/issues/18025](url)
