### ISSUE TITLE
Apple TV: menu key gesture recognizer not working on Modal or on native stack navigator

### ISSUE THREAD

**Issue by leonchabbey** [react-native-tvos/react-native-tvos#341]
### Description

This issue appeared while using the `createNativeStackNavigator` from react-navigation and react-native-screens.

`createNativeStackNavigator` creates a new `UINavigationController` and `UIViewController` which seems to handle by default the "menu" button to go back to the previous screen on the navigation stack.

The current implementation of `RCTTVRemoteHandler` only applies to the `RCTRootView`. Since the root view is the first view in the view hierarchy, it is gonna be the last one to receive a `menuPressed:` event after every potential propagation. So the `UINavigationController` created by react-native-screens will always override a `menuPressed:` event when the app is inside a stack screen.

We fixed it by initing a `RCTTVRemoteHandler` for every `RCTTVView`: https://github.com/SRGSSR/react-native-tvos/pull/2. However it seems overkill to do it for every single view and definitely not the cleanest way.

We didn't find a cleaner/easier way to do it since the issue is kinda shared between the remote event handling implementation here and how react-native-screens works.

### Version

0.68.2-6

### Output of `npx react-native info`

System:
- OS: macOS 12.3.1
- CPU: (8) arm64 Apple M1
- Memory: 125.94 MB / 16.00 GB
- Shell: 5.8 - /bin/zsh

Binaries:
- Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
- Yarn: 1.22.17 - /opt/homebrew/bin/yarn

CocoaPods: 1.11.3 - /opt/homebrew/bin/pod

iOS SDK:
- Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5

IDEs:
- Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild

### Steps to reproduce

1) add `react-navigation` and `react-native-screens` to your project
2) create a stack navigator using `createNativeStackNavigator`
3) try to get the `menu` event using `BackHandler` inside a stack screen

**Comment by SebastienChauvin** [comment]
For completeness we also tried to add a remote handler only to `RNSScreenView` and that works as well. But this creates an undesirable dependency between `react-native-screens` and `react-native-tvos`

**Comment by SebastienChauvin** [comment]
Yes that would work. I was trying to find a solution that would not connect `react-native-screens` to `react-native-tvos` at all.
It's not fully clear to me yet, but I believe, the "good" solution would be to have react-native-screens derive `RNSScreenView` from `RCTRootView` and remove some of the responsibilities from the `RCTRootView`... But that's a big refactor implicating all three libraries.

**Comment by leonchabbey** [comment]
After more testing and debugging, even with the "fix" I found and patching `react-native-screens` like you recommended @douglowder, the gesture recognizing lifecycle/queue seems just very unstable.

As an example, I did a small project ([ModalExample.zip](https://github.com/react-native-tvos/react-native-tvos/files/9527512/ModalExample.zip)) with a Modal which you can open by pressing on a button. It replicates quite well our issue with `react-native-screens` since the modal system also tries to manage the `UIPressTypeMenu` event to invoke the `onRequestClose` JS prop.
As you can see in this project, the `onRequestClose` is never fired when pressing on the remote's menu button even though the modal closes. The gesture/event seems to be caught by some native controller before it gets to `_menuButtonGestureRecognizer` in `RCTModalHostView`.

The same behaviour happens with `react-native-screens`, sometimes the gesture recognizer gets the event before the `UINavigationController` and sometimes it doesn't. I couldn't find why.

So no solution really works at this point... Any other ideas?

**Comment by douglowder** [comment]
Wow the modal example is interesting indeed. It seems that tvOS has changed the way they do modal presentations -- the menu key goes to the modal view controller's view, bypassing any recognizers set on `RCTModalHostView`.

I'll do some work to fix that, and then take a look at the `react-native-screens` issue.

**Comment by leonchabbey** [comment]
Thanks for helping us with this issue!

My knowledge of native iOS/tvOS has its limitations and unfortunately I can't afford spending too much time on trying to fix this right now.

It think it might be the same issue happening on the Modal and Navigation. The view controller somehow gets the event before its children even though they have recognizers set.

Maybe a hint about the issue: if i recall correctly, setting a menu button recognizer from `RCTModalHostViewController` in `viewDidLayoutSubviews` to `self.view` was getting the menu pressed every single time.
`self.view` being the "direct" view of the controller might be the reason it works.

**Comment by douglowder** [comment]
@leonchabbey please see #348 .

It definitely works for the RNTester example and the menu key behavior is now correct for the example you sent. There is still something else in your example that is taking over the menu key and preventing the RCTTVRemoteHandler in the modal from working. However, this is definitely a big improvement in modal behavior on tvOS.

**Comment by leonchabbey** [comment]
Thanks for the PR.

I quickly tried the last commit on the Modal example and now it really "overrides" the default menuPressed for the native modal 👍 

So in the end setting the gesture handlers on the view of the modal's view container as suggested in my "hint" above was the only way to stop the propagation of the event?

I'm gonna try to implement something similar to react-native-screens.

**Comment by leonchabbey** [comment]
I found another use case that has an issue linked to the hasTVPreferredFocus fix you did: https://github.com/react-native-tvos/react-native-tvos/commit/11a974fb0258e67e268655eb1cd4763330ed8c19#diff-f0893c7fdea16a37417f46bfb45692a307acc216813d08438af8857917511df4R142-R155

You should be able to reproduce it by adding a button inside your Modal with `hasTVPreferredFocus={true}`. Since the modals are created in another subtree, which is not under  `RCTRootView`, it will then cause a freeze of _maybe_ 480ms since it won't find the `rootview`.
It happens in our app which has a pretty complex View hierarchy inside the modal.

**Comment by douglowder** [comment]
Thanks @leonchabbey for reporting the preferred focus issue.  I'll try that out locally and see if there is an easy fix.

Good news is, when we finally move to the new Fabric architecture, that problem will no longer exist because the root view is always non-null :)

**Comment by merrywhether** [comment]
> Good news is, when we finally move to the new Fabric architecture, that problem will no longer exist because the root view is always non-null :)

@douglowder What do you mean by this comment about finally moving to Fabric? The rn-tvos readme indicates support for Fabric; is that not recommended yet?

**Comment by douglowder** [comment]
@merrywhether Fabric is indeed supported. However, there are some limitations, and I believe that not all third party libraries have added support for Fabric yet. I think it is certainly worth trying out to see if it works well for your particular app.

**Comment by leonchabbey** [comment]
FYI, this patch fixes the back/menu button handling issue inside a Screen (of @react-navigation / react-native-screens):
```
diff --git a/node_modules/react-native-screens/ios/RNSScreen.h b/node_modules/react-native-screens/ios/RNSScreen.h
index a2195b5..5909034 100644
--- a/node_modules/react-native-screens/ios/RNSScreen.h
+++ b/node_modules/react-native-screens/ios/RNSScreen.h
@@ -10,6 +10,11 @@
 #import <React/RCTView.h>
 #endif
 
+#if __has_include(<React/RCTTVRemoteHandler.h>)
+#include <React/RCTTVRemoteHandler.h>
+#endif
+
+
 NS_ASSUME_NONNULL_BEGIN
 
 @interface RCTConvert (RNSScreen)
@@ -68,7 +73,9 @@ NS_ASSUME_NONNULL_BEGIN
 @property (nonatomic) int activityState;
 @property (weak, nonatomic) UIView<RNSScreenContainerDelegate> *reactSuperview;
 
-#if !TARGET_OS_TV
+#if TARGET_OS_TV
+@property (nonatomic, strong) RCTTVRemoteHandler *tvRemoteHandler;
+#else
 @property (nonatomic) RNSStatusBarStyle statusBarStyle;
 @property (nonatomic) UIStatusBarAnimation statusBarAnimation;
 @property (nonatomic) UIInterfaceOrientationMask screenOrientation;
diff --git a/node_modules/react-native-screens/ios/RNSScreen.mm b/node_modules/react-native-screens/ios/RNSScreen.mm
index 5431330..13875f6 100644
--- a/node_modules/react-native-screens/ios/RNSScreen.mm
+++ b/node_modules/react-native-screens/ios/RNSScreen.mm
@@ -82,6 +82,8 @@ - (void)initCommonProps
   _hasStatusBarHiddenSet = NO;
   _hasOrientationSet = NO;
   _hasHomeIndicatorHiddenSet = NO;
+  
+  _tvRemoteHandler = [[RCTTVRemoteHandler alloc] initWithView:self];
 }
 
 - (UIViewController *)reactViewController

```

**Comment by leonchabbey** [comment]
> Thanks @leonchabbey for reporting the preferred focus issue. I'll try that out locally and see if there is an easy fix.
> 
> Good news is, when we finally move to the new Fabric architecture, that problem will no longer exist because the root view is always non-null :)
> 
> This is related to #344 so I'll track it there.

Hi @douglowder!

Did you manage to test it / reproduce the issue since?

This issue is quite a blocker for us right now and we can't migrate to Fabric because of reanimated...
We have a button that needs to get the focus on mount but setting `hasTVPreferredFocus={true}` causes the freeze we talked about before (`counter` [here](https://github.com/react-native-tvos/react-native-tvos/blob/efaa116881b47c75bc77a7538579ad8ab09e6e33/React/Views/RCTTVView.m#L153) is equal to 0 and rootview is `nil` so the `hasTVPreferredFocus` gets ignored in the end).

When I have the time (probably tomorrow) I will try to share a demo project with the same setup as our project.
FYI,  this issue occurs in a react-navigation Drawer Screen.

And do you mind explaining why the rootview can be null? Isn't it the first view created right at the begninning? 🤔

**Comment by douglowder** [comment]
I will wait to see your demo project, but I do know that when using React Navigation with native stack navigator, for example, there can be views that are not descended from the root view. Hopefully once I see the demo I can figure out what is happening.

**Comment by leonchabbey** [comment]
Here is the demo project: [NullRootViewDemo.zip](https://github.com/react-native-tvos/react-native-tvos/files/9824522/NullRootViewDemo.zip)

It seems like the issue only occurs with `hasTVPreferredFocus` set to `true` on mount on views in nested navigators.
I added comments in the demo code, but basically if you render only the `Drawer.Navigator` you won't have the issue. However, if you render a `Stack.Navigator` which then renders a `Drawer.Navigator` you can see a slight freeze which are the 480ms of trying to find the rootview.

I will try to debug more tomorrow but I wanted to give you the demo ASAP since it seems like we are on different timezones 😃

**Comment by douglowder** [comment]
It looks like the issue can be avoided by using `@react-navigation/stack` instead of `@react-navigation/native-stack`.

However, to really fix the issue, I think you will need to add navigation focus listeners and only set `hasTVPreferredFocus` when the screen has navigation focus. I'll spend some time trying to implement that.

**Comment by leonchabbey** [comment]
Yep I already tried their `useIsFocused` hook but it usually returns `true` already when the route mounts so it doesn't fix the issue.

Something that works but is not ideal since we will usually see a change in focus, is to set a `mounted` state variable so we will wait at least one react render before setting `hasTVPreferredFocus` to true.

```typescript
// useMounted hook
export const useMounted = () => {
  const [mounted, setMounted] = useState(false);
  useDidMount(() => {
    setMounted(true);
  });
  return mounted;
};

```

**Comment by douglowder** [comment]
I attempted something completely different -- instead of searching for the root view when `hasTVPreferredFocus` is set, just fire a notification and let the root view handle it.

The problem is, at the time the notification is fired, the root view does not yet exist -- I verified that in this weird case, RNSScreen is creating and attaching views first before creating the root view.

Hopefully when we migrate to Fabric, this will not happen :)
