### ISSUE TITLE
react-native-tvos/rn-diff-purge-tv is out of sync, last available version is 0.68.2-2

### ISSUE THREAD

**Issue by wouterds** [react-native-tvos/react-native-tvos#342]
### New Version

0.68.2-6

### Old Version

0.68.2-2

### Issue and Reproduction Steps

The react-native-tvos/rn-diff-purge-tv repository seems out of sync, not possible to upgrade to latest version (0.68.2-6).

```
$ npx @react-native-community/cli upgrade 0.68.2-6   
info Fetching diff between v0.68.1-1 and v0.68.2-6...
error Fetch request failed with status 404: 404: Not Found.
error Failed to fetch diff for react-native@0.68.2-6. Maybe it's not released yet?
info For available releases to diff see: https://github.com/react-native-community/rn-diff-purge#diff-table-full-table-here
```

**Comment by douglowder** [comment]
Issue is now fixed, sorry for the delay.

**Comment by euroclydon37** [comment]
Looks like it's out of sync again. I'm looking to upgrade to the latest to get [this patch](https://github.com/react-native-tvos/react-native-tvos/pull/601).

(Wish I knew how to update it for you. Thank you for all the work you put into this.)

**Comment by ashnfb** [comment]
@euroclydon37 , I'm using this on 0.69.6-2

May work for you too?
[tvos_focus.patch](https://github.com/react-native-tvos/react-native-tvos/files/13711183/tvos_focus.patch)

**Comment by douglowder** [comment]
@euroclydon37 my apologies, I have now updated rn-diff-purge-tv with all the versions up to and including 0.73.1-0 which I just published.

**Comment by euroclydon37** [comment]
Thanks!
