### ISSUE TITLE
On Fire TV, onLongPress is not working

### ISSUE THREAD

**Issue by maximilize** [react-native-tvos/react-native-tvos#349]
### Description

On Fire TV, when long pressing the OK button, it only calls the `onPress` callback.
Some android TV devices, like emulators as well, fire a lot of `onPress` events when long pressing the button. With this, we created a workaround to emulate longPress on such devices. However, on Fire TV, this does not work.

I captures the events which we fired by `useTVEventHandler` and found that FireTV sends `eventType = "select"` for short clicks, and `eventType = "longSelect"`. So it *should* be quite easy to fix this behaivor. Here the two events for `onPress` and `onLongPress`:

```
{"dispatchConfig": {}, "eventKeyAction": 1, "eventType": "select", "tag": 509, "target": 509}
{"dispatchConfig": {}, "eventKeyAction": 1, "eventType": "longSelect", "tag": 509, "target": 509}
```

### Version

0.68.1-1

### Output of `npx react-native info`

```
System:
    OS: Linux 5.19 Pop!_OS 22.04 LTS
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-1280P
    Memory: 12.32 GB / 31.07 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.13.1 - ~/.local/node-v16.13.1-linux-x64/bin/node
    Yarn: 1.22.17 - ~/.local/node-v16.13.1-linux-x64/bin/yarn
    npm: 8.1.2 - ~/.local/node-v16.13.1-linux-x64/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_342 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-tvos:  0.68.1-1 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Create a button with `TouchableNativeFeedback`
2. Add the `onPress` and `onLongPress` props
3. Run the app on Fire TV and click the button

**Comment by douglowder** [comment]
@maximilize can you test the change in #352 and make sure that fixes the issue on your Fire TV?

**Comment by mansilaad** [comment]
+1 same issue
