### ISSUE TITLE
TouchableOpacity causes SVG elements to disappear

### ISSUE THREAD

**Issue by MPIIIMan** [react-native-tvos/react-native-tvos#350]
### Description

I posted this on S/O but I'm beginning to think this is a bug.

I am using react-native-tvos to create an app. I am trying to display SVG elements that respond to the remote. I have tried using `TouchableOpacity` as well as `Pressable` on the elements. Whenever I wrap the elements with those they no longer appear. I've looked through dozens of S/O posts and have tried various things. Such as zIndex, flex on container. I also tried the react-native-gesture-handler, but that doesn't seem to work for tvos.

I've broken the code down to something very simple. Just a circle in the middle of the screen.

### Version

0.68.2-6

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 57.14 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 26, 27, 28
      Build Tools: 28.0.3
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.2-6 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

react-native run-ios  --simulator "Apple TV 4K (2nd generation)" --scheme "TestApp-tvOS"

### Snack, code example, screenshot, or link to a repository

```import Svg, {Circle} from 'react-native-svg';
import * as React from 'react';
import {TouchableOpacity, StyleSheet, View} from 'react-native';

const App = () => {
    return (
      <View >
          <Svg x="0px" y="0px" viewBox="0 0 1920 1080" style="enable-background:new 0 0 1920 1080;">
            <TouchableOpacity style={{
                opacity: 1,
                fill: "#FF0000",
                stroke: "5",
                zIndex: 100,
              }} onPress={() => alert('PRESSED')}>
              <Circle style={{zIndex:200,}} cx="960" cy="540" r="100" opacity="1" fill="#FF0000" onPress={() => alert('PRESSED')}/>
            </TouchableOpacity>
          </Svg>
      </View>
    );
};

export default App;

**Comment by douglowder** [comment]
I'll take a look

**Comment by douglowder** [comment]
Ah, your markup is incorrect. The SVG should be wrapped inside the TouchableOpacity, e.g.

```jsx
import * as React from 'react';
import {TouchableOpacity, View} from 'react-native';
import {Svg, Circle} from 'react-native-svg';

const App = () => {
  return (
    <View>
      <TouchableOpacity onPress={() => alert('PRESSED')}>
        <Svg
          x="0px"
          y="0px"
          viewBox="0 0 1920 1080"
          fill="transparent"
          style="enable-background:new 0 0 1920 1080;">
          <Circle cx="960" cy="540" r="100" opacity="1" fill="#FF0000" />
        </Svg>
      </TouchableOpacity>
    </View>
  );
};

export default App;
```

**Comment by MPIIIMan** [comment]
Thanks for the response. I understand I can put it around the entire SVG.
I had hoped it could be done on individual elements inside the SVG.
Is this a limitation with react-native-tvos or react-native-svg?

**Comment by douglowder** [comment]
I would not have thought it would work at all, even on phones. If the problem is specifically on Apple TV, it probably means that the SVG wrapper is set to isUserInteractionEnabled=false in the native implementation, which would make it not visible to the TV focus engine.

**Comment by MPIIIMan** [comment]
That does make sense. I had hoped that things like onPress, Pressable, or TouchableOpacity would translate to remote control inputs on Apple TV

**Comment by douglowder** [comment]
The remote control's select button does invoke the onPress method in TouchableOpacity and Pressable, provided that they are currently focused by the TV focus engine.
