### ISSUE TITLE
focus() doesn't work on buttons

### ISSUE THREAD

**Issue by stepas-dev** [react-native-tvos/react-native-tvos#353]
### Description

I need to be able to focus button using focus method on AndroidTV, but nothing happens, any solution ?

### Version

npm:react-native-tvos@0.68.2-6

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 94.81 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.2-6 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

step 1 - create button
step 2 - assign ref
step 3 - use focus

### Snack, code example, screenshot, or link to a repository

``
```
const buttonRef = useRef()

const someFunction = () => {
  buttonRef.current?.focus();  // <--- never works
}

<Pressable ref={buttonRef}><Text>Button</Text></Pressable>

```
``

**Comment by douglowder** [comment]
I don't believe that `focus()` is a valid method for buttons (`Touchable` or `Pressable`). Generally they are focused in response to user interactions and the `onFocus()` and `onBlur()` methods are called. `TextInput` does have the `focus()` method.

**Comment by stepas-dev** [comment]
i need to setup my own manual focus manager in response to user interactions, default focus is unreliable and buggy

**Comment by douglowder** [comment]
Thanks for the clarification! You have mentioned two different issues...

- Managing focus yourself: apart from hasTVPreferredFocus, we do provide the nextFocusLeft, nextFocusRight, etc., that allows you to direct focus when the user navigates with the D-pad.

- Preserving focus when back navigating: this is something I'm actively working on. The solution requires a state or context to track the screen selected by the user so the Home Screen knows which button should have focus after navigating back.

**Comment by AnonymusRaccoon** [comment]
@douglowder I have two different cases where I would like to use the focus() method and I don't know if they can be done without this method:
 - The first one is for a video player's control. I want to automatically focus back the play button every time the controls are hidden.
 - The second one is for a side menu, when this menu closes, I want to send the focus back to the open button. Now, my focus is simply lost (when the menu hides, no elements seem to have focus and the remote doesn't do anything anymore). For context, my menu is shows with a `{isOpen && <Menu />}`
