### ISSUE TITLE
AndroidTV: Long press not firing event until after released

### ISSUE THREAD

**Issue by josefnorlin** [react-native-tvos/react-native-tvos#358]
### Description

This project is awesome!

Coming from react-native with mobile devices I've had such a nice time moving over to TV development and I'm so thankful for the work @douglowder and the rest of you guys have been doing.

One bug I've realised is that long press only gets fired **after** the button have been released. This is not the common behaviour since users expects something to happen while pressing. I haven't been able to test this on an AppleTV project but I'm guessing that's how it's working there.

### Version

0.68.2-6

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.5.1
    CPU: (10) x64 Apple M1 Max
    Memory: 622.58 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 29, 30, 31, 32
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-23 | Android TV ARM EABI v7a, android-30 | Android TV Intel x86 Atom, android-30 | Google TV Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-31 | Android TV ARM 64 v8a, android-31 | Google TV ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.2-6
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.70.1 is now available (your project is running on v0.68.2-6).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.70.1.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.68.2-6.
info To upgrade, run "react-native upgrade".

### Steps to reproduce

Listen to a longSelect event like so:

```
  const myTVEventHandler = evt => {
    console.log(evt.eventType);

    if (evt && evt.eventType === 'select') {
      handleSelect(selectedChannel);
    } else if (evt && evt.eventType === 'longSelect') {
      console.log('Long press');
    }
  };

  useTVEventHandler(myTVEventHandler);
```

Notice that the log only shows up after you released the button.

**Comment by douglowder** [comment]
Confirmed, the Android TV behavior is as described, and is different from Apple TV. I'll take a look.

**Comment by douglowder** [comment]
This reproduces on 0.69.5-1. Also, we need to make sure that the fix for #349 does not regress

**Comment by abthkr** [comment]
Facing the same issue. I need to implement bi-directional scrollview and bring the current row/column in front focus.  I am trying to implement scroll actions on my custom scrollview (as paging was not supported for vertical scrollview/flatlist) on directional events. But that only works for single event, since cannot detect if user is long pressing the directional control (so that my scrollview scrolls multiple rows/columns while user is long pressing).

**Comment by josefnorlin** [comment]
> This reproduces on 0.69.5-1. Also, we need to make sure that the fix for #349 does not regress

Still present on 0.69.6-2 even with this PR: https://github.com/react-native-tvos/react-native-tvos/pull/396

**Comment by danychi** [comment]
Probably we need a fix like this on this [file](https://github.com/danychi/react-native-tvos/blob/24db404ce5cfcad6f6ace015d7ba86f458f724fe/ReactAndroid/src/main/java/com/facebook/react/modules/core/ReactAndroidHWInputDeviceHelper.java#L112)

```java
// Simple implementation of long press detection
if ((eventKeyAction == KeyEvent.ACTION_DOWN)
    && isSelectOrDPadEvent && mLastKeyDownTime == 0) {
    // dispatch long press event when it began
    dispatchEvent(KEY_EVENTS_LONG_PRESS_ACTIONS.get(eventKeyCode), mLastFocusedViewId, eventKeyAction, context);
    mLastKeyDownTime = time;
}
```

**Comment by wouterds** [comment]
@janvandertaelen

**Comment by sharan-SKY** [comment]
i believe there is another issue where longSelect gets triggered even when I do a normal press. I dont have to necessarily wait for one second for `longSelect` to trigger. is there an existing issue for this? I am using version 0.68.2

**Comment by douglowder** [comment]
@sharan-SKY you should upgrade to the latest (0.73.2-0)
