### ISSUE TITLE
Couldn't determine Hermesc location on Android Release

### ISSUE THREAD

**Issue by geroale** [react-native-tvos/react-native-tvos#364]
### Description

When compiling on Android release mode (debug mode is working) with hermes enabled, the following error is showing, blocking the build

`org.gradle.internal.UncheckedException: java.lang.Exception: Couldn't determine Hermesc location. Please set project.ext.react.hermesCommand to the path of the hermesc binary file. node_modules/react-native/sdks/hermesc/%OS-BIN%/hermesc`

This is because the folder `hermesc`, which is the hermes compiler, is missing in the `node_modules/react-native/sdks/` folder.

However this folder is present when creating a fresh project with the vanilla `react-native` template.

A way to workaround this, is indeed to take the folder `node_modules/react-native/sdks/hermesc` from a fresh generated `react-native` project and copy it in a `react-native-tv` one, in the same location.

It would be awesome to include it also in the `react-native-tvos` package, but we weren't able to understand the root cause of this issue.

### Version

0.69.5-1

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.02 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.17 - /usr/local/opt/node@14/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.69.5-1 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Create a new project with `react-native-tvos` template
- Enable hermes on Android
- Compile for Android in release mode

**Comment by douglowder** [comment]
@geroale could you try with 0.69.5-1?

**Comment by douglowder** [comment]
Confirmed, this reproduces on a newly created project with 0.69.5-1. Agreed, the solution is not obvious at all yet, I'll take this up immediately.

**Comment by geroale** [comment]
@douglowder Thank you so much :)

**Comment by douglowder** [comment]
I think the root cause is that the `hermesc` path changed from 0.68 to 0.69.

See @cortinico 's comment: https://github.com/facebook/react-native/issues/34043#issuecomment-1163796634

I'll have a look at what is missing from this repo to set up the paths correctly.

**Comment by douglowder** [comment]
Please patch your app as below, and see if that fixes the issue for you.

```patch
diff --git a/node_modules/react-native/react.gradle b/node_modules/react-native/react.gradle
index 2e9d8e5..5b2347d 100644
--- a/node_modules/react-native/react.gradle
+++ b/node_modules/react-native/react.gradle
@@ -123,6 +123,15 @@ def getHermesCommand = {
         return prebuiltHermes.getAbsolutePath()
     }
 
+    // 4. If the above fails, use hermesc from hermes-engine dependency
+    def hermesEnginePath = "node_modules/hermes-engine/%OS-BIN%/hermesc"
+        .replaceAll("%OS-BIN%", getHermesOSBin())
+        .replace('/' as char, File.separatorChar);
+    def hermesEngineHermes = new File(reactRoot, hermesEnginePath)
+    if (hermesEngineHermes.exists()) {
+        return hermesEngineHermes.getAbsolutePath()
+    }
+
     throw new Exception("Couldn't determine Hermesc location. " +
         "Please set `project.ext.react.hermesCommand` to the path of the hermesc binary file. " +
         "node_modules/react-native/sdks/hermesc/%OS-BIN%/hermesc");
```

**Comment by geroale** [comment]
@douglowder Yes, it seems to work for us. Thank you

**Comment by cortinico** [comment]
Hey all,
Happy to bring a bit of clarity here.

Starting from React Native 0.69, we're shipping Hermes together with React Native (we call this 'Bundled Hermes'. See https://reactnative.dev/architecture/bundled-hermes

With Bundled Hermes, we dropped the old `hermes-engine` NPM Package and we distribute `hermesc` (the hermes compiler) as part of react native. It's located inside the `sdks/hermesc/` folder.

> Please patch your app as below, and see if that fixes the issue for you.

Please note that this patch is falling back to the `hermes-engine` NPM Package, which is considered 'deprecated'. Specifically the bytecode version of `hermesc` from the `hermes-engine` NPM Package will probably diverge from the Hermes version you're using.

I'm unsure which version of Hermes is `react-native-tvos` using, but the tl;dr is: if you get `hermesc` and `hermes` (the runtime) from two different sources, things might break.

**Comment by douglowder** [comment]
Thanks @cortinico ! I'm working on fixing this properly by building `hermesc` the same way that RN core does, but I wanted to make sure that people were unblocked while I'm getting that done :)

**Comment by nunsie** [comment]
My release builds crash due to the bytecode issue mentioned above (after applying patch)

```
09-29 12:17:05.479 14104 14132 E AndroidRuntime: FATAL EXCEPTION: mqt_js
09-29 12:17:05.479 14104 14132 E AndroidRuntime: Process: com.package, PID: 14104
09-29 12:17:05.479 14104 14132 E AndroidRuntime: com.facebook.jni.CppException: Compiling JS failed: Wrong bytecode version. Expected 85 but got 84 Buffer size 2492812 starts with: c61fbc03c103191f54000000980d5711
09-29 12:17:05.479 14104 14132 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-29 12:17:05.479 14104 14132 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
09-29 12:17:05.479 14104 14132 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-29 12:17:05.479 14104 14132 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
09-29 12:17:05.479 14104 14132 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
09-29 12:17:05.479 14104 14132 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
09-29 12:17:05.479 14104 14132 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
09-29 12:17:05.479 14104 14132 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
```

In order to resolve and get the release build running on my devices again:

1. copied the `hermesc` dir from vanilla `react-native` into my repo.
2. set a `postinstall` npm script to move it to the correct `sdks` location.

This approach has a LOT of drawbacks (those bins add nearly 50mb to source) and is meant to be SUPER temporary but got me going again, just sharing incase anyone else was looking for an alternative in the meanwhile 👍

**Comment by cortinico** [comment]
> This approach has a LOT of drawbacks (those bins add nearly 50mb to source) and is meant to be SUPER temporary but got me going again, just sharing incase anyone else was looking for an alternative in the meanwhile 👍

Thanks for sharing this. You should be fine by adding a dependency on the `react-native` package and use `hermesc` from there though.

For future reference: we're updating the way how we distribute artifacts with an RFC here: https://github.com/react-native-community/discussions-and-proposals/pull/508
Once we land that, you should be able to just fetch `hermesc` for a specific version of React Native from the storage source we pick.

**Comment by douglowder** [comment]
Release 0.69.5-2 is published, and includes the correct `hermesc` artifacts from RN core 0.69.5.
