### ISSUE TITLE
I18nManager.allowRTL(false) not working in tvOS

### ISSUE THREAD

**Issue by aniketgupta8960** [react-native-tvos/react-native-tvos#372]
### Description

We are building a tvOS app which support multiple language. When the device language is Arabic then the I18nManager.allowRTL(false) doesn't work when app launches. The Ui gets disturbed.We want that the device language doesn't affect the app style . As we reload the app then the RTL is disabled
Is there a solution to disable RTL

### Version

68.2-2

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 230.93 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/‘~/.npm-global/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 21, 23, 25, 27, 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.2-2 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

When the device language is changed to arabic then I18nManager.allowRTL(false)  doesn't work when app launches first time. IF we reload the app then it works fine

**Comment by douglowder** [comment]
I am confused about this requirement. If the device language is Arabic, RTL must be enabled in order for the app to work correctly, yes?

**Comment by douglowder** [comment]
Also, if you can provide a simple app that shows this problem, it would be helpful in understanding and debugging the issue.
