### ISSUE TITLE
 ERROR  Invariant Violation: `new NativeEventEmitter()` requires a non-null argument. Getting this error on upgrade of tvOs version from 0.68.2-2 to 0.69.6 .

### ISSUE THREAD

**Issue by aniketgupta8960** [react-native-tvos/react-native-tvos#375]
### Description

I updated the react native tvOS version to 0.69.6-0. The previous tvOS version was 0.68.2-2.  
I have ran yarn install and pod install and also deleted node_modules and yarn.lock before running the yarn install command.But still this issue is there
Any Solution for this 
My package.json is
{
  "name": "KidsApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "postinstall": "patch-package",
    "lint": "eslint ."
  },
  "dependencies": {
    "@miblanchard/react-native-slider": "2.1.0",
    "@react-native-async-storage/async-storage": "1.15.15",
    "@react-native-community/netinfo": "8.2.0",
    "@react-navigation/native": "6.0.6",
    "@react-navigation/stack": "^6.2.2",
    "@sentry/react-native": "^4.6.1",
    "lottie-ios": "3.2.3",
    "lottie-react-native": "5.1.3",
    "patch-package": "6.4.7",
    "postinstall": "0.7.4",
    "postinstall-postinstall": "2.1.0",
    "react": "18.0.0",
    "react-native": "npm:react-native-tvos@0.69.6-0",
    "react-native-circular-gradient-progress": "1.0.6",
    "react-native-config": "1.4.5",
    "react-native-default-preference": "1.4.4",
    "react-native-device-info": "9.0.2",
    "react-native-elements": "3.4.2",
    "react-native-fs": "2.19.0",
    "react-native-game-center": "https://github.com/miracle2k/react-native-game-center",
    "react-native-gesture-handler": "^2.5.0",
    "react-native-image-picker": "4.7.3",
    "react-native-keyboard-aware-scroll-view": "0.9.5",
    "react-native-linear-gradient": "2.5.6",
    "react-native-localization": "2.3.1",
    "react-native-material-menu": "2.0.0",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "^3.15.0",
    "react-native-select-dropdown": "1.7.0",
    "react-native-simple-default-props": "^1.0.0",
    "react-native-sound": "0.11.2",
    "react-native-splash-screen": "3.3.0",
    "react-native-sqlite-storage": "6.0.1",
    "react-native-svg": "12.3.0",
    "react-native-uuid": "2.0.1",
    "react-native-vector-icons": "9.1.0",
    "react-native-webp-format": "1.1.2",
    "react-native-zip-archive": "6.0.6",
    "react-redux": "7.2.6",
    "redux-persist": "6.0.0"
  },
  "devDependencies": {
    "@babel/core": "7.17.10",
    "@babel/runtime": "7.17.9",
    "@react-native-community/eslint-config": "3.0.1",
    "babel-jest": "28.0.3",
    "eslint": "8.14.0",
    "jest": "28.0.3",
    "metro-react-native-babel-preset": "0.70.3",
    "react-test-renderer": "18.0.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

 

### Version

0.69.6-0

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 48.54 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/‘~/.npm-global/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 21, 23, 25, 27, 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.69.6-0 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Add the latest version of tvOS in package.json then this error happening

**Comment by douglowder** [comment]
Please provide a complete app that shows the issue, so I can see the stack and determine the source of this error.
