### ISSUE TITLE
react-native-template-typescript-tv fails with "Could not locate Gemfile"

### ISSUE THREAD

**Issue by iDVB** [react-native-tvos/react-native-tvos#377]
### Description

When running...
`react-native init TestApp --template=react-native-template-typescript-tv`
it errors out with `Could not locate Gemfile`

### Version

9.2.1

### Output of `npx react-native info`

`npx react-native info`
errors with
error: unknown command 'info'
(Did you mean init?)

### Steps to reproduce

Run the following when you already have the cocoapods gem installed.
`react-native init TestApp --template=react-native-template-typescript-tv`

**Comment by douglowder** [comment]
Thanks for the bug report, I will take a look.

**Comment by douglowder** [comment]
Tracking this in https://github.com/react-native-tvos/react-native-template-typescript-tv/issues/5
