### ISSUE TITLE
AndroidTv / React native player not working when start app

### ISSUE THREAD

**Issue by EGutierrezVargas** [react-native-tvos/react-native-tvos#381]
### Description

Hi guys, i have a problem when i run npm i react-native-video and start application no play the video, buy when i run whitout react-native-os is play with the video.

![image](https://user-images.githubusercontent.com/20630878/197589489-8be19e0c-62bc-4ba4-9586-4d1291d8886b.png)

![image](https://user-images.githubusercontent.com/20630878/197589525-781202bb-b8a1-4425-b9ec-72e583e79965.png)

  "dependencies": {
    "react": "18.0.0",
    "react-native": "npm:react-native-tvos@latest",
    "react-native-video": "^5.2.1"
  },

### Version

18.0.0

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 4.29 GB / 15.63 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: Not Found
  Languages:
    Java: 11.0.16.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: Not Found
    react-native-tvos:  0.69.5-2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I run this command react-native init DummyTVApp --version=react-native@npm:react-native-tvos@latest
and before npm i react-native-video when y watching video no display.

### Snack, code example, screenshot, or link to a repository
```jsx
import React,{useState, useEffect} from "react";
import { View, Text, StyleSheet, Button,Dimensions,Platform,TVEventHandler} from "react-native";
import Video  from 'react-native-video';
// import TVEventHandler from 'TVEventHandler';
// import TVEventHandler from 'react-native/Libraries/Components/AppleTV/TVEventHandler';

const App = () => {
  const [dataURl, setDataURl] = useState('');
  const [loading, setLoading] = useState(false);
  const [heightLandscape, setHeigthLandscape] = useState();

  // const _tvEventHandler = new TVEventHandler();

  // const _enableTVEventHandler = () => {
  //   _tvEventHandler.enable(this, function (cmp, evt) {
  //     if (evt && evt.eventType === 'right') {
  //       console.log(evt.eventType);
  //     } else if (evt && evt.eventType === 'up') {
  //       console.log(evt.eventType);
  //     } else if (evt && evt.eventType === 'left') {
  //       console.log(evt.eventType);
  //     } else if (evt && evt.eventType === 'down') {
  //       console.log(evt.eventType);
  //     }
  //   });
  // };


  const _disableTVEventHandler = () => {
    if (_tvEventHandler) {
      _tvEventHandler.disable();
    }
  }


  const getData = async(endpoint,option) => {
    const getUrl = await fetch(`${endpoint}`,option);
    const data = await getUrl.json();
    return data;
  }
 
  const { width, height } = Dimensions.get('window');

  const getDimensions = (width,height) => {
    const isLandscapeMode = width > height ? true : false;
    return isLandscapeMode;
  }

  
  // useEffect(() => {
  //   console.log('widthss',Platform.isTV);
    
  //     _enableTVEventHandler();
  //     //   return () => _disableTVEventHandler();
  //     // });

  //     // return null;

  //   // this.TVEventHandler = new TVEventHandler();
  //   // TVEventHandler.enable(this, (cmp, evt) => {
  //   //  console.log(evt);
  //   // });

  //   const getOrientation =  getDimensions(width,height);
  //   getOrientation ? setHeigthLandscape('100%') : setHeigthLandscape(width * .5625)
  
    
  //   const subscription = Dimensions.addEventListener("change",({ window, screen }) => {
  //       const resultDimensions = getDimensions(window.width,window.height)
  //       resultDimensions ? setHeigthLandscape('100%') : setHeigthLandscape(width * .5625)
  //     });

  //   return () => subscription?.remove();

  // }, []);  

  var styles = StyleSheet.create({
    backgroundVideo: {
      position: 'absolute',
      top: 0,
      left: 0,
      bottom: 0,
      right: 0,
    },
    containerViewVideo:{
      position: 'absolute',
      width: '100%',
      height: '50%',
    },
    container:{
      width: '100%',
      height: '100%'
    },
    video:{
      flex: 1,
      width: Dimensions.get('window').width,
      height: Dimensions.get('window').width
    }
    });

    return <>
            <Text>hOLAAAA</Text>
          <View>
          <Video source={{uri: "https://samplelib.com/lib/preview/mp4/sample-5s.mp4"}}   // Can be a URL or a local file.
            // ref={ref => (this.player = ref)}
            title="Lista de casa de Papel"
            // onLoad={(data) => {
            //   // console.log('data',data)
            //   // this.player.seek(1200)
              
            // }}
        
            style={styles.container}
            resizeMode='contain'
          //  onBuffer={this.onBuffer}
            controls={true}
          />
          </View>
          
          </>
}

export default App;
```

**Comment by freeboub** [comment]
Please don't put useless commented code in ticket description.
You need to provide the exact react native react-native-tvos you use. in 10 month, nobody will be able to understand what is lastest...
Did you try to play the video with another version or with regular react-native.
It looks more an issue with react-native-video. Did you try to test this video with react-native-video sample ?

**Comment by douglowder** [comment]
It would be helpful if you provide a working example repo that shows the problem.

Since your app is using functional components, I'd also recommend strongly that you use the `useTVEventHandler()` hook instead of creating your own `TVEventHandler` objects.

**Comment by Leena-Sharma-rsys** [comment]
While using UseTVHandler, it gives an error of TypeError: (0, _react.useTVEventHandler) is not a function. (In '(0, _react.useTVEventHandler)()', '(0, _react.useTVEventHandler)' is undefined)
