### ISSUE TITLE
TVEventHandler and many tv build components gone

### ISSUE THREAD

**Issue by akbari6776** [react-native-tvos/react-native-tvos#382]
### Description

In the first i don't install react-native-tvos and i can't find TVEventHandler, then with google search i know i should install this package and i installed and everything was fine, but today i got this error :

<img width="1434" alt="Screenshot 2022-10-26 at 20 15 51" src="https://user-images.githubusercontent.com/42941890/198140549-654ac2bf-74f1-440a-997d-2ac95156c5ba.png">

![Screenshot 2022-10-26 at 21 35 43](https://user-images.githubusercontent.com/42941890/198140589-5f29b61a-836c-4a66-b8df-491017a877c1.png)

When i search in `./node_modules/react-native/Libraries/component` i noticed that TV component and TabBarIOS components and many other component is gone

![Screenshot 2022-10-27 at 00 49 21](https://user-images.githubusercontent.com/42941890/198140454-8e6103c8-0f33-4ce9-b3b9-b191657ae9be.png)

even i install again this package : `yarn add react-native@npm:react-native-tvos@latest` but nothing

### Version

0.69.3

### Output of `npx react-native info`

System:
    OS: macOS 13.0
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 47.42 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 24, 25, 28, 29, 30, 31, 32
      Build Tools: 28.0.2, 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0
      System Images: android-28 | Android TV Intel x86 Atom, android-28 | China version of Wear OS Intel x86 Atom, android-28 | Wear OS Intel x86 Atom, android-28 | ARM 64 v8a, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs ARM 64 v8a, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google ARM64-V8a Play ARM 64 v8a, android-28 | Google Play Intel x86 Atom, android-29 | ARM 64 v8a, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Android TV Intel x86 Atom, android-30 | China version of Wear OS 3 - Preview Intel x86 Atom, android-30 | Wear OS 3 - Preview Intel x86 Atom, android-30 | ARM 64 v8a, android-30 | Intel x86 Atom_64, android-30 | Google TV Intel x86 Atom, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64, android-31 | Android TV Intel x86 Atom, android-31 | ARM 64 v8a, android-31 | Intel x86 Atom_64, android-31 | Google TV Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google APIs Intel x86 Atom_64, android-32 | Google Play ARM 64 v8a, android-32 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: npm:react-native-tvos@latest => 0.69.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Absence of TV component
Absence of TabBarIOS
Absence of many tv build components
even with install `yarn add react-native@npm:react-native-tvos@latest` again and again

**Comment by akbari6776** [comment]
I created a new tvos project and copied the TV and TabBarIos folders and the index.js file and then put it in my main project and the errors went away and the project can run, but all is not well, very It's not working properly.

**Comment by douglowder** [comment]
I suspect that you might have installed both react-native and react-native-tvos, which will not work. react-native-tvos is a fork of the main react-native project, so you should never install both.

**Comment by akbari6776** [comment]
@douglowder yes i first install react-native then run command yarn add react-native@npm:react-native-tvos@latest

it was ok but when i worked on project i got ViewPropType error and installed deprecated-react-native-prop-types, and then TV and TabIosBar folder deleted

**Comment by douglowder** [comment]
From the README for this repo:

> To build your project for Apple TV, you should change your `package.json` imports to import `react-native` as follows, so that this package is used instead of the core react-native package.

```js
"react-native": "npm:react-native-tvos@latest",
```

> You cannot use this package and the core react-native package simultaneously in a project.
