### ISSUE TITLE
Failed to transform react-native-0.71.0-rc.0-debug.aar

### ISSUE THREAD

**Issue by wouterds** [react-native-tvos/react-native-tvos#386]
### Description

Out of nowhere my 2 react-native-tvos projects don't compile anymore for Android.

During compilation the build eventually fails with the following;
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-config:generateDebugRFile'.
> Could not resolve all files for configuration ':react-native-config:debugCompileClasspath'.
   > Failed to transform react-native-0.71.0-rc.0-debug.aar (com.facebook.react:react-native:0.71.0-rc.0) to match attributes {artifactType=android-symbol-with-package-name, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform: /Users/wouterds/.gradle/caches/modules-2/files-2.1/com.facebook.react/react-native/0.71.0-rc.0/7a7f5a0af6ebd8eb94f7e5f7495e9d9684b4f543/react-native-0.71.0-rc.0-debug.aar.
```

It looks like it's using a wrong future version of react native (`0.71.0-rc`)? I'm using `0.66.3-3` in this specific project.

This was working 3 days ago in both repositories and nothing changed in between, I have nightly build pipeline and prior builds also don't compile anymore. I have tried deleting `~/.gradle`, node_modules & android build cache multiple times, the build pipeline that produces my nightly builds always starts without any cache so we can spot these kind of issues.

It started happing approximately around 2022-11-04 19:00 UTC.

Any help would be much appreciated!

### Version

0.66.3-3

### Output of `npx react-native info`

```
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M2
    Memory: 278.50 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Watchman: 2022.10.31.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/wouterds/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 26, 28, 30, 31
      Build Tools: 28.0.3, 30.0.2, 31.0.0
      System Images: android-31 | Google TV ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.66.3-3 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

```
yarn android
```

### Snack, code example, screenshot, or link to a repository

https://github.com/wouterds/react-native-tv-example

**Comment by wouterds** [comment]
Ah I just saw react-native [released a hotfix](https://github.com/facebook/react-native/releases/tag/v0.70.5) addressing this issue & mentions this as workaround: https://github.com/facebook/react-native/issues/35210.

**Comment by wouterds** [comment]
The workaround described in above issue works https://github.com/wouterds/react-native-tv-example/commit/266f7d8dc5ec511548cd9755567e3d9da789a449

**Comment by douglowder** [comment]
Thanks for the heads up @wouterds ... wow.

I'll take a look to see if I can patch TV repo for 0.68 and higher releases.
