### ISSUE TITLE
Text getting focus instead of touchables (Android only)

### ISSUE THREAD

**Issue by wouterds** [react-native-tvos/react-native-tvos#389]
### Description

I just upgraded to version `0.69.5-2` very meticulously and everything compiles and runs, but the focus engine seems to be focusing Text nodes now instead of Touchables. I discovered this by turning on a debug setting, then you can see the Text gets the focus instead of the button. With debug mode off it looks like the focus is not working until you click a few times (as we don't have focus states for text).

This was not the case in the previous version we were running (0.66.3-3).

### Version

0.69.5-2

### Output of `npx react-native info`

```
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M2
    Memory: 122.89 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Watchman: 2022.10.31.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/wouterds/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 26, 28, 30, 31
      Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-31 | Google TV ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.69.5-2 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Render a screen with some touchables on top, then some text in between and then some more buttons. When navigating down from the top you will first pass through the text nodes and only then land on the touchables on the bottom.

### Snack, code example, screenshot, or link to a repository

I currently don't have a demo project to show this behaviour but can look into one if desired and we don't get this sorted out else.

**Comment by wouterds** [comment]
This resolves the issue but it can't be right that I would have to explicitly opt-out from this everywhere we use Text? There's ways around it by abstracting Text into a custom component but still that seems not ideal?

![Screen Shot 2022-11-09 at 10 28 01](https://user-images.githubusercontent.com/1210628/200792548-e5ea2dcd-e932-40a7-85db-5e363298de52.jpg)

**Comment by wouterds** [comment]
So like I said we could go this route, having a custom Text component, this solves it for now but it doesn't really sit right with me, it's just a workaround, not a decent solution imo.

![Screen Shot 2022-11-09 at 13 15 52](https://user-images.githubusercontent.com/1210628/200828403-5ad2439e-299b-40b6-98cf-1848cdf51af8.jpg)

![Screen Shot 2022-11-09 at 13 16 18](https://user-images.githubusercontent.com/1210628/200828396-1fd30f25-6c65-4d48-a4ba-fd071603621a.jpg)

**Comment by wouterds** [comment]
I'm gonna close it for now as above workaround works, but look into demo project if I can reproduce this bug

**Comment by geroale** [comment]
We have the same issue

**Comment by wouterds** [comment]
I ended up creating a custom `Text` component where we set the default value for `accessible` to `false`.

```
import React, { memo } from 'react';
import { Text as RNText, TextProps as RNTextProps } from 'react-native';

type Props = RNTextProps;

export type TextProps = Props;

const Text = (props: Props) => (
  <RNText
    {...props}
    accessible={props.accessible || false}
  />
);

export default memo(Text);
```

**Comment by douglowder** [comment]
@wouterds I took at look at the commit history of the Android native textinput views, and found this change that it seems to me might explain this: https://github.com/react-native-tvos/react-native-tvos/commit/d4a78183b6c80d978a90d9dc85705a2ff30fef43

Can you try reverting that change and see if it fixes the issue for you?

**Comment by wouterds** [comment]
@douglowder I'll give it a try

**Comment by wouterds** [comment]
I'm not able to get my app compiling when I fork the react-native-tvos repo & apply the patch.

**Comment by douglowder** [comment]
@wouterds after applying the patch, you would need to execute

```
./gradlew :ReactAndroid:installArchives
```

inside the react-native-tvos repo, and then copy the `android` directory with that build into your app directory, replacing the existing `node_modules/react-native/android`

**Comment by clebeaupin** [comment]
+1 same issue.

**Comment by etiennelab** [comment]
+1 Same issue here on last version of react-native-version

**Comment by thomasyvert** [comment]
+1 Same issue too

**Comment by crewtaylorfd** [comment]
+1 Same issue on 0.68.2-6. I didn't have the issue right when I upgraded to 0.68.2-6 but have it now.

**Comment by douglowder** [comment]
Ok I've picked this up and had a look, and I think the change that made this happen is probably this change in RN core, or one of the changes that happened in `Text.js` afterwards: https://github.com/react-native-tvos/react-native-tvos/commit/f3bf2e4f51897f1bb71e37002c288ebf3b23cf78

Most likely, what we want for TV is to not have `Text` components be pressable, or setting `accessible` to false by default, but I'll take a look at different options and come up with the right fix.
