### ISSUE TITLE
App is not building on Android 

### ISSUE THREAD

**Issue by stepas-dev** [react-native-tvos/react-native-tvos#392]
### Description

Can't run app on android anymore, in normal react native the solution was upgrading it to version 0.69.7. Any solution ?

> What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:
      - /Users/stivas/.gradle/caches/transforms-3/a8108ce710a662637a30dedebdb0a106/transformed/jetified-react-native-0.71.0-rc.0-debug/jni/arm64-v8a/libc++_shared.so
      - /Users/stivas/.gradle/caches/transforms-3/1a8b906c1649e97dbca55059e0091063/transformed/jetified-fbjni-0.3.0/jni/arm64-v8a/libc++_shared.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets

### Version

npm:react-native-tvos@0.69.6-0

### Output of `npx react-native info`

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 77.52 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: 2022.10.10.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.69.6-0 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

run android

**Comment by douglowder** [comment]
Please see #386 and #390 . I will be publishing a hotfix soon, but you can use the workarounds described there.
