### ISSUE TITLE
Long press event is not firing when clicking on left/right button

### ISSUE THREAD

**Issue by zachariast** [react-native-tvos/react-native-tvos#408]
### Description

You guys rock!!

I am facing an issue(maybe a feature?) and I am not able to see an event when long pressing on left and right buttons on the RCU. I am currently testing it on Android Tv. 

Also when listening to the events I am receiving back the following:

`{"dispatchConfig": {}, "eventKeyAction": 1, "eventType": "right", "tag": 1763, "target": 1763}`

I am missing the **body** property

```
export type HWEvent = {
    eventType: 'up' | 'down' | 'right' | 'left' | 'blur' | 'focus' | 'pan' | string;
    eventKeyAction?: -1 | 1 | 0 | number;
    tag?: number;
    body?: {
      state: "Began" | "Changed" | "Ended",
      x: number,
      y: number,
      velocityx: number,
      velocityy: number
    }
  };
```

### Version

0.69.5-1

### Output of `npx react-native info`

```
System:
    OS: macOS 12.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 582.20 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 2022.10.31.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.4 - /usr/local/opt/openjdk@17/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.69.5-1
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

I am listening for the events here: 

```
if (evt && evt.eventType === 'right') {
    if (evt.eventKeyAction === 1) {
        this.seekForward();
    }
} else if (evt && evt.eventType === 'left') {
    if (evt.eventKeyAction === 1) {
        this.seekBackward();
    }
}
```

**Comment by douglowder** [comment]
The native implementation on Android TV is in https://github.com/react-native-tvos/react-native-tvos/blob/tvos-v0.69.6/ReactAndroid/src/main/java/com/facebook/react/modules/core/ReactAndroidHWInputDeviceHelper.java .

We don't fill in the optional `body` property for TV remote events, with the exception of pan events on the touchpad found on the Siri remote of the Apple TV.

We do fire events for long presses of the center ("select") button -- the event type is "longSelect". We don't send long press events for the arrow keys.
