### ISSUE TITLE
(Android TV) onFocus not firing inside a modal

### ISSUE THREAD

**Issue by maciejsiiminski** [react-native-tvos/react-native-tvos#414]
### Description

Hello,
I'm facing a similar issue to the one in issue #115 that was fixed in commit #219 . When I use TouchableOpacity inside a modal onFocus event is not fired. I tried setting a TVEventhandler and a NativeEventEmitter with a subscription onHWKeyEvent and neither receives any events. 
The weirdest part is that onPress event works correctly. If I put more TouchableOpacities inside the modal I can navigate and choose a specific TouchableOpacity to be pressed, but navigation is not visible and onFocus events are never fired. 

### Version

0.69.6-0

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19045
    CPU: (8) ia32 AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
    Memory: 919.63 MB / 5.95 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.7.0 - C:\Program Files (x86)\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
    Visual Studio: 17.0.32112.339 (Visual Studio Community 2022)
  Languages:
    Java: 18.0.1
  npmPackages:
    @react-native-community/cli: ^6.0.0 => 6.4.0
    react: 18.1.0 => 18.1.0
    react-native: 0.67.2 => 0.67.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Put TouchableOpacity that logs anything onFocus event inside a modal

**Comment by douglowder** [comment]
@maciejsiiminski I will set up to test this in RNTester again, but this was specifically fixed in #219 . Do you have an example project that shows the issue? That would greatly help in narrowing down the issue.
