### ISSUE TITLE
onfocus and onblur not firing at all

### ISSUE THREAD

**Issue by TDanks2000** [react-native-tvos/react-native-tvos#417]
### Description

onFocus and onBlur are not firing at all on my android box, when i press left or right on my remote control the scroll view moves but no on focus is being called

```js
import { TouchableOpacity } from "react-native";
import React, { useEffect, useState } from "react";

const Focusable = ({ children, onPress }) => {
  const [isFocused, setIsFocused] = useState(false);

  const setFocus = (type) => {
    console.log(type);
    setIsFocused(type);
  };

  useEffect(() => {
    console.log(isFocused);
  }, [isFocused]);

  return (
    <TouchableOpacity
      activeOpacity={0.1}
      onPress={onPress}
      onFocus={() => setFocus(true)}
    >
      {children}
    </TouchableOpacity>
  );
};

export default Focusable;
```

### Version

0.69.6-0

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22623
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 514.88 MB / 7.86 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: 17.2.32630.192 (Visual Studio Community 2022)
  Languages:
    Java: 11.0.17
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: Not Found
    react-native-tvos:  0.69.6-0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

press on remote and onfocus will not be called 

### Snack, code example, screenshot, or link to a repository

https://github.com/TDanks2000/Streamable-tv

**Comment by douglowder** [comment]
I'll take a look. In the meantime, you may wish to take a look at `Pressable`, as it already has `pressed` and `focused` callbacks that you can use.

**Comment by TDanks2000** [comment]
how do I access the focused  from Pressable

**Comment by TDanks2000** [comment]
also thought id just add to this the device is Beelink GT King 4k

**Comment by TDanks2000** [comment]
> I'll take a look. In the meantime, you may wish to take a look at `Pressable`, as it already has `pressed` and `focused` callbacks that you can use.

focused is not getting called here either

on my box or wsa with arrow keys

```js
import { Pressable, Text, TouchableOpacity } from "react-native";
import React, { useEffect, useState } from "react";

const Focusable = ({ children, onPress }) => {
  const [isFocused, setIsFocused] = useState(false);

  const setFocus = (type) => {
    console.log(type);
    setIsFocused(type);
  };

  return (
    <Pressable
      onHoverIn={() => setFocus(true)}
      onHoverOut={() => setFocus(false)}
      activeOpacity={0.1}
      onPress={onPress}
    >
      {({ pressed, focused }) => {
        console.log({ pressed, focused });
        return (
          <Text style={{ color: "white" }}>
            {pressed ? "Pressed!" : "Press Me"}
          </Text>
        );
      }}
    </Pressable>
  );
};

export default Focusable;
```

```
// console log

 {"focused": false, "pressed": true}
 {"focused": false, "pressed": false}
```

**Comment by TDanks2000** [comment]
as you can see the items are moving but the onfocus is not being called

https://user-images.githubusercontent.com/40835340/209128042-6a411830-9a3b-49a8-ae0f-36e9ac394741.mp4

**Comment by douglowder** [comment]
Could you add a `README.md` to your project, explaining how to build it on the command line for Android? Or is it Android Studio only?

**Comment by douglowder** [comment]
Even Android Studio fails. I get a variation of this error for command line or Android Studio.

```bash
$ expo run:android

This command is being executed with the global Expo CLI. Learn more: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421
To use the local CLI instead (recommended in SDK 46 and higher), run:
› npx expo run:android

› Building app...
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/dlowder/iosProjects/Streamable-tv/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 250

* What went wrong:
A problem occurred evaluating script.
> Calling `[node, /Users/dlowder/iosProjects/Streamable-tv/node_modules/@react-native-community/cli/build/bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object
  
  The current character read is 'i' with an int value of 105
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0
  info Run CLI with --verbose flag for more details.
  ^. Output: info Run CLI with --verbose flag for more details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 898ms
/Users/dlowder/iosProjects/Streamable-tv/android/gradlew exited with non-zero code: 1
Error: /Users/dlowder/iosProjects/Streamable-tv/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at spawnAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnGradleAsync (/usr/local/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:83:28)
    at assembleAsync (/usr/local/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:57:16)
    at actionAsync (/usr/local/lib/node_modules/expo-cli/src/commands/run/android/runAndroid.ts:145:22)
```

**Comment by TDanks2000** [comment]
i give up with react native, ive had multiple issues with it, and this just puts the nail in the coffin, im moving away from this and going to flutter

**Comment by douglowder** [comment]
Sorry to hear that. I created a new project, and added your component to it, and it works as expected in Android emulator.

I will create a repo with that project, feel free to try it out on your Android box.

**Comment by douglowder** [comment]
https://github.com/douglowder/Issue417

- Clone the repo
- Change to repo directory

```
yarn
cd android
./gradlew :app:installDebug
```

**Comment by IvanJRCH** [comment]
I relive this issue, because it still hasn't been fixed today 23/2/2024 onFocus and onBlur just don't work on android tv, and I'm stuck on this, I kindly request a solution to this serious problem

**Comment by h1nson** [comment]
Try this #308
