### ISSUE TITLE
(tvOS) TVTextScrollView does not work correctly when there is a focusable element above/below it

### ISSUE THREAD

**Issue by AntonBrevnov** [react-native-tvos/react-native-tvos#418]
### Description

Problem with TVTextScrollView on tvOS. When there are no focusable elements under/above it, then everything works without problems. But otherwise, when scrolling the text in the direction where the focused element is located, the text scrolls sharply to the end and the focus is shuffled to the next element

For example, there is such a code:

`
      <TouchableOpacity>
        ...
      </TouchableOpacity>
      <TVTextScrollView>
        Some big text
      </TVTextScrollView>
`

In this case, there is a Touchable Opacity over the TV Text Scroll View. If I scroll the text down, then there is no problem. But when I scroll it up, I will abruptly switch to the button and the entire contents of the TV Text Scroll View will scroll to the beginning.

### Version

0.68.2-3

### Output of `npx react-native info`

System:
    OS: macOS 13.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 2.49 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /var/folders/2v/npjwsgvd0x9cbmv_vt5zlqrh0000gp/T/yarn--1672211798751-0.32410066274861227/node
    Yarn: 1.22.10 - /var/folders/2v/npjwsgvd0x9cbmv_vt5zlqrh0000gp/T/yarn--1672211798751-0.32410066274861227/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-30 | Google TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Android TV Intel x86 Atom, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.2-3 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Create react native app for tv platforms
- Write this code in the App component
`
      <TouchableOpacity>
        ...
      </TouchableOpacity>
      <TVTextScrollView>
        Some big text
      </TVTextScrollView>
`
- run app on tvOS

**Comment by douglowder** [comment]
I am able to reproduce this in `RNTester` (after rebuilding it to be non-fabric).

I think that somehow the OS gesture handler that looks for swipes to move focus, is overriding the swipe gesture handler that we add in the scroll view. Will have a look at some different options for fixing this. If it is impossible to have a swipe, then maybe a pan gesture handler could be used instead.

**Comment by douglowder** [comment]
I will also have a look at implementing this feature in Fabric.

**Comment by Shizerq** [comment]
@douglowder is there any progress?
