### ISSUE TITLE
Android native focus event firing too fast

### ISSUE THREAD

**Issue by Joplinj** [react-native-tvos/react-native-tvos#419]
### Description

Hello everyone !

I'm facing a simple issue I guess. 

I'm developing an Android TV app.

Let's imagine an horizontal ScrollView, with 10 TouchableNativeFeedback inside, Then there is few element out of the screen, normal.

When i go right, onFocus fired, and set the ScrollView offset to 200 * index of the element.

The animation goes well, but if i go left, on an element outside of the screen, then the focus is fired too fast to bring the element in the visible screen, and then the animation not fire properly.

I probably missing something, about the native event managing.

Thanks ! :)

### Version

70.5

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.17763
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 4.06 GB / 15.40 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 31
      Build Tools: 30.0.3, 31.0.0, 33.0.1
      System Images: android-29 | Google Play Intel x86 Atom, android-31 | Android TV ARM 64 v8a, android-31 | Android TV Intel x86 Atom, android-31 | ARM 64 v8a, android-31 | Intel x86 Atom_64, android-31 | Google TV ARM 64 v8a, android-31 | Google TV Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_352 - C:\Program Files\Eclipse Adoptium\jdk-8.0.352.8-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create a new project for Android TV

Display a ScrollView fullscreen with enough Touchables elements inside to go out of the screen on the right and assign a style like 200px.

Set an onFocus on Touchables elements, that update the x position of the scrollview ( 200 * index ). Then the scrollview moove to keep the focus element not mooving.

Navigate with remote or keyboard

**Comment by douglowder** [comment]
You seem to be using version 0.70.5 of the core React Native repo, and not the React Native provided by this repo, which is currently at 0.69.6-0.
