### ISSUE TITLE
Pressable's android_ripple is applied on hover

### ISSUE THREAD

**Issue by zoriya** [react-native-tvos/react-native-tvos#440]
### Description

The ripple color is applied when the Pressable get focused. It should only be applied on press.

### Version

0.69.6-1

### Output of `npx react-native info`

System:
    OS: Linux 6.0 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 4.34 GB / 15.50 GB
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 3.2.4 - /usr/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 33
      Build Tools: 33.0.1
      System Images: android-30 | Android TV Intel x86 Atom, android-30 | Google TV Intel x86 Atom, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_352 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Simply add the ripple property to a Pressable and see. Example:

```tsx
const Example = () => {
	return (
		<Pressable android_ripple={{ foreground: true, color: "#000000" }}>
			<View style={{ width: 300, height: 300, backgroundColor: "red" }} />
		</Pressable>
	);
};
```

### Snack, code example, screenshot, or link to a repository

Example screenshots:
With android_ripple:
![image](https://user-images.githubusercontent.com/32224410/211209380-cc6f532e-1ba2-43ec-8eca-f561357790cd.png)
Without ripples:
![image](https://user-images.githubusercontent.com/32224410/211209420-ea28d6b3-d848-49cf-8f3b-397b92b2c3bd.png)

notice the black tint added to the image when android ripples are added.

**Comment by douglowder** [comment]
Hmm I will have to think about this one. To make existing apps work without too many changes needed, the general solution in React Native TV has been to execute `onPressIn` when a button is focused, so that the user can see what button has focus without the developer having to add special `onFocus` highlighting. This is probably what is causing the ripple to show.

I'll have a look at Google's Android TV development docs to see what we should be doing here.

@wouterds @yusufyildirim @leonchabbey would appreciate hearing your suggestions.

**Comment by AnonymusRaccoon** [comment]
I just tested this and actually, the onPressIn/onPressOut is never called on TV (at least in my tests). Neither pressing the select button nor focusing an object trigger those callbacks. Should I open another issue for that?

**Comment by douglowder** [comment]
No let's track that here. I will do some testing to see exactly what is calling the ripple onPressIn, and then work on a proper fix. I assume you want things to work the same for Touchable, correct?

**Comment by AnonymusRaccoon** [comment]
I actually have not tried the Touchable, I expect the focus to be triggered on entering/leaving the pressable. The onPress to be called when the user pressed/releases the select button, and the ripple to trigger when the user presses the button or start pressing it.

**Comment by douglowder** [comment]
I'm still debugging, but it seems that having a ripple at all causes ripple effect to show by default on focus, unless you change the defaults. I wasn't able to change the behavior by making any JS changes.

I found this Q&A that might shed some light on the issue:

https://stackoverflow.com/questions/42125871/android-ripple-drawable-and-state-focused-dpad-navigation

**Comment by AnonymusRaccoon** [comment]
Also, kinda related, but the `hasTVPrefferedFocus` props makes the focus ripple show on android mobile, and it can't be dismissed since focus is not implemented on react-native-android.
