### ISSUE TITLE
Rootview is nil

### ISSUE THREAD

**Issue by samsonroyquickplay** [react-native-tvos/react-native-tvos#467]
### Description

Whenever we render the component for the first time the rootview is always nil and if we load the view after a certain interval of time then rootview is not nil ? Any idea why this would happen ? @douglowder 

```
const Component = () => {

return <TouchableOpacity hasTVPreferredFocus={true}><Text>Hello</Text></TouchableOpacity>
} ---> This doesn't work.


const Component = () => {
const [timer, setTimer] = useState<boolean>(false);


 useEffect(() => {
    setTimeout(() => setTimer(true), 5000)
  }, [])

return timer ? <TouchableOpacity hasTVPreferredFocus={true}><Text>Hello</Text></TouchableOpacity> : null
} ----> This works
```

```
- (void)setPreferredFocus:(BOOL)hasTVPreferredFocus
{
  _hasTVPreferredFocus = hasTVPreferredFocus;
  if (hasTVPreferredFocus) {
    dispatch_async(dispatch_get_main_queue(), ^{
      RCTRootView *rootview = [self waitForNonNullRootView];
      if (rootview == nil) return;
      [rootview setReactPreferredFocusedView:self];
      [rootview setNeedsFocusUpdate];
    });
  }
}
```

### Version

0.69.6-2

### Output of `npx react-native info`

System:
    OS: macOS 12.6.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 36.06 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/samsonroy/.gems/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.69.6-2 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. We have sidebar and we go and hit enter on sidebar.
2. And that render the view beside the drawer,
3. It is not focusing any element even if the hasTvPrefferedFocus is true.

**Comment by douglowder** [comment]
The root view being initially nil is expected on iOS/tvOS. (In Fabric renderer, this does not happen, by the way.) The `waitForNonNullRootView` method is there precisely to solve this issue.

You say you have a sidebar -- are you using React Navigation? It would be helpful to see a complete small example project that reproduces the issue.
