### ISSUE TITLE
Multiple issues when attempting building from source

### ISSUE THREAD

**Issue by maciejsiiminski** [react-native-tvos/react-native-tvos#508]
### Description

I have been trying to build react native tvos from the source because our app has [random crushes caused by an unresolved error](https://github.com/facebook/react-native/issues/33375) and some people claim to have mitigated this issue by modifying react's java code. I forked this repository and changed the source according to their solution but unfortunately, I'm having problems building the artifacts from source. 

First of all, I had problems even getting information on how to build 0.69 as react native only has documentation on this topic for the current version. I used an internet archive to [get this page from approximately the time when the 0.69 was the current release](https://web.archive.org/web/20230131222557/https://reactnative.dev/contributing/how-to-build-from-source) and followed the instructions. Unfortunately, I got several errors when compiling ReactAndroid from the source.

The android code block causes `No signature of method: build_93d9su6vassuwgsnlj85kal3v.android() is applicable for argument types: (build_93d9su6vassuwgsnlj85kal3v$_run_closure21) values: [build_93d9su6vassuwgsnlj85kal3v$_run_closure21@8a0215e]`.   I've managed to conclude that the the `multipleVariants `part of publishing block
```
publishing {
        multipleVariants {
            withSourcesJar()
            withJavadocJar()
            allVariants()
        }
    }
```
causes this issue and commenting this part out fixes it but I don't know why this is the case and if commenting out this part doesn't affect the project in any significant way. 

The second error I came by and that is the one I cannot fix in any way is` Project with path ':ReactAndroid:hermes-engine' could not be found in project ':ReactAndroid'.` caused by line `compileOnly(project(":ReactAndroid:hermes-engine"))`. I know it is caused by project ReactAndroid:hermes-engine not being a part of the ReactAndroid project by I don't know how it is supposed to work without making it a multi-project build with setting.gradle file. Unfortunately, I only know the bare basics of gradle. 

I wouldn't qualify my problem as a bug but rather a question or help needed but these labels are not available in this repository. Sorry if I'm formulating the issue wrong and breaking the rules of this repo but I'm at a dead end, need some help and thought that this is the best place to ask as it concerns building react native tvos from source.

### Version

0.69.6-0

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19045
    CPU: (8) ia32 AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
    Memory: 825.54 MB / 5.95 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.7.0 - C:\Program Files (x86)\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
    Visual Studio: 17.0.32112.339 (Visual Studio Community 2022)
  Languages:
    Java: 11.0.15
  npmPackages:
    @react-native-community/cli: ^6.0.0 => 6.4.0
    react: 18.1.0 => 18.1.0
    react-native: 0.67.2 => 0.67.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Try building react native tvos android artifacts from source according to [this documentation](https://web.archive.org/web/20230131222557/https://reactnative.dev/contributing/how-to-build-from-source)

### Snack, code example, screenshot, or link to a repository

my setting.gradle file 
```
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenLocal()
        google()
    }
}

include ':app', ':react-native', ':react-native-gesture-handler', ':react-native-reanimated', ':react-native-vector-icons', ':react-native-community-masked-view', ':react-native-safe-area-context', ':react-native-video', ':react-native-svg', ':react-native-community-async-storage', ':react-native-device-info', ':react-native-keychain', ':react-native-system-setting', ':react-native-community-netinfo', ':react-native-splash-screen', ':ReactAndroid'

project(':react-native').projectDir = new File('C:/Users/macie/MetroApp/node_modules/react-native')
project(':react-native-gesture-handler').projectDir = new File('C:/Users/macie/MetroApp/node_modules/react-native-gesture-handler/android')
project(':react-native-reanimated').projectDir = new File('C:/Users/macie/MetroApp/node_modules/react-native-reanimated/android')
project(':react-native-vector-icons').projectDir = new File('C:/Users/macie/MetroApp/node_modules/react-native-vector-icons/android')
project(':react-native-community-masked-view').projectDir = new File('C:/Users/macie/MetroApp/node_modules/@react-native-community/masked-view/android')
project(':react-native-safe-area-context').projectDir = new File('C:/Users/macie/MetroApp/node_modules/react-native-safe-area-context/android')
project(':react-native-video').projectDir = new File('C:/Users/macie/MetroApp/node_modules/react-native-video/android-exoplayer')
project(':react-native-svg').projectDir = new File('C:/Users/macie/MetroApp/node_modules/react-native-svg/android')
project(':react-native-community-async-storage').projectDir = new File('C:/Users/macie/MetroApp/node_modules/@react-native-community/async-storage/android')
project(':react-native-device-info').projectDir = new File('C:/Users/macie/MetroApp/node_modules/react-native-device-info/android')
project(':react-native-keychain').projectDir = new File('C:/Users/macie/MetroApp/node_modules/react-native-keychain/android')
project(':react-native-system-setting').projectDir = new File('C:/Users/macie/MetroApp/node_modules/react-native-system-setting/android')
project(':react-native-community-netinfo').projectDir = new File('C:/Users/macie/MetroApp/node_modules/@react-native-community/netinfo/android')
project(':react-native-splash-screen').projectDir = new File('C:/Users/macie/MetroApp/node_modules/react-native-splash-screen/android')
project(':ReactAndroid').projectDir = new File('C:/Users/macie/MetroApp/node_modules/maciejsiiminski/react-native-tvos/ReactAndroid')
includeBuild('C:/Users/macie/MetroApp/node_modules/maciejsiiminski/react-native-tvos/packages/react-native-gradle-plugin')
```

**Comment by wouterds** [comment]
I've been looking at this issue extensively past half year and tried fixing it https://github.com/react-native-tvos/react-native-tvos/pull/457, but it's still present (in react-native core, it's not -tvos specific), also in the latest versions like .71 people are still reporting it.

I've made a reproducible example using the -tvos repo (described here https://github.com/facebook/react-native/issues/33686#issuecomment-1525541443), and we've got now a new dedicated ticket to debug this (here: https://github.com/facebook/react-native/issues/37267), but the react-native core maintainers would like to see a vanilla react-native project that can reproduce the issue.

I think it's just a lot harder to do on Android phones as they're much quicker than the Android TV devices and similarly with emulators, it's also a lot harder to reproduce.

Not really an answer to your question directly but just FYI the problem is located higher up and is currently awaiting a reproducible example in a vanilla RN project.

**Comment by douglowder** [comment]
@wouterds the scripts that builds the Android binaries for the TV repo is in `scripts/prepare-tv-release.js`. Do you need to build for 0.69 or 0.71? Does the build need to include Hermes to reproduce this bug?

**Comment by douglowder** [comment]
@maciejsiiminski for 0.69 you should clone the repo, make your changes, then do

`node scripts/prepare-tv-release.js`

and go get a coffee while you wait for it to finish.

This creates an `android` directory containing the Android artifacts. Copy that into `node_modules/react-native` in your app project directory, replacing the `node_modules/react-native/android` directory that is installed by NPM.
