### ISSUE TITLE
Error when adding "use_frameworks! :linkage => :static" to Podfile to enable third-party library usage

### ISSUE THREAD

**Issue by CodingByJerez** [react-native-tvos/react-native-tvos#517]
We encountered an error when adding the line "use_frameworks! :linkage => :static" to the Podfile of our project. We added this line to enable the usage of a third-party library in our project.

However, during compilation, the following error occurred:

```
Multiple commands produce '.../Build/Products/Debug-iphonesimulator/ReactCommon-framework/ReactCommon.framework/Headers/CallbackWrapper.h'

Target 'ReactCommon-framework' (project 'Pods') has copy command from '.../app/node_modules/react-native/ReactCommon/react/bridging/CallbackWrapper.h' to '.../Build/Products/Debug-iphonesimulator/ReactCommon-framework/ReactCommon.framework/Headers/CallbackWrapper.h'

Target 'ReactCommon-framework' (project 'Pods') has copy command from '.../app/node_modules/react-native/ReactCommon/react/nativemodule/core/ReactCommon/CallbackWrapper.h' to '.../Build/Products/Debug-iphonesimulator/ReactCommon-framework/ReactCommon.framework/Headers/CallbackWrapper.h'


```

Context:
We added the line "use_frameworks! :linkage => :static" to our Podfile to enable the usage of a third-party library in our project. This third-party library is essential for adding specific functionalities to our application.

However, during compilation, we received the above-mentioned error. It appears that there is a conflict in copying the "CallbackWrapper.h" file within the ReactCommon framework.

We are seeking a solution to resolve this error and enable the usage of the third-party library in our project.

Any assistance or suggestions would be greatly appreciated. Thank you.

### Version

0.71.10-0

### Output of `npx react-native info`

System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 85.59 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.4.0 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/opt/ruby/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.71.10-0 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Steps to reproduce:

Open the Podfile in your project.
Locate the section where dependencies are defined.
Add the following line: use_frameworks! :linkage => :static
Save the Podfile.
Run the command pod install in the terminal to install the updated dependencies.
Build the project using Xcode or the command line.
Observe the compilation process and the resulting error message.
Expected result:
The project should compile successfully without any errors.

Actual result:
The error message mentioned in the description is displayed during the compilation process.

Note: The issue occurs specifically when the line "use_frameworks! :linkage => :static" is added to the Podfile in order to enable the usage of a third-party library in the project.

### Snack, code example, screenshot, or link to a repository

```
...//

target 'MyApp' do
  platform :ios, min_ios_version_supported

 +  use_frameworks! :linkage => :static

...//
```

**Comment by douglowder** [comment]
This seems related to the issues raised in https://github.com/facebook/react-native/issues/37554 .

I will need an actual project that reproduces the error, so I can see what libraries you are trying to link, the order of the code in the Podfile, etc.

**Comment by CodingByJerez** [comment]
Dear @douglowder,

Thank you for promptly responding to my request. I want to express my gratitude for your assistance.

As requested, I will provide you with a project that reproduces the error. Here is the link to the project: https://github.com/CodingByJerez/react-native-tvos-show-prob

I want to emphasize that in the previous version, I was using the Firebase Conversion library 14.12.0 (slightly patched), and this version still works with React Native version 0.71.10-0. However, when I try to upgrade to a newer version than 14.12.0, I add "use_frameworks! :linkage => :static" to the Podfile, which triggers the error I mentioned earlier. It is important to note that this error does not seem to be related to the Firebase Conversion library because even if it is not installed, as soon as we add this line, the error occurs.

I hope this information will be helpful in understanding and resolving the issue I am facing. If you need further details or any other information, please let me know.

(PS: On the other hand, I have successfully managed to run version 0.71.10-0 without any issues. However, when I try to upload my project to Apple for tvOS, I encounter the following error:

```
Asset validation failed
Missing Info.plist value. A value for the key 'MinimumOSVersion' in the bundle MyApp-tvOS.app/Frameworks/hermes.framework is required.
```

```
Asset validation failed
Invalid Bundle. The MyApp-tvOS.app/Frameworks/hermes.framework bundle does not support the specified minimum OS version in the Info.plist.
```

Once again, thank you for your valuable assistance and promptness.-

Best regards,
Rodolphe

**Comment by douglowder** [comment]
I've reproduced the error you are seeing, it seems to be exactly the issue described in https://github.com/facebook/react-native/issues/36120 .

There are some commented out lines in `ReactCommon.podspec` that seem to have been intended to fix this behavior -- uncommenting them gets past the error you see but introduces other problems.

Unfortunately I don't have a solution for this yet.

**Comment by YoucefBen47** [comment]
@CodingByJerez  Hi,
We are facing the same issue after installing @react-native-firebase app and auth. I read that you managed to successfully run the app is that right ? If yes can you tell me how you solved the multiple command produce issue ?

**Comment by YoucefBen47** [comment]
@CodingByJerez Hi and thank you for replying,
By ` you need to use the maximum version 14.12.0.` Do you mean @react-native-firebase/app and @react-native-firebase/auth version 14.12.0 ? Because I just tested that and still getting the same errors.

**Comment by CodingByJerez** [comment]
@YoucefBen47 for both, what error do you get?

**Comment by YoucefBen47** [comment]
@CodingByJerez I appreciate your help. I get these two errors when I don't add ` use_frameworks! :linkage => :static`. The app builds and works fine but if I try to use auth I get the errors in the attached screenshots even after making the changes you suggested.
<img width="1258" alt="Screenshot 2023-07-31 at 6 06 24 PM" src="https://github.com/react-native-tvos/react-native-tvos/assets/70854871/1bc53139-48de-434c-8497-b3a8db8e77f7">
<img width="1260" alt="Screenshot 2023-07-31 at 6 07 19 PM" src="https://github.com/react-native-tvos/react-native-tvos/assets/70854871/82fad4e9-0b01-42a2-a102-8484ef47ead1">

**Comment by YoucefBen47** [comment]
@CodingByJerez Thank you so much you are a saviour.  After adding `s.tvos.deployment_target = "11.0"` to `@react-native-firebase/app` the test app built successfuly and seems to be working. 
I appreciate your help.
