### ISSUE TITLE
Shifting the focus from Drawer to Contents

### ISSUE THREAD

**Issue by mayur199816** [react-native-tvos/react-native-tvos#528]
### Description

<img width="717" alt="Screenshot 2023-06-21 at 8 59 46 PM" src="https://github.com/react-native-tvos/react-native-tvos/assets/67521143/89d145f8-36c4-4649-97f8-5092a8bac24b">

Hi,

The above displayed image shows the structure of app. Not able to shift the focus from drawer to right side where contents is displayed.

### Version

react-native-tvos@0.69.6-2

### Output of `npx react-native info`

System:
    OS: macOS 12.6.5
    CPU: (10) x64 Apple M1 Pro
    Memory: 21.58 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - /var/folders/2r/3s4c6fmn11xffbb92xy9wv0m0000gn/T/yarn--1687361865461-0.1507113197218799/node
    Yarn: 1.22.19 - /var/folders/2r/3s4c6fmn11xffbb92xy9wv0m0000gn/T/yarn--1687361865461-0.1507113197218799/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
    Watchman: 2022.12.12.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.69.6-2 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Attached a image for clear understanding

### Snack, code example, screenshot, or link to a repository

..

**Comment by wouterds** [comment]
Are you making use of `TVFocusGuideView`? This component helps you with that. There's some documentation about it on the README but @yusufyildirim also wrote an article about TV focus recently that might help you out. https://medium.com/xite-engineering/revolutionizing-focus-management-in-tv-applications-with-react-native-10ba69bd90
