### ISSUE TITLE
(Android TV) Seeker Disappears and won't come back

### ISSUE THREAD

**Issue by redreceipt** [react-native-tvos/react-native-tvos#529]
### Description

I apologize if this is a duplicate. And I'm sure I won't use the correct technical language. But initially the seeker bar shows up. But when it fades out, the buttons on the Chromecast don't bring it back up so it can't be scrolled. We are using `react-native-video`.

### Version

0.68.2-7

### Output of `npx react-native info`

```
tv % npx react-native info                                                                                                                         (chore-user-settings-migration) apollos-platforms 
warn Package @sentry/react-native contains invalid configuration: "dependency.platforms.ios.sharedLibraries" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
error Failed to load configuration of your project.
info Run CLI with --verbose flag for more details.
```

### Steps to reproduce

- Play a video (using `react-native-video`)
- The seeker is there initially, and then it fades out and it won't come back

### Snack, code example, screenshot, or link to a repository

<img width="1501" alt="Screenshot 2023-06-21 at 4 50 24 PM" src="https://github.com/react-native-tvos/react-native-tvos/assets/2659478/f06e5d6c-3dd3-4ed8-b5a0-0ec1c2c670f7">

**Comment by douglowder** [comment]
- This is very likely an issue with `react-native-video`, not with React Native itself.
- We would ask that you reproduce this with the latest releases (react-native-tvos@0.71.11-0, react-native-video@5.2.1).
- If the issue still occurs, please provide a sample project that shows the issue.
