### ISSUE TITLE
UIKeyboardDidShowNotification' is unavailable: not available on tvOS error in react-native-safe-area-context after React Native update

### ISSUE THREAD

**Issue by mansilaad19** [react-native-tvos/react-native-tvos#536]
### New Version

0.71.11

### Old Version

0.69.8-2

### Build Target(s)

tvOS 16.3.2(20K672),  Apple TV 4K (2nd generation)

### Output of `react-native info`

OS: macOS 13.4.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 137.16 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.71.11-0 
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

Hello everyone,

I recently updated my React Native version from 0.69.8-2 to 0.71.11 and started encountering an error that I haven't been able to resolve. The error message is: 

`'UIKeyboardDidShowNotification' is unavailable: not available on tvOS`

This error is coming from the `react-native-safe-area-context` package and it's preventing me from building my project in Xcode. 

Here's the exact error message:

```
/repo/node_modules/react-native-safe-area-context/ios/RNCSafeAreaProvider.m:18:53 'UIKeyboardDidShowNotification' is unavailable: not available on tvOS
```

I've tried searching for solutions online but haven't found any discussions specifically related to this error. I'm hoping someone here might have encountered this issue before and can provide some guidance.

Here are some details about my environment:

- React Native version: 0.71.11
- react-native-safe-area-context version: (4.6.4)
- Xcode version: (Version 14.3.1 (14E300c))
- Targeted platform: tvOS

Any help would be greatly appreciated. Thank you in advance!

**Comment by douglowder** [comment]
This needs to be fixed in https://github.com/th3rdwave/react-native-safe-area-context .

The fix is to update their podspec to require tvOS 12.4 minimum version, as in this patch:

https://github.com/react-native-tvos/TVReanimated/blob/main/patches/react-native-safe-area-context%2B4.5.3.patch

**Comment by douglowder** [comment]
Update @mansilaad19 -- it looks like they have just applied a different fix to the issue and published 4.7.0 -- so you can upgrade to that for now. I'll work with them to make sure there are no other adjustments needed.

**Comment by douglowder** [comment]
@mansilaad19 their fixes look good. If you are enabling Fabric, you will need an additional patch. I have submitted a PR to fix that: https://github.com/th3rdwave/react-native-safe-area-context/pull/415

**Comment by mansilaad19** [comment]
Thank You @douglowder
