### ISSUE TITLE
ScrollView Moving to initial position and then coming to the position required  if we are using scrollTo.

### ISSUE THREAD

**Issue by aniketgupta8960** [react-native-tvos/react-native-tvos#542]
### Description

We are using scrollview and needed to focus on some Item in the scrollView. We have used scrollTo to move scrollView to a position and made animation to true. But when the scrollTo is working first it is moving to the initial position and then coming to the position required. Working fine on Apple tv but causing issue in Android tv

### Version

0.68.2-2

### Output of `npx react-native info`

System:
    OS: macOS 13.4.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 185.94 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Watchman: 2023.06.26.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.2-2 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Add few touchable inside a scrollview and try to move scrollview using scrollTo 

### Snack, code example, screenshot, or link to a repository

NA
[Uploading testing.webm…]()

**Comment by douglowder** [comment]
You might try doing the scrollTo within a setTimeout. See related issue https://github.com/facebook/react-native/issues/6849#issuecomment-225124536

**Comment by matias-sandell** [comment]
Also, if you're not already doing it, you might try setting `scrollEnabled={false}` on the scrollView to disable the default Android scrolling behaviour (since you're doing it imperatively with scrollTo(). I had some really jittery scrolling experiences when using scrollToIndex() and scrollEnabled=true at the same time.
