### ISSUE TITLE
How to focus only on the button on a Modal and do not focus on button in background.

### ISSUE THREAD

**Issue by aniketgupta8960** [react-native-tvos/react-native-tvos#543]
### Description

I have a dropdown which I have created using flatlist. I want that when the dropdown is open the focus should move only inside the dropdown and it should not go on the button in the bakground.I have made this work in AppleTv and it is working fine in Apple Tv but in Android tv the focus moves out of the dropDown on the button in the background.

### Version

0.68.2-2

### Output of `npx react-native info`

System:
    OS: macOS 13.4.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 34.63 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Watchman: 2023.06.26.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.2-2 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create a dropdown using flalist then the open it then focus goes back to background button

### Snack, code example, screenshot, or link to a repository

https://github.com/react-native-tvos/react-native-tvos/assets/74759255/be40235a-386e-47f0-b4a0-03db8a1ffa99

**Comment by aniketgupta8960** [comment]
@douglowder  Can you please help me with the solution for above focus issue

**Comment by douglowder** [comment]
@aniketgupta8960 you should probably move to 0.71.11-0 (or at least 0.69.8-2) to get this fix: https://github.com/react-native-tvos/react-native-tvos/pull/465

@yusufyildirim is there anything special that needs to be done for handling focus inside a modal on Android?
