### ISSUE TITLE
Hermes Enabled for Android TV, Encountering DSO Error Upon Release

### ISSUE THREAD

**Issue by akbari6776** [react-native-tvos/react-native-tvos#549]
### Description

When I enabled Hermes for my Android TV project, it worked only for the debug version. However, when I generated the release version and installed it, the app crashed at startup. I retrieved the crash log from Logcat, and it indicated an error related to "couldn't find DSO to load: libjscexecutor.so".

### Version

0.69.6-0

### Output of `npx react-native info`

System:
    OS: macOS 13.0
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 157.14 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
    Watchman: 2023.03.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 24, 25, 28, 29, 30, 31, 32, 33, 33, 33
      Build Tools: 28.0.2, 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 33.0.2
      System Images: android-28 | Android TV Intel x86 Atom, android-28 | China version of Wear OS Intel x86 Atom, android-28 | Wear OS Intel x86 Atom, android-28 | ARM 64 v8a, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs ARM 64 v8a, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google ARM64-V8a Play ARM 64 v8a, android-28 | Google Play Intel x86 Atom, android-29 | ARM 64 v8a, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Android TV Intel x86 Atom, android-30 | China version of Wear OS 3 - Preview Intel x86 Atom, android-30 | Wear OS 3 - Preview Intel x86 Atom, android-30 | ARM 64 v8a, android-30 | Intel x86 Atom_64, android-30 | Google TV Intel x86 Atom, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64, android-31 | Android TV Intel x86 Atom, android-31 | ARM 64 v8a, android-31 | Intel x86 Atom_64, android-31 | Google TV Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google APIs Intel x86 Atom_64, android-32 | Google Play ARM 64 v8a, android-32 | Google Play Intel x86 Atom_64, android-33-ext4 | Google Play ARM 64 v8a, android-33-ext4 | Google Play Intel x86_64 Atom, android-33-ext5 | Google Play ARM 64 v8a, android-33-ext5 | Google Play Intel x86_64 Atom, android-33 | Google APIs ARM 64 v8a, android-33 | Google APIs Intel x86_64 Atom, android-33 | Google Play ARM 64 v8a, android-33 | Google Play Intel x86_64 Atom, android-TiramisuPrivacySandbox | Google Play ARM 64 v8a, android-TiramisuPrivacySandbox | Google Play Intel x86_64 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.69.6-0 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Many steps i tried, but nothing happen

### Snack, code example, screenshot, or link to a repository

![Screenshot 2023-07-23 at 17 29 25](https://github.com/react-native-tvos/react-native-tvos/assets/42941890/d85dde06-6c0a-4adb-9283-ca120e6042f9)

**Comment by douglowder** [comment]
Fixed in 0.69.8-2 and all 0.71 releases

**Comment by akbari6776** [comment]
> Fixed in 0.69.8-2 and all 0.71 releases

Its not fix on 0.69.8-2 

![Screenshot 2023-07-26 at 11 24 57](https://github.com/react-native-tvos/react-native-tvos/assets/42941890/12654910-4f0a-4764-a4fe-aba42613ed3a)
![Screenshot 2023-07-26 at 11 25 26](https://github.com/react-native-tvos/react-native-tvos/assets/42941890/ed9e14ef-5a8f-4105-9a6b-5cbe5b561883)
