### ISSUE TITLE
React Native TVOS fails to build after installing firebase !!

### ISSUE THREAD

**Issue by YoucefBen47** [react-native-tvos/react-native-tvos#551]
### Description

We are using firebase authentication in our app. It works fine across all the platforms however when we tried to set up TVOS it fails to build after adding   `use_frameworks! :linkage => :static` and `$RNFirebaseAsStaticFramework = true` to the podfile.
The image attached shows the error we are seeing.
Is @react-native-firebase/auth supported on tv os ?

### Version

npm:react-native-tvos@0.71.12-0

### Output of `npx react-native info`

System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 966.19 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.8.0 - /opt/homebrew/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.71.12-0 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Created a new project using: npx react-native init FliikaTVTest --template=react-native-tvos@latest.
2. Used yarn add @react-native-firebase/app and yarn add @react-native-firebase/auth to install firebase.
3. Added  `use_frameworks! :linkage => :static` and `$RNFirebaseAsStaticFramework = true` and ` pod 'GoogleUtilities', :modular_headers => true` to podfile.
4. ran pod install --repo-update.

### Snack, code example, screenshot, or link to a repository

<img width="1404" alt="Screenshot 2023-07-30 at 6 04 25 PM" src="https://github.com/react-native-tvos/react-native-tvos/assets/70854871/3e878364-d8e3-428b-9873-8012dfbc7866">

**Comment by douglowder** [comment]
I think this is the same issue as #517 . I'll take a look to see if there is anything Firebase-specific, and thanks very much for the repro steps!

**Comment by YoucefBen47** [comment]
@douglowder Thank you for responding quickly. I have asked the dev who opened the issue you mentioned to see how he managed to run his app successfully. Hopefully this issue will be solved soon. Just to confirm tvos does support firebase authentication right ? Because I was trying some stuff and after adding `pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'` we got the error in the screenshot attached.
<img width="1440" alt="Screenshot 2023-07-27 at 1 55 03 PM" src="https://github.com/react-native-tvos/react-native-tvos/assets/70854871/dda27ebd-b025-4ba6-b8e8-cc48b8c854ca">

**Comment by douglowder** [comment]
I suspect that the solution to this is to add the tvOS platform to the Firebase podspec, as described in https://github.com/react-native-tvos/react-native-tvos/issues/517#issuecomment-1658939160 . If this is not the issue, please comment here and I can reopen.

**Comment by sunzongzheng** [comment]
I also encountered this problem
All I did was:
1. Create a project according to the documentation
2. Add `use_frameworks` in Podfile

Have you solved this problem? @YoucefBen47
