### ISSUE TITLE
Cannot install app on real tvOS device

### ISSUE THREAD

**Issue by istvan-szilagyi** [react-native-tvos/react-native-tvos#564]
### New Version

71.11-0

### Old Version

69.6-3

### Build Target(s)

Apple TV - Debug (Real device)

### Output of `react-native info`

System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 100.69 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/szilagyiistvan/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.71.11-0 
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

After we update from 69.6-3 to 71.11-0 we noticed that we cannot run the app anymore on a real Apple TV device. For iOS it is still everything fine. We are receiving this:

<img width="295" alt="Screenshot 2023-08-24 at 10 41 33" src="https://github.com/react-native-tvos/react-native-tvos/assets/21306972/b92ab4b2-f4e6-480f-8ecf-acbb5802134b">

Details:

<img width="1724" alt="Screenshot 2023-08-24 at 10 43 00 (1)" src="https://github.com/react-native-tvos/react-native-tvos/assets/21306972/36161a1b-cd51-47e6-9f36-5182055a19b8">

The app actually installs, or at least the icon appears on the TV but if we try to launch it manually we see a message that:
"Failed to install - App integrity could not be verified"

Usually same message is displayed whenever the provisioning profile expires, but ours is not expired. I also tried to revoke and re-create it but same result. And I'm pretty sure that it's because this update, because if I reverted the code where we still had the older version of react-native-tvos (69.6-3) I was able to run it.

**Comment by douglowder** [comment]
Normally I would only expect this error when using a free (not paid) Apple developer account. I'll see if I can reproduce it. I was able to install and run apps on a real Apple TV with the 0.71 releases, and had no issues.

**Comment by zsoltbokor3ssprx** [comment]
After we turned off the Hermes on ios/tvos everything works fine again.

**Comment by douglowder** [comment]
See if turning off Bitcode generation in the release build fixes the issue.
