### ISSUE TITLE
Perf regression between RN 0.69 and later versions

### ISSUE THREAD

**Issue by douglowder** [react-native-tvos/react-native-tvos#570]
### Description

Creating this issue to track the work happening in core around a regression in performance (frame rate) seen in all versions of React Native since 0.69.

Core issue link: https://github.com/facebook/react-native/issues/36296

One of the first tasks for this will be to take this repro project and try to make it work on TV if possible (hopefully we can at least make Android TV work with this): https://github.com/tj-mc/rn-perf-repro

### React Native Version

0.72.4

### Output of `npx react-native info`

{
  "name": "perf",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "17.0.2",
    "react-native": "0.68.7"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.67.0",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}

### Steps to reproduce

Take the example repo and upgrade to RN 0.72.x

### Snack, code example, screenshot, or link to a repository

https://github.com/tj-mc/rn-perf-repro

**Comment by tj-mc** [comment]
Awesome 👏 PRs welcome if you need extend the Repro with anything specific needed for tvOS 😀

**Comment by douglowder** [comment]
@tj-mc the repro runs on Apple TV and Android TV now using the 0.69.8-0 release of this repo:

https://github.com/douglowder/rn-perf-repro/tree/tv-69

I'll also create a branch for 0.72 for comparison.

Hopefully whatever fixes eventually come from core will just merge cleanly here -- most of the changes here are for input and focus handling, not rendering. If there are Hermes changes, I'll merge those into the Hermes TV repo as well.

**Comment by douglowder** [comment]
Interesting, on Android TV I get a console warning "Excessive number of pending callbacks", will have to see what that is :)

**Comment by freeboub** [comment]
> Interesting, on Android TV I get a console warning "Excessive number of pending callbacks", will have to see what that is :)
> 

I also had this issue sometimes during development. I was doing too many updates during the long press. (I am still using react native, but once I will use this repo). So the issue was in my app...

And thank you for sharing this important ticket !

**Comment by douglowder** [comment]
This has been fixed in core. See https://github.com/facebook/react-native/issues/36296#issuecomment-1721832276
