### ISSUE TITLE
isTVSelectable and focusable not working on TVFocusGuideView

### ISSUE THREAD

**Issue by lcaprini** [react-native-tvos/react-native-tvos#572]
### Description

In some cases I need to disable the spatial navigation at all, for example when a user enters in a specific view that needs some data from an API i,n order to became usable by the user itself.

I tried to set `focusable` and/or `isTvSelectable` to false on the `TVFocusGuide` that wraps the entire view, but the button inside it (a `Pressable` component) receive the focus; if I set the `isTvSelectable` also on the `Pressable`, all works correctly.

Otherwise, there is some react native trick to completely disable the spatial navigation (maybe using some native platform API)?

Thank you for your job
--Luca

### React Native Version

0.71.12-0

### Output of `npx react-native info`

System:
    OS: macOS 13.5
    CPU: (12) arm64 Apple M2 Pro
    Memory: 76.31 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: Not Found
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/lcapriniw1/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.20 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.71.12-0 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Simply wrap a `Pressable` button with a `TvFocusGuide` component and disable it.

### Snack, code example, screenshot, or link to a repository

```typescript 
const Pairing = (): JSX.Element => {
  const navigation = useNavigation();

  return (
    <TVFocusGuideView
      autoFocus
      focusable={false}
      isTVSelectable={false}
      style={{ flex: 1, backgroundColor: Theme.colors.BACKGROUND_COLOR }}
    >
      <Text style={{ color: 'white', fontSize: 32, marginBottom: 64 }}> PAIRING </Text>
      <Button
        title="Login with email and password"
        onPress={() => {
          navigation.navigate(Screens.Login);
        }}
      ></Button>
    </TVFocusGuideView>
  );
};

const Button = ({
  title,
  onPress,
  disabled,
}: ButtonProps): JSX.Element => {
  // simple hook that manages the isFocused state
  const { ref, isFocused, onFocus, onBlur } = useFocusable();

  return (
    <Pressable
      isTVSelectable={!disabled}
      onPress={onPress}
      onFocus={onFocus}
      onBlur={onBlur}
      ref={ref}
    >
      <Text>
        {title}
      </Text>
    </Pressable>
  );
};
```

**Comment by fredrifoUni** [comment]
Thank you for reporting this bug! I am experiencing the same issue on `react-native-tvos@0.72.4-0`

**Comment by douglowder** [comment]
You should set `disabled` on the `Pressable`, not on the focus guide. The focus guide does not receive focus itself.

**Comment by lcaprini** [comment]
If I set the `disabled` on the `Pressable` it works correctly, but I have some complex components with a lot of `Pressable` (like a screen keyboard) and change the `disabled` prop on all of them could be less readable compared to set only the `isTVSelectable` to the `TVFocusGuideView`.

By the way, what is the intended use for the`isTVSelectable` prop on `TVFocusGuideView`?

**Comment by douglowder** [comment]
@lcaprini all views have the `isTVSelectable` prop. Only views that can receive focus should have that set to true.
