### ISSUE TITLE
Create many environment for my app in react native tvos

### ISSUE THREAD

**Issue by tronghieu60s** [react-native-tvos/react-native-tvos#577]
### Description

I want to setup many environment (example: development, staging, production).
I did following this blog: https://dev.to/leon_arantes/react-native-multiple-environments-setup-schemaflavors-3l7p

But i have a issuse, i want to run with suffix
Example:
 - development: com.tvos.dev
 - staging: com.tvos.staging
 - production: com.tvos

When call "npm run android", it run "expo run:android", i want to add suffix for this command but tag "--appIdSuffix=tag" not working. It just working if i using "react-native run-android --appIdSuffix=tag".

How can i do?

### React Native Version

0.74.0

### Output of `npx react-native info`

no

### Steps to reproduce

no

### Snack, code example, screenshot, or link to a repository

no

**Comment by zubyrbutt** [comment]
I've also had this issue, and I follow this example project for the environment.
[https://github.com/wouterds/react-native-tv-example](url)

**Comment by tronghieu60s** [comment]
> I've also had this issue, and I follow this example project for the environment. [https://github.com/wouterds/react-native-tv-example](url)

thank you, i think i should using this template for my project
