### ISSUE TITLE
Playing youtube on tvos is next to impossible because there is no webviews on tvos

### ISSUE THREAD

**Issue by absmugz** [react-native-tvos/react-native-tvos#581]
### Description

Playing youtube on tvos is next to impossible because there is no webviews on tvos

### React Native Version

0.73.x

### Output of `npx react-native info`

npx react-native

### Steps to reproduce

Add youtube player and try running tvos

### Snack, code example, screenshot, or link to a repository

https://www.npmjs.com/package/react-native-youtube

**Comment by douglowder** [comment]
That is correct. The only way to do this would be to do something like what the `pytube` Python package does, which is to identify an itag for an MP4 stream and pass that to a video player.
