### ISSUE TITLE
`useTVEventHandler()` on Android TV - only works if focusables are present, or is inside ScrollView

### ISSUE THREAD

**Issue by douglowder** [react-native-tvos/react-native-tvos#584]
### Description

@nguyvan reports a bug where the code below works correctly on Apple TV, but no events are observed on Android TV. Debugging showed that events are sent as expected if the `Text` component is placed inside a `ScrollView`.

This issue is reproducible on apps using RNTV 0.71 and 0.72 releases.

```tsx
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 */

import React from 'react';
import type {PropsWithChildren} from 'react';
import {
  HWEvent,
  Text,
  useTVEventHandler,
  SafeAreaView,
} from 'react-native';

const EventView = () => {
  const [lastEventType, setLastEventType] = React.useState('none');
  const myTVEventHandler = 
    (evt: HWEvent) => {
      console.log(evt);
      setLastEventType(evt.eventType);
    };
  useTVEventHandler(myTVEventHandler);
  return (
    <SafeAreaView style={{flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'white'}} >
      <Text style={{color: 'blue'}}>{lastEventType}</Text>
    </SafeAreaView>
  );
};

const App = () => {
  return (
    <EventView />
  );
};

export default App;
```

### React Native Version

0.72.5-0

### Output of `npx react-native info`

See above

### Steps to reproduce

See above

### Snack, code example, screenshot, or link to a repository

See above

**Comment by douglowder** [comment]
Investigated this more, and it seems that if any focusable control is present (e.g. a `Pressable`), then events show up as expected.

I no longer believe this to be a regression, but may just be the way things work in Android itself or in the RN Android implementation. Since no views are present that can respond to the events, the system optimizes them out.

**Comment by douglowder** [comment]
In the example app above, we can restore the events by setting `focusable={true}` on the `SafeAreaView`. This might be an ok workaround for the issue in an app that has no focusables and just wants to handle the events by directly using a TVEventHandler. @nguyvan @yusufyildirim

**Comment by yusufyildirim** [comment]
@douglowder You're right. . When a `KeyEvent` is generated, that event is dispatched through the view hierarchy until reaching out to the `currently focused` element. If there's no focus, that callback won't be triggered technically speaking.  So, it's related to our implementation. We should rely on Activity's `onKeyUp` and `onKeyDown` events instead if we want to capture and dispatch every key event.

**Comment by yusufyildirim** [comment]
@douglowder Okay, I might have talked a bit more certain than I should 😄  Did some extra research and found that the behavior is not super clearly defined. Currently focused element has the priority, that's for sure but how everything works it there's nothing focused on the screen is a bit of mystery. We can assume some stuff based on your findings. Anyway, `onKeyUp` and `onKeyDown` are safer bets nevertheless.

**Comment by douglowder** [comment]
@yusufyildirim since very few apps will meet the conditions for reproducing the issue, and there is an easy workaround, we can either close this, or move it to the "Feature Request" list in discussions for doing the Activity level work. What do you think?
