### ISSUE TITLE
Apple TV remote touch pad not working when build with Xcode 15, but working fine when building with Xcode 14.3.1

### ISSUE THREAD

**Issue by mehthabux** [react-native-tvos/react-native-tvos#595]
### Description

I have recently updated my machine, so I had to install Xcode 15. But when I tried to use the touchpad on Apple TV remote. I noticed that the touchpad is getting hanged at the input keyboard and unable to move further.

But I can confirm this issue does not happen in Xcode 14.3.1, I ran the same project on my old machine. it's working fine [there[](url)](url)

### React Native Version

npm:react-native-tvos@0.72.6-0

### Output of `npx react-native info`

System:
  OS: macOS 14.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 483.08 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.2
    path: /opt/homebrew/opt/node@18/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.8.1
    path: /opt/homebrew/opt/node@18/bin/npm
  Watchman:
    version: 2023.10.23.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.2
    path: /Users/mehthabmusambil/.rvm/gems/ruby-2.7.4/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.21
    path: /usr/bin/javac
  Ruby:
    version: 2.7.4
    path: /Users/mehthabmusambil/.rvm/rubies/ruby-2.7.4/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.72.6-0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

Try to build the tv app in Xcode 15
<img width="530" alt="Screenshot 2023-11-05 at 12 54 14 PM" src="https://github.com/react-native-tvos/react-native-tvos/assets/69464250/8eae9045-a7c0-4f69-8ff2-7b71c2ea2ff7">

**Comment by douglowder** [comment]
Interesting... I just built a demo app with text inputs using RNTV 0.72.6-0 and do not see an issue on the Apple TV simulator. I'm running Xcode 15.0. Maybe 15.0.1 changed some behavior in the simulator. I'll do further testing, but not sure I can help with this.

**Comment by mehthabux** [comment]
@douglowder . Could you please check in physical device 
thank you

**Comment by misha-belokon** [comment]
Same here, Xcode 15+, reproduces only on physical Apple TV. Xcode 14 works fine. It can be reproduced using the attached code snippet, press on buttons, and at some point focus will get stuck on one of them

```js
import React, {useState} from 'react';
import {Text, TouchableHighlight, View} from 'react-native';

const Button = ({color = 'red', setColor, currentColor}) => {
  return (
    <TouchableHighlight
      onPress={() => setColor(color)}
      style={[
        {
          backgroundColor: 'black',
          marginBottom: 20,
          borderRadius: 5,
          paddingLeft: 40,
        },
      ]}
      underlayColor={'grey'}>
      <Text style={{color: 'white', fontSize: 36}}>
        {color} {color === currentColor ? '  V' : ''}
      </Text>
    </TouchableHighlight>
  );
};

const App: () => React.ReactElement = () => {
  const [color, setColor] = useState('black');
  return (
    <View style={{flex: 1, backgroundColor: color, paddingHorizontal: 240}}>
      <Button currentColor={color} color="red" setColor={setColor} />
      <Button currentColor={color} color="green" setColor={setColor} />
      <Button currentColor={color} color="blue" setColor={setColor} />
      <Button currentColor={color} color="purple" setColor={setColor} />
      <Button currentColor={color} color="orange" setColor={setColor} />
      <Button currentColor={color} color="yellow" setColor={setColor} />
      <Button currentColor={color} color="grey" setColor={setColor} />
      <Button currentColor={color} color="silver" setColor={setColor} />
    </View>
  );
};

export default App;
```

**Comment by douglowder** [comment]
Test on a real device. I found two things:

- The problem is reproducible on a real device if building a release build
- If I instead do a debug build (but force building main.jsbundle and don't use packager), then the application works correctly on the real device.

So there is some issue with Xcode 15, specifically regarding release builds. Will continue testing this.

**Comment by douglowder** [comment]
I'm also looking at this note in the tvOS 17 changelog from Apple, which calls out some changes in the default behavior of gesture recognizers.

https://developer.apple.com/documentation/tvos-release-notes/tvos-17-release-notes#UIKit

**Comment by mehthabux** [comment]
Thank you @douglowder for checking it out

**Comment by douglowder** [comment]
@misha-belokon @mehthabux could you try out the patch in #601 for non-Fabric apps, and see if that fixes the issue for you? It does appear to work for me with a tvOS 17.1 device.

**Comment by misha-belokon** [comment]
@douglowder Thank you! I can confirm that the provided patch fixes the issue for me. Xcode 15.0.1, tvOS 17.1
