### ISSUE TITLE
Can't build tvOS app with the new architecture

### ISSUE THREAD

**Issue by sehyod** [react-native-tvos/react-native-tvos#599]
### Description

Hello, I'm very new to React Native development and I'm trying to familiarise myself with Fabric Native components.
After following the [tutorial](https://reactnative.dev/docs/the-new-architecture/pillars-fabric-components?fabric-component-specs=typescript) from react native website, everything works as expected when running the iOS app, but the build fails for tvOS, with the following error: `Undefined symbol: _RTNCenteredTextCls`

I would like to know, if there are any known issues when working with the new architecture for tvOS apps, or if I did something wrong here

### React Native Version

0.72.6

### Output of `npx react-native info`

System:
  OS: macOS 14.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 123.89 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.1.0
    path: /var/folders/qk/34qbn1pd3c7_f9t_hctq1blm0000gn/T/yarn--1699441459863-0.44091798545658323/node
  Yarn:
    version: 1.22.19
    path: /var/folders/qk/34qbn1pd3c7_f9t_hctq1blm0000gn/T/yarn--1699441459863-0.44091798545658323/yarn
  npm:
    version: 9.6.4
    path: ~/.nvm/versions/node/v20.1.0/bin/npm
  Watchman:
    version: 2023.10.09.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /opt/homebrew/opt/ruby/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 3.2.2
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.72.6-0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true

### Steps to reproduce

- Create an app with `react-native init TestApp --template=react-native-template-typescript-tv`
- Change react-native-tvos version to `npm:react-native-tvos@^0.72.6-0`, remove `node_modules` and run `yarn`
- Follow instructions to create an iOS native component at https://reactnative.dev/docs/the-new-architecture/pillars-fabric-components?fabric-component-specs=typescript
  - Create RTNCenteredText/ios/{RTNCenteredText.h, RTNCenteredText.mm, RTNCenteredTextManager.mm}, RTNCenteredText/js/RTNCenteredTextNativeComponent.tsx, RTNCenteredText/package.json and RTNCenteredText/rtn-centered-text.podspec by copying the content from the tutorial
  - Run `node TestApp/node_modules/react-native/scripts/generate-codegen-artifacts.js --path TestApp/ --outputPath RTNCenteredText/generated/`
  - in `TestApp`, run `yarn add ../RTNCenteredText` then `cd ios && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install`
- Update the app's Podfile to set :fabric_enabled to true in both regular and tvOS targets
- Add the native component in the app
- Open `TestApp.xcworkspace` in xcode
- Select the iOS target and run: everything works
- Select the tvOS target and run: the build fails
<img width="262" alt="image" src="https://github.com/react-native-tvos/react-native-tvos/assets/58954208/c4d0e277-c32e-433d-9a2a-692063e50ad5">

### Snack, code example, screenshot, or link to a repository

TestApp/App.tsx:
```tsx
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 */
import React from 'react';
import RTNCenteredText from 'rtn-centered-text/js/RTNCenteredTextNativeComponent';

const App: () => JSX.Element = () => {
  return (
    <RTNCenteredText text="Hello World!" style={{width: '100%', height: 30}} />
  );
};
export default App;
```

RTNCenteredText/ios/RTNCenteredText.h:
```objective-c
#import <React/RCTViewComponentView.h>
#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface RTNCenteredText : RCTViewComponentView

@end

NS_ASSUME_NONNULL_END
```

RTNCenteredText/ios/RTNCenteredText.mm:
```objective-c
#import "RTNCenteredText.h"

#import <react/renderer/components/RTNCenteredTextSpecs/ComponentDescriptors.h>
#import <react/renderer/components/RTNCenteredTextSpecs/EventEmitters.h>
#import <react/renderer/components/RTNCenteredTextSpecs/Props.h>
#import <react/renderer/components/RTNCenteredTextSpecs/RCTComponentViewHelpers.h>

#import "RCTFabricComponentsPlugins.h"

using namespace facebook::react;

@interface RTNCenteredText () <RCTRTNCenteredTextViewProtocol>
@end

@implementation RTNCenteredText {
  UIView *_view;
  UILabel *_label;
}

+ (ComponentDescriptorProvider)componentDescriptorProvider
{
  return concreteComponentDescriptorProvider<RTNCenteredTextComponentDescriptor>();
}

- (instancetype)initWithFrame:(CGRect)frame
{
  if (self = [super initWithFrame:frame]) {
    static const auto defaultProps = std::make_shared<const RTNCenteredTextProps>();
    _props = defaultProps;

    _view = [[UIView alloc] init];
    _view.backgroundColor = [UIColor redColor];

    _label = [[UILabel alloc] init];
    _label.text = @"Initial value";
    [_view addSubview:_label];

    _label.translatesAutoresizingMaskIntoConstraints = false;
    [NSLayoutConstraint activateConstraints:@[
      [_label.leadingAnchor constraintEqualToAnchor:_view.leadingAnchor],
      [_label.topAnchor constraintEqualToAnchor:_view.topAnchor],
      [_label.trailingAnchor constraintEqualToAnchor:_view.trailingAnchor],
      [_label.bottomAnchor constraintEqualToAnchor:_view.bottomAnchor],
    ]];

    _label.textAlignment = NSTextAlignmentCenter;

    self.contentView = _view;
  }

  return self;
}

- (void)updateProps:(Props::Shared const &)props oldProps:(Props::Shared const &)oldProps
{
  const auto &oldViewProps = *std::static_pointer_cast<RTNCenteredTextProps const>(_props);
  const auto &newViewProps = *std::static_pointer_cast<RTNCenteredTextProps const>(props);

  if (oldViewProps.text != newViewProps.text) {
    _label.text = [[NSString alloc] initWithCString:newViewProps.text.c_str() encoding:NSASCIIStringEncoding];
  }

  [super updateProps:props oldProps:oldProps];
}

@end

Class<RCTComponentViewProtocol> RTNCenteredTextCls(void)
{
  return RTNCenteredText.class;
}
```

RTNCenteredText/ios/RTNCenteredTextManager.mm:
```objective-c
#import <React/RCTLog.h>
#import <React/RCTUIManager.h>
#import <React/RCTViewManager.h>

@interface RTNCenteredTextManager : RCTViewManager
@end

@implementation RTNCenteredTextManager

RCT_EXPORT_MODULE(RTNCenteredText)

RCT_EXPORT_VIEW_PROPERTY(text, NSString)

@end
```

RTNCenteredText/js/RTNCenteredTextNativeComponent.tsx:
```typescript
import type { ViewProps } from "ViewPropTypes";
import type { HostComponent } from "react-native";
import codegenNativeComponent from "react-native/Libraries/Utilities/codegenNativeComponent";

export interface NativeProps extends ViewProps {
  text?: string;
  // add other props here
}

export default codegenNativeComponent<NativeProps>(
  "RTNCenteredText"
) as HostComponent<NativeProps>;
```

RTNCenteredText/package.json:
```json
{
  "name": "rtn-centered-text",
  "version": "0.0.1",
  "description": "Showcase a Fabric Native Component with a centered text",
  "react-native": "js/index",
  "source": "js/index",
  "files": [
    "js",
    "android",
    "ios",
    "rtn-centered-text.podspec",
    "!android/build",
    "!ios/build",
    "!**/__tests__",
    "!**/__fixtures__",
    "!**/__mocks__"
  ],
  "keywords": [
    "react-native",
    "ios",
    "android"
  ],
  "repository": "https://github.com/<your_github_handle>/rtn-centered-text",
  "author": "<Your Name> <your_email@your_provider.com> (https://github.com/<your_github_handle>)",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/<your_github_handle>/rtn-centered-text/issues"
  },
  "homepage": "https://github.com/<your_github_handle>/rtn-centered-text#readme",
  "devDependencies": {},
  "peerDependencies": {
    "react": "*",
    "react-native": "*"
  },
  "codegenConfig": {
    "name": "RTNCenteredTextSpecs",
    "type": "components",
    "jsSrcsDir": "js"
  }
}
```

RTNCenteredText/rtn-centered-text.podspec:
```podspec
require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name            = "rtn-centered-text"
  s.version         = package["version"]
  s.summary         = package["description"]
  s.description     = package["description"]
  s.homepage        = package["homepage"]
  s.license         = package["license"]
  s.platforms       = { :ios => "12.0" }
  s.author          = package["author"]
  s.source          = { :git => package["repository"], :tag => "#{s.version}" }

  s.source_files    = "ios/**/*.{h,m,mm,swift}"

  install_modules_dependencies(s)
end
```

**Comment by douglowder** [comment]
Your Xcode project will have two targets, `TestApp` (for phone) and `TestApp-tvOS` (for TV). Most likely explanation for your issue is that you added your new source files to the Xcode project, but only for the phone target. Check the files and make sure that they are included in both targets.

**Comment by sehyod** [comment]
Thank you for your answer. However, I haven't added any source files to the Xcode project. I believe adding files is necessary when using the legacy architecture. With the new architecture, the native code lives in another directory, then I add it to my app with `yarn add ../RTNCenteredText` (and then `RCT_NEW_ARCH_ENABLED=1 bundle exec pod install`). Am I missing any step here?

**Comment by sehyod** [comment]
Thank you for your answer @douglowder. However, I haven't added any source files to the Xcode project. I believe adding files is necessary when using the legacy architecture. With the new architecture, the native code lives in another directory, then I add it to my app with `yarn add ../RTNCenteredText` (and then `RCT_NEW_ARCH_ENABLED=1 bundle exec pod install`). Am I missing any step here?

**Comment by douglowder** [comment]
I see the problem... Change the generated podspec platforms line to 

```
s.platforms       = { :ios => "13.0", :tvos => "13.0"}
```

and run the pod install step again.

**Comment by sehyod** [comment]
I have finally found the solution, and it was very straight forward. My podspec file was the issue: I had written `s.platforms       = { :ios => "12.0" }`, blindly following the react native tutorial. But it should have been `s.platforms       = { :ios => "12.0", :tvos => "12.0" }` here

**Comment by sehyod** [comment]
I saw your reply after sending mine but I'm glad we reached the same conclusion! Thank you for your help 😄
