### ISSUE TITLE
Experiencing a crash when using TabBarIOS

### ISSUE THREAD

**Issue by prasad-gobburkar** [react-native-tvos/react-native-tvos#607]
### Description

Hi @douglowder,
I am experiencing a crash when using TabBarIOS in the latest version of React Native for tvOS; previously, it was working fine.

### React Native Version

 0.72.6

### Output of `npx react-native info`

System:
  OS: macOS 13.6.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 258.91 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.14.2
    path: ~/.nvm/versions/node/v16.14.2/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 8.5.0
    path: ~/.nvm/versions/node/v16.14.2/bin/npm
  Watchman:
    version: 2023.08.14.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.72.6-1
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false

### Steps to reproduce

import TabBarIOS component try to use it.

### Snack, screenshot, or link to a repository

<img width="859" alt="image" src="https://github.com/react-native-tvos/react-native-tvos/assets/48175590/26c9a3c5-be79-4db2-bf44-0df0d9575f8e">

**Comment by samsonroyquickplay** [comment]
@yusufyildirim Can you please help us here ?

**Comment by douglowder** [comment]
@samsonroyquickplay thanks for the heads up. I've merged #608 and cherry-picked to the 0.72 branch.
