### ISSUE TITLE
TVEventHandler doesn't work inside Modal

### ISSUE THREAD

**Issue by svbutko** [react-native-tvos/react-native-tvos#609]
### Description

Hello, recently I tried to use `TVEventHandler` inside react-native's `Modal` and stumbled upon a fact that `TVEventHandler` doesn't fire events inside of this `Modal`, is this correct behaviour?

Thank you.

### React Native Version

0.71.10-0

### Output of `npx react-native info`

OS: macOS 14.1.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 107.66 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    Watchman: 2023.11.20.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.11090377

### Steps to reproduce

1. Create `Modal` with `TVEventHandler` inside of it
2. Use remote buttons
3. Events are not registered in `TVEventHandler`'s callback

### Snack, screenshot, or link to a repository

```
import {
    Modal, TVEventHandler, View,
} from 'react-native';

export const TestModal = () => {
    return (
        <Modal visible>
            <KeyHandler />
            <View
                style={{
                    width: 100,
                    height: 100,
                }}
            />
        </Modal>
    );
};

class KeyHandler {
    _tvEventHandler;

    _enableTVEventHandler() {
        this._tvEventHandler = new TVEventHandler();
        this._tvEventHandler.enable(this, (cmp, evt) => {
            console.log('EVENT: ', evt);
        });
    }

    _disableTVEventHandler() {
        if (this._tvEventHandler) {
            this._tvEventHandler.disable();
            delete this._tvEventHandler;
        }
    }

    componentDidMount() {
        this._enableTVEventHandler();
    }

    componentWillUnmount() {
        this._disableTVEventHandler();
    }

    render() {
        return null;
    }
}
```

**Comment by svbutko** [comment]
Only `focus` and `blur` events are firing

**Comment by douglowder** [comment]
I'll test this out -- is this Android TV or Apple TV, or both?

**Comment by svbutko** [comment]
> I'll test this out -- is this Android TV or Apple TV, or both?

I tested on Android only (project doesn't have tvOS) but I will try it on tvOS this weekend

**Comment by douglowder** [comment]
This is probably related to #588

**Comment by douglowder** [comment]
@svbutko confirmed, this is the same issue as #588 . If you have at least one focusable view (like a Pressable or TouchableOpacity) in your modal, the event handler will work.

**Comment by svbutko** [comment]
@douglowder I did try it (together with the lattest version of react-native-tvos, 0.72.6-1) but unfortunately it doesn't work.

I have buttons (tried both `Pressable` and `TouchableOpacity`) and I tried both `useTVEventHandler` and `TVEventHandler`, the outcome still the same, only `focus` and `blur` events are firing.

I have a modal with the following props:

```
            <Modal
                visible={hasActiveOverlay}
                animationType="none"
                presentationStyle="overFullScreen"
                onRequestClose={onOverlayClosed}
                transparent
            >
```

**Comment by svbutko** [comment]
@douglowder I probably found why it TvEventHandler doesn't work with buttons in modals: it misses `dispatchKeyEvent` inside `ReactModalHostView`

I compared both files [ReactRootView](https://github.com/react-native-tvos/react-native-tvos/blob/6cbf47c2c963098e3a55d5be7ecc07aabb231107/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java) and [ReactModalHostView](https://github.com/react-native-tvos/react-native-tvos/blob/6cbf47c2c963098e3a55d5be7ecc07aabb231107/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/modal/ReactModalHostView.java)

And ReactModalHostView misses `dispatchKeyEvent`

I will try to do something with it soon!

**Comment by douglowder** [comment]
@svbutko thanks for your investigation! I took another look, and it appears that the code added to fix this originally in https://github.com/react-native-tvos/react-native-tvos/pull/219 has been refactored out. This really needs to be handled in the `onKey()` method. Reopening this and will try to get this fixed soon. @yusufyildirim

**Comment by douglowder** [comment]
I now have a fix, will post PR today.
