### ISSUE TITLE
How to use it in android tv?

### ISSUE THREAD

**Issue by huynhttdev** [react-native-tvos/react-native-tvos#616]
### Description

I read your document but i see this:

`To build your project for Apple TV, you should change your package.json imports to import react-native as follows, so that this package is used instead of the core react-native package.`

And if i use react-native cli not expo, how can i integrate this package to my project?

### React Native Version

0.72

### Output of `npx react-native info`

System:
  OS: macOS 13.3
  CPU: (8) arm64 Apple M2
  Memory: 191.00 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.19.0
    path: ~/.nvm/versions/node/v16.19.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 8.19.3
    path: ~/.nvm/versions/node/v16.19.0/bin/npm
  Watchman:
    version: 2023.07.10.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/tranhuynh/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.7
    wanted: 0.72.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

No

### Snack, screenshot, or link to a repository

No

**Comment by douglowder** [comment]
For the current (0.73) release:

```
react-native init MyProject --template=react-native-tvos
```

For 0.72,

```
react-native init MyProject --template=react-native-tvos@0.72.6-1
```

**Comment by huynhttdev** [comment]
How about update from existed project react-native-cli to react-native-tvos project bro? @douglowder 

Is update react-native package to npm:react-native-tvos@x.x.x right?

**Comment by douglowder** [comment]
That is correct.

**Comment by huynhttdev** [comment]
How can I use react-native-fs for downloading files bro? @douglowder 

The docs of react-native-fs it not mention a guide to config with this project, because this project uses Kotlin instead of Java.

**Comment by douglowder** [comment]
@huynhttdev on Android TV with this repo, react-native-fs should work the same as in their instructions.
