### ISSUE TITLE
Conditional pod imports (per target) with the new architecture enabled

### ISSUE THREAD

**Issue by psysize** [react-native-tvos/react-native-tvos#617]
### Description

When trying to conditionally import pods which do not support tvOS but do support iOS with Fabric enabled, we end up with errors about missing symbols at build time:

```
Undefined symbols for architecture arm64:
  "_RNCWebViewCls", referenced from:
      _RCTThirdPartyFabricComponentsProvider in libReact-RCTFabric-tvOS.a(RCTThirdPartyFabricComponentsProvider.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

We were previously able to do this (without the new architecture) by excluding modules from auto-linking by placing them in `react-native.config.js` like so:

```
module.exports = {
  dependencies: {
    'react-native-webview': {
      platforms: {
        ios: null, // Pod added manually for iOS but not tvOS.
      },
    },
  },
};
```

We then imported the pod manually under the iOS (and not the tvOS) target:

```
target 'FabricApp' do
  config = use_native_modules!
  platform :ios, min_ios_version_supported

  use_react_native!(
  ...
  )

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'FabricAppTests' do
    inherit! :complete
    # Pods for testing
  end

end
```

This method doesn't work with the new architecture enabled and instead produces the error above when trying to build for tvOS.

Unfortunately I'm not well versed with C or Ruby but I've tried a few different scenarios to no avail, including adding support for tvOS in the module's `.podspec` and wrapping non compatible parts of the module with the `!TARGET_OS_TV` condition.

Any workaround, patch or fix is welcome, thanks for your help and contribution so far and in advance for any support.

### React Native Version

0.73.0-0

### Output of `npx react-native info`

```
System:
  OS: macOS 13.6.2
  CPU: (10) arm64 Apple M1 Pro
  Memory: 81.61 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.0
    path: ~/.nvm/versions/node/v18.18.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v18.18.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /var/folders/gs/wnwnx8351wb7lm9n6bftp8wh0000gn/T/frum_38699_1701944311250/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.18
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /var/folders/gs/wnwnx8351wb7lm9n6bftp8wh0000gn/T/frum_38699_1701944311250/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.73.0-0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Steps to reproduce

1. Create a new project

```
yarn create react-native-app FabricApp --template https://github.com/react-native-tvos/react-native-template-typescript-tv/tree/tv-release-0.73.0 --template-path template
```

2. Add an iOS only module:

```
yarn add react-native-webview
```

3. Exclude the module from autolinking:

```
module.exports = {
  dependencies: {
    // Required for Expo CLI to be used with platforms (such as Apple TV) that are not supported in Expo SDK
    expo: {
      platforms: {
        android: null,
        ios: null,
        macos: null,
      },
    },
    'react-native-webview': {
      platforms: {
        ios: null, // Pod added manually for iOS but not tvOS.
      },
    },
  },
};
```

4. Add the module to the iOS but **not** the tvOS target in `ios/Podfile`.
```
target 'FabricApp' do
  config = use_native_modules!
  platform :ios, min_ios_version_supported

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'FabricAppTests' do
    inherit! :complete
    # Pods for testing
  end

end
```

5. Install pods with the new architecutre enabled:

```
RCT_NEW_ARCH_ENABLED=1 bundle exec pod install
```

6. Attempt to build the app for tvOS in xCode. The build should fail with the following error:

```
Undefined symbols for architecture arm64:
  "_RNCWebViewCls", referenced from:
      _RCTThirdPartyFabricComponentsProvider in libReact-RCTFabric-tvOS.a(RCTThirdPartyFabricComponentsProvider.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Undefined symbol: _RNCWebViewCls

Linker command failed with exit code 1 (use -v to see invocation)
```

7. Build iOS using xCode without issues

_I ran into a separate issue with 0.73 iOS and `react-native-webview` about `yoga/style/Style.h` not found which I worked after following [this advice](https://github.com/react-native-webview/react-native-webview/issues/3218#issuecomment-1805203710)._

### Snack, code example, screenshot, or link to a repository

_See basic steps to reproduce._

**Comment by douglowder** [comment]
@psysize I have discovered a related issue with missing symbols. This seems to occur only when there are two targets in the app's Podfile, targeting different platforms.

Please try commenting out the iOS target in your Podfile, then build for tvOS and see if the error is resolved.

**Comment by psysize** [comment]
@douglowder - I tried but ended up with the same result, seems like fabric scripts (Codegen?) is still processing the module regardless of if the module is listed as null in `react-native.config.js`.

**Comment by douglowder** [comment]
Ah I just noticed... in your `react-native.config.js`, you should have `tvos: null` for webview, not `ios: null`. If this does not fix the problem, please let me know and I will reopen this issue.

**Comment by psysize** [comment]
@douglowder Amazing, thanks that's solved it.

Never knew we could use `tvos` in the `react-native.config.js`, I guess it's a new thing?

I'll try see if I can write up some docs about it and maybe platform targeting.
