### ISSUE TITLE
Not working with expo-file-system packages

### ISSUE THREAD

**Issue by huynhttdev** [react-native-tvos/react-native-tvos#618]
### Description

If I init expo project as the react native docs mentioned, `expo-file-system` packages will work fine.
But I use [this](https://github.com/react-native-tvos/react-native-tvos/issues/616#issuecomment-1844118137) to init project `expo-file-system`  not working

### React Native Version

npm:react-native-tvos@0.72.6-1

### Output of `npx react-native info`

System:
  OS: macOS 13.3
  CPU: (8) arm64 Apple M2
  Memory: 99.05 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.6.6
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/tranhuynh/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/tranhuynh/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.72.6-1
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

No

### Snack, screenshot, or link to a repository

No

**Comment by douglowder** [comment]
Expo packages are not yet supported for TV, but this feature is being actively worked on. See #614 .
