### ISSUE TITLE
Missing symbols and experimental inspector broken when both iOS and tvOS targets present in Podfile

### ISSUE THREAD

**Issue by douglowder** [react-native-tvos/react-native-tvos#619]
### Description

If both iOS and tvOS targets are present, as in the Podfile for the standard template in this repo, the app will build successfully, but certain symbols (including hermes debugger) seem to not be linked in, leading to at least two issues:

1) The new experimental debugger does not work.
2) react-native-reanimated (3.6.0 and above) will break compilation if it is included in the build, due to missing symbols.

### React Native Version

0.73.0-0

### Output of `npx react-native info`

See repro steps

### Steps to reproduce

Create a new app:
```
yarn create react-native-app TVHermesDebuggerIssue -template https://github.com/react-native-tvos/react-native-template-typescript-tv/tree/tv-release-0.73.0 --template-path template
```

In a separate window, start the packager with the experimental debugger:
```
npx react-native start --experimental-debugger
```

Build and start the app in the first window:
```
yarn tvos
```

In the packager window, press `j` to invoke the debugger. It will fail with `No compatible apps connected`.

Now comment out the iOS target in the Podfile, and then do
```
rm -rf ios/build ios/Pods ios/Podfile.lock
npx pod-install
yarn tvos
```

Now press `j` in the packager window again. It will succeed.

### Snack, screenshot, or link to a repository

See above

**Comment by douglowder** [comment]
After discussion, we have decided to implement a (hopefully temporary) workaround, and comment out the iOS target in the template Podfile. We recommend that developers who encounter this issue do the same in their application Podfiles.

**Comment by douglowder** [comment]
@henninghall "prebuild" is exactly the right word 😀 The new support for Expo apps modifies the Podfile and project for TV through a config plugin. So multiple targets are not needed in the Podfile. https://github.com/react-native-tvos/react-native-tvos/blob/tvos-v0.73.0/README.md#new-using-the-expo-sdk-with-tv-apps

**Comment by douglowder** [comment]
Unfortunately solving the root cause would be potentially very complex, with changes needed in React Native core code, and Expo code as well.

**Comment by henninghall** [comment]
Okay thanks. Do I understand correctly that this might affect a large portion of the users who are not using Expo, everyone that have multiple targets? Maybe we can try develop a recommended "plugin" or prebuild script for the non-expo projects too? 

Here is my work in progress solution. I am trying to avoid different podfiles or modifying files if possible. 
<details>
<summary>Podfile</summary>

```rb

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

source 'https://github.com/react-native-community/react-native-tvos-podspecs.git'
source 'https://cdn.cocoapods.org/'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

os = ENV['OS']

if os == 'tvos'
  platform :tvos, min_ios_version_supported
  prepare_react_native_project!

  target 'Project-tvOS' do

    config = use_native_modules!

    use_react_native!(
      :path => config[:reactNativePath],
      # An absolute path to your application root.
      :app_path => "#{Pod::Config.instance.installation_root}/.."
    )

    # your other libraries will follow here!

    post_install do |installer|
      # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
      react_native_post_install(
        installer,
        config[:reactNativePath],
        :mac_catalyst_enabled => false
      )

    end
  end

elsif os == 'ios'
  platform :ios, min_ios_version_supported
  prepare_react_native_project!

  target 'Project' do

    config = use_native_modules!

    use_react_native!(
      :path => config[:reactNativePath],
      # An absolute path to your application root.
      :app_path => "#{Pod::Config.instance.installation_root}/.."
    )

    # your other libraries will follow here!
    
    post_install do |installer|
      # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
      react_native_post_install(
        installer,
        config[:reactNativePath],
        :mac_catalyst_enabled => false
      )
    end

  end

elsif os == nil
  raise "Missing OS env variable"
else
  raise "Unknown OS: #{os}"
end


```

</details>

Then installing pods with
`OS=ios pod install` or equivalent

**Comment by istvan-szilagyi** [comment]
Hello!

And what can you do if you have both targets (iOS/tvOS) and you need to use a package which only works for mobile (not for TV) like react-native-webview?

I'm getting an error at pod installation, that:

```
[!] The platform of the target `XXX-tvOS` (tvOS 15.1) is not compatible with `react-native-webview (13.12.3)`, which does not support `tvOS`.
```

I also tried @henninghall 's solution and when installing with OS=ios all good, but with OS=tvos same error occurs.

Thanks in advance!

**Comment by istvan-szilagyi** [comment]
Had time to focus on this, and could fix by patching react-native (more exactly script that is installing the pods)

Script was generated for 0.76.3, but works for 0.77.0 and 0.77.1 as well (haven't tried newer versions)

`diff --git a/node_modules/react-native/scripts/cocoapods/autolinking.rb b/node_modules/react-native/scripts/cocoapods/autolinking.rb
index b2e5600..f4d5ecd 100644
--- a/node_modules/react-native/scripts/cocoapods/autolinking.rb
+++ b/node_modules/react-native/scripts/cocoapods/autolinking.rb
@@ -14,7 +14,7 @@ require_relative '../react_native_pods.rb'
 #
 # Parameters:
 # - config_command: the command to run to get the application's current config, e.g. ['npx', '@react-native-community/cli', 'config']
-def list_native_modules!(config_command)
+def list_native_modules!(skip, config_command)
 
   if !(config_command.is_a? Array and config_command.size > 0)
     Pod::UI.warn "Expected a list_native_modules! to be called with a config command", [
@@ -45,6 +45,11 @@ def list_native_modules!(config_command)
   packages.each do |package_name, package|
     next unless package_config = package["platforms"]["ios"]
 
+    if skipped_pod = skip.find { |package_name| package["name"].include? "#{package_name}" }
+      Pod::UI.notice "Skipping pods for: #{skipped_pod}"
+      next
+    end
+
     name = package["name"]
     podspec_path = package_config["podspecPath"]
     script_phases = package_config["scriptPhases"]
@@ -201,6 +206,6 @@ $default_command = ['node', '-e', "process.argv=['', '', 'config'];require('@rea
 # Parameters:
 # - config_command: the command to run to get the application's current config, e.g. ['npx', '@react-native-community/cli', 'config'],
 #                   you can override this if you'd like to avoid the dependency. e.g. ['cat', 'your_config.json']
-def use_native_modules!(config_command = $default_command)
-  return link_native_modules!(list_native_modules!(config_command))
+def use_native_modules!(skip = [], config_command = $default_command)
+  return link_native_modules!(list_native_modules!(skip, config_command))
 end`
