### ISSUE TITLE
Build fails after update to 0.73.0-0

### ISSUE THREAD

**Issue by pavel-krasnov** [react-native-tvos/react-native-tvos#620]
### Description

When I upgrade `react-native-tvos` to `0.73.0-0` in a clean project created with `npx react-native@latest init AwesomeProject`, I can't build the Android app anymore. See reproduction steps for a more detailed description.

### React Native Version

0.73.0-0

### Output of `npx react-native info`

System:
  OS: Linux 6.5 TUXEDO OS 2
  CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
  Memory: 17.93 GB / 30.76 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 18.19.0
    path: ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v18.19.0/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v18.19.0/bin/npm
  Watchman:
    version: 20231008.002904.0
    path: /usr/local/bin/watchman
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 3.0.2
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-tvos:
    installed: 0.73.0-0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

### Steps to reproduce

Run:

- `npx react-native@latest init AwesomeProject`
- `cd AwesomeProject`
- `npm i`
- `cd android`
- `./gradlew assembleRelease`

Everything works as intended.

- Open `package.json`
- Replace `"react-native": "0.73.0"` to `"react-native": "npm:react-native-tvos@0.73.0-0"`
- run `npm i` in the root of the project
- run `./gradlew assembleRelease` under the `android` folder.

Get this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalReportRelease'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not find com.facebook.react:flipper-integration:.
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2s
5 actionable tasks: 5 up-to-date
```

### Snack, screenshot, or link to a repository

https://github.com/pavel-krasnov/react-native-tvos-bug

**Comment by douglowder** [comment]
As stated in the release notes, Flipper support has been removed from this repo in the 0.73 release. You should remove the Flipper dependency from `android/app/build.gradle`, and you should also remove the Flipper import and invocation in `MainApplication.kt`. Then your app will build as expected.
