### ISSUE TITLE
Build fails after upgrading to 0.73.0-0

### ISSUE THREAD

**Issue by maciejsiiminski** [react-native-tvos/react-native-tvos#621]
### Description

After upgrading the version of this repo from 0.72.6-1 to 0.73.0-0 I cannot build the app. Build fails with error: 
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileTvDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:tvDebugCompileClasspath'.
   > Could not find com.facebook.react:react-android:0.73.0-0.
     Required by:
         project :app
   > Could not find com.facebook.react:hermes-android:0.73.0-0.
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installTvDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wr
ong: Could not determine the dependencies of task ':app:compileTvDebugJavaWithJavac'. > Could not resolve all task dependencies for configuration ':app:tvDebugCompileClasspath'. > Coul
d not find com.facebook.react:react-android:0.73.0-0. Required by: project :app > Could not find com.facebook.react:hermes-android:0.73.0-0. Required by: project :app * Try: > Run with
 --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.
org BUILD FAILED in 33s.
```

### React Native Version

0.73.0-0

### Output of `npx react-native info`

System:
  OS: Windows 10 10.0.19045
  CPU: "(8) x64 AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  "
  Memory: 997.50 MB / 5.95 GB
Binaries:
  Node:
    version: 21.4.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.18
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 10.2.4
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
  Visual Studio:
    - 17.6.33723.286 (Visual Studio Community 2022)
Languages:
  Java:
    version: 11.0.16.1
    path: C:\Program Files\Microsoft\jdk-11.0.16.101-hotspot\bin\javac.EXE
  Ruby:
    version: 3.1.2
    path: C:\Ruby31-x64\bin\ruby.EXE
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-tvos:
    installed: 0.73.0-0
    wanted: 0.72.6-0
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

Upgrade this repo to the latest, but I am unsure if this is my project-specific or not.

### Snack, screenshot, or link to a repository

Cannot share the repo because I am not allowed by my employer.

**Comment by douglowder** [comment]
@maciejsiiminski there are going to be some changes in gradle scripts and application code in your app's android directory, as well as the change to the react native version.

I would recommend that you generate a new app with the same name using react-native or Expo CLI (see the README for instructions). Then check the differences in the android directory to see what's changed.
