### ISSUE TITLE
Error when migrating from official react native to forked version. missing m1 workarounds

### ISSUE THREAD

**Issue by silencer07** [react-native-tvos/react-native-tvos#625]
### New Version

react-native-tvos@0.73.0-0

### Old Version

react-native@0.72.6

### Build Target(s)

iPhone 15 Pro Max 17.2 Simulator

### New Version

react-native-tvos@0.73.0-0

### Old Version

react-native@0.72.6

### Build Target(s)

iPhone 15 Pro Max 17.2

### Output of `react-native info`

System:
  OS: macOS 14.2
  CPU: (10) arm64 Apple M2 Pro
  Memory: 742.25 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.1
    path: ~/.volta/tools/image/node/18.17.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.volta/tools/image/yarn/1.22.19/bin/yarn
  npm:
    version: 9.6.7
    path: ~/.volta/tools/image/node/18.17.1/bin/npm
  Watchman:
    version: 2023.10.09.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: ~/.sdkman/candidates/java/current/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.73.0-0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

info React Native v0.73.1 is now available (your project is running on v0.73.0-0).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.73.1
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.73.1
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".

### Issue and Reproduction Steps

I have an expo created project. basically I am doing all the builds locally, hence I am doing a "bare" workflow.

I am trying to move this fork as `react-native-tv-space-navigation` requires this. I also updated the deploymentTarget to `14.0`

However I am encountering this issue:

```
npx expo prebuild --clean

Command `pod install` failed.
└─ Cause: An error occurred while processing the post-install hook of the Podfile.

undefined method `__apply_Xcode_12_5_M1_post_install_workaround' for #<Pod::Podfile:0x0000000104a6ced0 @defined_in_file=#<Pathname:~/WebstormProjects/VideokePartyMaker/ios/Podfile>, @internal_hash={
....
```

### Issue and Reproduction Steps

- create a new expo project
- do a prebuild
- use the react-native-tvos fork
- encountered this error

**Comment by douglowder** [comment]
Please try the 0.73.1-0 release just published yesterday, which includes a dependency on the new SDK 50 preview.

Recommended steps:

```sh
yarn create expo-app MyNewProject -e with-tv
cd MyNewProject
export EXPO_TV=1
npx expo prebuild
yarn ios # build for Apple TV
yarn android # build for Android phone or TV
```

**Comment by silencer07** [comment]
Apologies for not reverting immediately @douglowder. I will definitely try the said build
