### ISSUE TITLE
Swipe is lost when navigating from a route to another.

### ISSUE THREAD

**Issue by ali-sao** [react-native-tvos/react-native-tvos#629]
### Description

Hello; 

I came across a very odd issue, where the swipe event is lost when navigating from one route to another. I witnessed this on Apple TV new remote (2nd/3rd generation with clickpad)

The interesting about this bug is that the swipe is being restored after clicking any 4D button on the click pad. 

I tried to console.log events with useTVEventHandler(handleTVEvent); and no events were captured unless I pressed a physical button. 

### React Native Version

0.72.6-0

### Output of `npx react-native info`

```
System:
  OS: macOS 13.6.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 126.12 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.yarn/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v18.19.0/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 14.0.1
    path: /Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.72.6-0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

I tried the examples folder and I was able to reproduce the issue when navigating from one view to another that has a focusable component. 

I am suspecting it has something to do with the react-native-screens w react-navigation  . I am using the following versions :

```
"@react-navigation/native": "^6.1.9",
 "@react-navigation/native-stack": "^6.9.17",
 "react-native-screens": "^3.29.0",
 "react-native": "npm:react-native-tvos@0.72.6-0",
```

### Snack, screenshot, or link to a repository

https://github.com/react-native-tvos/react-native-tvos/tree/9d339ee24020c0676500a93e151519256fac94fb/packages/rn-tester

**Comment by douglowder** [comment]
If you can provide an example repo where I can test this, that would be great.

I suspect that RNScreens might be overriding the swipe gesture handler when this type of navigation is enabled.....

**Comment by ali-sao** [comment]
I am not sure but I think it's [this](https://github.com/software-mansion/react-native-screens/pull/1867), I will prepare a demo for you to check while keep looking into the root cause. Thanks @douglowder

**Comment by ChadyAyoub4** [comment]
Experiencing the same bug, anything i can do to fix it? using react-navigation/native and native stack v6. also should not that pressing the play button on the remote restores the swipe as well.

**Comment by ali-sao** [comment]
Have you tried updating both, react-navigation and react-native-tvos @ChadyAyoub4 ? this has been eliminiated by only updating to the latest back then.

**Comment by ChadyAyoub4** [comment]
@ali-sao I have not, if there is shorter solutions i would like to use that otherwise i have no choice but to upgrade. Does anyone know it what commit this was fixed? Maybe i could use the changes instead of upgrading the project.

**Comment by prasad-r-g** [comment]
> @ali-sao I have not, if there is shorter solutions i would like to use that otherwise i have no choice but to upgrade. Does anyone know it what commit this was fixed? Maybe i could use the changes instead of upgrading the project.

Hi @ChadyAyoub4 did you find any alternate solution for this ...?

**Comment by ChadyAyoub4** [comment]
@prasad-r-g No unfortunately, i had to go for RN 0.73 on 2 apps to fix this one, upgrading was worth it however.

**Comment by prasad-r-g** [comment]
> @prasad-r-g No unfortunately, i had to go for RN 0.73 on 2 apps to fix this one, upgrading was worth it however.

@ChadyAyoub4 thanks for a quick reply..I will try upgrading

**Comment by prasad-r-g** [comment]
@douglowder making the upgrade makes minimum deployment target to 13.4 any workaround on this to support 13.0 as a minimum deployment target

**Comment by ChadyAyoub4** [comment]
@prasad-r-g  most Apple TVs should be running TVOS 17 or 16, unless you have a specific reason to keep it 13, there should be no reason not to increment the deployment target

**Comment by douglowder** [comment]
@prasad-r-g I concur with @ChadyAyoub4 , you should move to 13.4 or greater

**Comment by prasad-r-g** [comment]
Thankyou @ChadyAyoub4 and @douglowder
