### ISSUE TITLE
How can I start a new project without expo?

### ISSUE THREAD

**Issue by jomachh** [react-native-tvos/react-native-tvos#635]
### Description

I tried with 

`react-native init MyApp --template=react-native-tvos`

But it still installing the expo version.

### React Native Version

npm:react-native-tvos@0.73.1-3

### Output of `npx react-native info`

System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M1
  Memory: 117.39 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.1
    path: ~/.nvm/versions/node/v18.17.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.17.1/bin/yarn
  npm:
    version: 9.6.7
    path: ~/.nvm/versions/node/v18.17.1/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.73.1-3
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

### Steps to reproduce

run npx react-native init MyApp --template=react-native-tvos

### Snack, screenshot, or link to a repository

n/a

**Comment by douglowder** [comment]
The Expo CLI is installed by default. However, Expo SDK code will not be compiled into your app.

**Comment by lifwanian** [comment]
What's the purpose of using the Expo CLI? There's no way to set it up without it?

**Comment by douglowder** [comment]
@lifwanian it provides (in my opinion) a better experience for running the app when developing. I originally moved to using Expo CLI after there were some issues where the RN community CLI would not correctly run Apple TV apps.

However, you do not have to use it, and you can uninstall it with `yarn remove expo` and then modify the `scripts` section of `package.json` to use the RN community CLI.

**Comment by douglowder** [comment]
On the same subject as this issue, is the Expo doc on some of the features provided by Expo CLI that are not available in the community CLI: https://docs.expo.dev/bare/using-expo-cli/#why-expo-cli-instead-of-npx-react-native
