### ISSUE TITLE
Unable to listen to onLongPress event on Pressable component

### ISSUE THREAD

**Issue by sunzongzheng** [react-native-tvos/react-native-tvos#637]
### Description

The following code is an example. The onPress event can be monitored, but the onLongPress event cannot be monitored.
But it works well on iOS
```tsx
<Pressable onLongPress={() => console.log('onLongPress')} onPress={() => console.log('onPress')}>
  <Text style={{color: 'red', fontSize: 40}}>Long Press Button</Text>
</Pressable>
``` 

### React Native Version

0.73.1-3

### Output of `npx react-native info`

```text
System:
  OS: macOS 13.6
  CPU: (12) arm64 Apple M2 Pro
  Memory: 68.81 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.3
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11005911
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.8
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.73.1-3
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

just create a new project and add the following code
```tsx
<Pressable onLongPress={() => console.log('onLongPress')} onPress={() => console.log('onPress')}>
  <Text style={{color: 'red', fontSize: 40}}>Long Press Button</Text>
</Pressable>
```

### Snack, screenshot, or link to a repository

https://snack.expo.dev/@sunzongzheng/longpress

**Comment by douglowder** [comment]
Thanks for the bug report! Is this happening on Apple TV, Android TV, or both?

**Comment by sunzongzheng** [comment]
> Thanks for the bug report! Is this happening on Apple TV, Android TV, or both?

I just test Apple TV

**Comment by douglowder** [comment]
@sunzongzheng confirmed, this is reproducible. The issue is in the native view implementations for Apple TV, which were missing the required gesture recognizer for long presses.

You can apply the following patch to your project using `patch-package` or similar tools to fix the issue for both Fabric and non-Fabric builds.  I'll post a PR shortly.

```patch
diff --git a/node_modules/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm b/node_modules/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
index 1240dc5..dc8862f 100644
--- a/node_modules/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
+++ b/node_modules/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
@@ -51,7 +51,8 @@ using namespace facebook::react;
   BOOL _removeClippedSubviews;
   NSMutableArray<UIView *> *_reactSubviews;
   BOOL _motionEffectsAdded;
-    UITapGestureRecognizer *_selectRecognizer;
+  UITapGestureRecognizer *_selectRecognizer;
+  UILongPressGestureRecognizer * _longSelectRecognizer;
   NSSet<NSString *> *_Nullable _propKeysManagedByAnimated_DO_NOT_USE_THIS_IS_BROKEN;
   ParallaxProperties _tvParallaxProperties;
   BOOL _hasTVPreferredFocus;
@@ -249,6 +250,11 @@ using namespace facebook::react;
     [self sendNotificationWithEventType:@"select"];
 }
 
+- (void)sendLongSelectNotification:(UIGestureRecognizer *)recognizer
+{
+  [self sendNotificationWithEventType:@"longSelect"];
+}
+
 - (void)sendNotificationWithEventType:(NSString * __nonnull)eventType
 {
   [[NSNotificationCenter defaultCenter] postNotificationName:@"RCTTVNavigationEventNotification"
@@ -292,6 +298,11 @@ using namespace facebook::react;
   }
 }
 
+- (void)handleLongSelect:(__unused UIGestureRecognizer *)r
+{
+  [self sendLongSelectNotification:r];
+}
+
 - (void)addParallaxMotionEffects
 {
   if(!_tvParallaxProperties.enabled) {
@@ -887,11 +898,21 @@ using namespace facebook::react;
                                                                                    action:@selector(handleSelect:)];
       recognizer.allowedPressTypes = @[ @(UIPressTypeSelect) ];
       _selectRecognizer = recognizer;
+
+      UILongPressGestureRecognizer *longRecognizer = [[UILongPressGestureRecognizer alloc] initWithTarget:self action:@selector(handleLongSelect:)];
+      recognizer.allowedPressTypes = @[ @(UIPressTypeSelect) ];
+      [self addGestureRecognizer:longRecognizer];
+      _longSelectRecognizer = longRecognizer;
+
       [self addGestureRecognizer:_selectRecognizer];
+      [self addGestureRecognizer:_longSelectRecognizer];
     } else {
       if (_selectRecognizer) {
         [self removeGestureRecognizer:_selectRecognizer];
       }
+      if (_longSelectRecognizer) {
+        [self removeGestureRecognizer:_longSelectRecognizer];
+      }
     }
   }
   // `tvParallaxProperties
diff --git a/node_modules/react-native/React/Views/RCTTVView.m b/node_modules/react-native/React/Views/RCTTVView.m
index 519fbbf..7548279 100644
--- a/node_modules/react-native/React/Views/RCTTVView.m
+++ b/node_modules/react-native/React/Views/RCTTVView.m
@@ -22,6 +22,7 @@
 @implementation RCTTVView {
   __weak RCTBridge *_bridge;
   UITapGestureRecognizer *_selectRecognizer;
+  UILongPressGestureRecognizer * _longSelectRecognizer;
   BOOL motionEffectsAdded;
   NSArray* focusDestinations;
   id<UIFocusItem> previouslyFocusedItem;
@@ -79,11 +80,21 @@ RCT_NOT_IMPLEMENTED(-(instancetype)initWithCoder : unused)
                                                                                  action:@selector(handleSelect:)];
     recognizer.allowedPressTypes = @[ @(UIPressTypeSelect) ];
     _selectRecognizer = recognizer;
+
+    UILongPressGestureRecognizer *longRecognizer = [[UILongPressGestureRecognizer alloc] initWithTarget:self action:@selector(handleLongSelect:)];
+    recognizer.allowedPressTypes = @[ @(UIPressTypeSelect) ];
+    [self addGestureRecognizer:longRecognizer];
+    _longSelectRecognizer = longRecognizer;
+
     [self addGestureRecognizer:_selectRecognizer];
+    [self addGestureRecognizer:_longSelectRecognizer];
   } else {
     if (_selectRecognizer) {
       [self removeGestureRecognizer:_selectRecognizer];
     }
+    if (_longSelectRecognizer) {
+      [self removeGestureRecognizer:_longSelectRecognizer];
+    }
   }
 }
 
@@ -120,6 +131,11 @@ RCT_NOT_IMPLEMENTED(-(instancetype)initWithCoder : unused)
   }
 }
 
+- (void)handleLongSelect:(__unused UIGestureRecognizer *)r
+{
+  [self sendLongSelectNotification:r];
+}
+
 - (BOOL)isUserInteractionEnabled
 {
   return YES;
@@ -414,6 +430,11 @@ RCT_NOT_IMPLEMENTED(-(instancetype)initWithCoder : unused)
     [self sendNotificationWithEventType:@"select"];
 }
 
+- (void)sendLongSelectNotification:(UIGestureRecognizer *)recognizer
+{
+    [self sendNotificationWithEventType:@"longSelect"];
+}
+
 - (void)sendNotificationWithEventType:(NSString * __nonnull)eventType
 {
   [[NSNotificationCenter defaultCenter] postNotificationName:@"RCTTVNavigationEventNotification"
```

**Comment by sunzongzheng** [comment]
> @sunzongzheng confirmed, this is reproducible. The issue is in the native view implementations for Apple TV, which were missing the required gesture recognizer for long presses.
> 
> You can apply the following patch to your project using `patch-package` or similar tools to fix the issue for both Fabric and non-Fabric builds. I'll post a PR shortly.
> 
> ```diff
> diff --git a/node_modules/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm b/node_modules/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
> index 1240dc5..dc8862f 100644
> --- a/node_modules/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
> +++ b/node_modules/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
> @@ -51,7 +51,8 @@ using namespace facebook::react;
>    BOOL _removeClippedSubviews;
>    NSMutableArray<UIView *> *_reactSubviews;
>    BOOL _motionEffectsAdded;
> -    UITapGestureRecognizer *_selectRecognizer;
> +  UITapGestureRecognizer *_selectRecognizer;
> +  UILongPressGestureRecognizer * _longSelectRecognizer;
>    NSSet<NSString *> *_Nullable _propKeysManagedByAnimated_DO_NOT_USE_THIS_IS_BROKEN;
>    ParallaxProperties _tvParallaxProperties;
>    BOOL _hasTVPreferredFocus;
> @@ -249,6 +250,11 @@ using namespace facebook::react;
>      [self sendNotificationWithEventType:@"select"];
>  }
>  
> +- (void)sendLongSelectNotification:(UIGestureRecognizer *)recognizer
> +{
> +  [self sendNotificationWithEventType:@"longSelect"];
> +}
> +
>  - (void)sendNotificationWithEventType:(NSString * __nonnull)eventType
>  {
>    [[NSNotificationCenter defaultCenter] postNotificationName:@"RCTTVNavigationEventNotification"
> @@ -292,6 +298,11 @@ using namespace facebook::react;
>    }
>  }
>  
> +- (void)handleLongSelect:(__unused UIGestureRecognizer *)r
> +{
> +  [self sendLongSelectNotification:r];
> +}
> +
>  - (void)addParallaxMotionEffects
>  {
>    if(!_tvParallaxProperties.enabled) {
> @@ -887,11 +898,21 @@ using namespace facebook::react;
>                                                                                     action:@selector(handleSelect:)];
>        recognizer.allowedPressTypes = @[ @(UIPressTypeSelect) ];
>        _selectRecognizer = recognizer;
> +
> +      UILongPressGestureRecognizer *longRecognizer = [[UILongPressGestureRecognizer alloc] initWithTarget:self action:@selector(handleLongSelect:)];
> +      recognizer.allowedPressTypes = @[ @(UIPressTypeSelect) ];
> +      [self addGestureRecognizer:longRecognizer];
> +      _longSelectRecognizer = longRecognizer;
> +
>        [self addGestureRecognizer:_selectRecognizer];
> +      [self addGestureRecognizer:_longSelectRecognizer];
>      } else {
>        if (_selectRecognizer) {
>          [self removeGestureRecognizer:_selectRecognizer];
>        }
> +      if (_longSelectRecognizer) {
> +        [self removeGestureRecognizer:_longSelectRecognizer];
> +      }
>      }
>    }
>    // `tvParallaxProperties
> diff --git a/node_modules/react-native/React/Views/RCTTVView.m b/node_modules/react-native/React/Views/RCTTVView.m
> index 519fbbf..7548279 100644
> --- a/node_modules/react-native/React/Views/RCTTVView.m
> +++ b/node_modules/react-native/React/Views/RCTTVView.m
> @@ -22,6 +22,7 @@
>  @implementation RCTTVView {
>    __weak RCTBridge *_bridge;
>    UITapGestureRecognizer *_selectRecognizer;
> +  UILongPressGestureRecognizer * _longSelectRecognizer;
>    BOOL motionEffectsAdded;
>    NSArray* focusDestinations;
>    id<UIFocusItem> previouslyFocusedItem;
> @@ -79,11 +80,21 @@ RCT_NOT_IMPLEMENTED(-(instancetype)initWithCoder : unused)
>                                                                                   action:@selector(handleSelect:)];
>      recognizer.allowedPressTypes = @[ @(UIPressTypeSelect) ];
>      _selectRecognizer = recognizer;
> +
> +    UILongPressGestureRecognizer *longRecognizer = [[UILongPressGestureRecognizer alloc] initWithTarget:self action:@selector(handleLongSelect:)];
> +    recognizer.allowedPressTypes = @[ @(UIPressTypeSelect) ];
> +    [self addGestureRecognizer:longRecognizer];
> +    _longSelectRecognizer = longRecognizer;
> +
>      [self addGestureRecognizer:_selectRecognizer];
> +    [self addGestureRecognizer:_longSelectRecognizer];
>    } else {
>      if (_selectRecognizer) {
>        [self removeGestureRecognizer:_selectRecognizer];
>      }
> +    if (_longSelectRecognizer) {
> +      [self removeGestureRecognizer:_longSelectRecognizer];
> +    }
>    }
>  }
>  
> @@ -120,6 +131,11 @@ RCT_NOT_IMPLEMENTED(-(instancetype)initWithCoder : unused)
>    }
>  }
>  
> +- (void)handleLongSelect:(__unused UIGestureRecognizer *)r
> +{
> +  [self sendLongSelectNotification:r];
> +}
> +
>  - (BOOL)isUserInteractionEnabled
>  {
>    return YES;
> @@ -414,6 +430,11 @@ RCT_NOT_IMPLEMENTED(-(instancetype)initWithCoder : unused)
>      [self sendNotificationWithEventType:@"select"];
>  }
>  
> +- (void)sendLongSelectNotification:(UIGestureRecognizer *)recognizer
> +{
> +    [self sendNotificationWithEventType:@"longSelect"];
> +}
> +
>  - (void)sendNotificationWithEventType:(NSString * __nonnull)eventType
>  {
>    [[NSNotificationCenter defaultCenter] postNotificationName:@"RCTTVNavigationEventNotification"
> ```

Thanks,After applying this patch, LongPress events can be detected

**Comment by sunzongzheng** [comment]
@douglowder I discovered a small problem. If a pop-up window pops up using `Alert.alert` after a LongPress event is detected, a LongPress event will be detected again after the button is released. According to my understanding, after the first pop-up window appears, `Pressable` should lose focus, and a LongPress event should not be detected when the key is released.

**Comment by douglowder** [comment]
I was always getting a second event when the button was released... I'll look into that

**Comment by douglowder** [comment]
@sunzongzheng I have edited the patch above to fix the issue. It is not a focus issue, it was ensuring that the gesture recognizer only fires events at the start of the press, not at the end. Note the change to the `handleLongSelect` method.
