### ISSUE TITLE
Receiving long press event even if it was a normal press

### ISSUE THREAD

**Issue by sharan-SKY** [react-native-tvos/react-native-tvos#650]
### Description

We have the below useTVEventHandler hook where we tap into select and longpress event for appropriate functionalities in our app. When I press ok from my RCU, the long select switch case gets called too along with select everytime. I am not sure if this is a bug from the library 

### React Native Version

0.68.2-7

### Output of `npx react-native info`

  npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 94.63 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    Watchman: 2023.09.18.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/sergioturcheniuk/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      Android NDK: 21.1.6352462
  IDEs:
    Android Studio: 2023.1 AI-231.9392.1.2311.11255304
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.2-7 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

```
useEffect(() => {
    if (listenEvents && tvEventHandler instanceof TVEventHandler) {
      tvEventHandler.enable(this, (_: any, evt: { eventType: string; eventKeyAction: number }) => {
        console.log(evt.eventType, ' ==== ', evt.eventKeyAction);
        switch (evt.eventType) {
          case 'select': {
            console.log(
              '================== select was triggered which is weird: ',
              evt.eventKeyAction
            );
            break;
          }
          case 'longSelect': {
            console.log(
              '================== longSelect was triggered which is weird: ',
              evt.eventKeyAction
            );
            break;
          }
        }
      });
    } else {
      disableEvents();
    }
    return () => {
      disableEvents();
    };
  }, [
    listenEvents,
    disableEvents,
    tvEventHandler,
  ]);
```

### Snack, screenshot, or link to a repository

 
![image](https://github.com/react-native-tvos/react-native-tvos/assets/83677992/9feb6928-e318-42bb-b44f-742e7d28f46a)

**Comment by douglowder** [comment]
There have been quite a few fixes in this area recently, I would suggest updating to 0.73.2-0 and see if this problem still occurs. Is this happening on Apple TV or Android TV?

**Comment by sharan-SKY** [comment]
@douglowder this is in android tv

**Comment by sharan-SKY** [comment]
Unfortunately its not an easy one to upgrade to new version especially if you project has 20 developers working on so this might be out of question for a while. On further check, we have this flag enabled which is why longSelect gets called

`ReactFeatureFlags.enableKeyDownEvents = true;`

but interestingly select event doesnt not receive key down event so the tvevent handler received longselect instead....i wonder if anyone had a workaround to make long press work with `enableKeyDownEvents` as true?

**Comment by douglowder** [comment]
Unfortunately we are not able to support this in older versions of this repository.

**Comment by bilalhameed1** [comment]
Hey there, @douglowder,
I'm using 0.73.2-0 but still facing the same issue. I'm unable to use onLongPress prop of Pressable only on Android TV. On Apple TV, it's working perfectly fine.
When I try to fire long press, it is still treated as a normal press.
