### ISSUE TITLE
 "Native module not found" How to skip any dependency from TVOS target 

### ISSUE THREAD

**Issue by SrinivasanKannan18** [react-native-tvos/react-native-tvos#655]
### Description

I'm using notifee for push notifications in mobile not for tvos. But everytime the TVOS native modules search for the notifee dependency and its throw an error

"Notifee Native module not found"

I need to skip the specific dependency native modules while use_native_modules! execution for tvos target. If Is it possible to skip then share your thoughts.

### React Native Version

0.72.6-1

### Output of `npx react-native info`

---

### Steps to reproduce

Install Notifee for mobile and run the tvos target. 
It throws the above error.

### Snack, screenshot, or link to a repository

<img width="1042" alt="Screenshot 2024-02-05 at 11 03 49 AM" src="https://github.com/react-native-tvos/react-native-tvos/assets/55490094/b16e4fb1-999f-4fab-ae9e-6815d03893e0">

**Comment by SrinivasanKannan18** [comment]
@shergin Any idea to skip the native module that is required for mobile not for tvos?

**Comment by douglowder** [comment]
This is supported in Expo modules via the `platforms` attribute in `expo-module.config.json`. I don't know if this is possible in non-Expo projects. https://docs.expo.dev/modules/module-config/
