### ISSUE TITLE
Incomplete documentation of react-native-tvos error onFocus/onBlur

### ISSUE THREAD

**Issue by IvanJRCH** [react-native-tvos/react-native-tvos#674]
### Description

Hi, I have followed the react-native-tvos documentation https://github.com/react-native-tvos/react-native-tvos for my app with expo and I have also followed this https://docs.expo. dev /guides/building-for-tv/ but as much as I followed their documentation and followed all the steps, the onFocus/onBlur code in Pressable and any others didn't work, my goal was Android TV, not Apple.

I also didn't have access to this import {TVEventHandler, useTVEventHandler} from 'react-native'; I tried many configurations and nothing worked, at one point it worked miraculously in some test, without having done anything different.

I decided to use the example provided by https://github.com/expo/examples/tree/master/with-tv as a template as suggested at https://docs.expo.dev/guides/building-for-tv/ and everything worked perfectly, so after testing in many ways with both pure react-native and expo I came to the conclusion that the documentation they provide for react-native-tvos did not mention something very important for the configuration of the library because at the same time At the same time following the documentation just doesn't work, check out this guide https://github.com/react-native-tvos/react-native-tvos because following it makes projects just not work.

Below I mention how I followed the guide:

I followed the part that says it will add this "react-native": "npm:react-native-tvos@latest", I also followed the exposition guide for this configuration but I won't add it because it's not relevant to the case.

then I followed this part of adding this newArchEnabled=true

I didn't follow the Metro setup because the guide implies it's optional, and I also didn't follow what's mentioned here "RNTester/PodfileRNTester/RNTesterPods.xcodeprojpod installRNTesterPods.xcworkspace"

It should be noted that in one of my tests it worked miraculously following only "react-native": "npm:react-native-tvos@latest", and newArchEnabled=true and hazta without newArchEnabled=true, but not in every new project. . . I couldn't get it to work, just using the template worked.

So check the guide because it is not very clear or some settings are missing.

**Comment by douglowder** [comment]
If you are planning to build your app with Expo SDK support, you should be following the steps in

https://docs.expo.dev/guides/building-for-tv/

Specifically, I would recommend creating your project this way:

```
yarn create expo-app MyProject -e with-tv
```

If you do that, the project will already have the correct dependency on react-native-tvos, and you won't have to make any changes to package.json.

Then you just do

```
cd MyProject
export EXPO_TV=1
npx expo prebuild --clean
yarn android --device tv_api_31
```

where `tv_api_31` should be replaced with the name of your Android TV emulator.

Here's a quick Typescript example showing the use of `Pressable` and `useTVEventHandler` on the TV. On Android, the TV event handler will not work unless there is at least one focusable component rendered (i.e. `Pressable`, `Touchable`, `TextInput`, etc.) Examples are included for using `onFocus` and `onBlur `handlers in a `Pressable`, and how to use the `pressed` and `focused` properties to change the style and content of the `Pressable`.

```tsx
import {
  StyleSheet,
  Text,
  View,
  useTVEventHandler,
  Pressable,
} from 'react-native';
import { useState } from 'react';

export default function App() {
  const [eventType, setEventType] = useState('');
  useTVEventHandler((event) => {
    if (event.eventType !== 'focus' && event.eventType !== 'blur') {
      setEventType(event.eventType);
    }
  });

  return (
    <View style={styles.container}>
      <Text>Open up App.tsx to start working on your app!</Text>
      <Pressable
        onPress={() => setEventType('Button 1 pressed')}
        onFocus={() => console.log('Button 1 focused')}
        onBlur={() => console.log('Button 1 blur')}
        style={({ pressed, focused }) =>
          pressed || focused ? styles.buttonFocused : styles.button
        }
      >
        {({ focused }) => {
          return (
            <Text style={styles.buttonText}>
              {focused ? 'Button 1 focused' : 'Button 1'}
            </Text>
          );
        }}
      </Pressable>
      <Pressable
        onPress={() => setEventType('Button 2 pressed')}
        style={({ pressed, focused }) =>
          pressed || focused ? styles.buttonFocused : styles.button
        }
      >
        {({ focused }) => {
          return (
            <Text style={styles.buttonText}>
              {focused ? 'Button 2 focused' : 'Button 2'}
            </Text>
          );
        }}
      </Pressable>
      <Text>{eventType}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    borderColor: 'blue',
    backgroundColor: 'blue',
    borderWidth: 1,
    borderRadius: 10,
    margin: 10,
  },
  buttonFocused: {
    borderColor: 'blue',
    backgroundColor: '#000088',
    borderWidth: 1,
    borderRadius: 10,
    margin: 10,
  },
  buttonText: {
    color: 'white',
    fontSize: 30,
  },
});
```

**Comment by IvanJRCH** [comment]
Hello, thanks for answering, it was precisely "yarn create expo-app MyProject -e with-tv" that worked for me, but in an already made project if I want to use react-native-tvos it does not work, what could be the reason for this ? , because I follow the guide and it doesn't work, and it really is a big mystery to me, I would like to know what I did wrong?

**Comment by douglowder** [comment]
@IvanJRCH in order to help you, I would need you to provide a project that reproduces the issue. I need

- The project you started with
- The changes you made for TV
- What specifically does not work after you make the TV changes
