### ISSUE TITLE
Сan't add custom fonts, with using expo-font

### ISSUE THREAD

**Issue by donchop** [react-native-tvos/react-native-tvos#684]
### Description

After install 'empty' project with command from README and installing expo-font - got errors.
Also when adding expo-splash-screen have same errors but with splash

- WARN:The "EXNativeModulesProxy" native module is not exported through NativeModules; verify that expo-modules-core's native code is linked properly ,
- Error: Cannot find native module 'ExpoFontLoader',
- ERROR  TypeError: Cannot read property 'useFonts' of undefined
<img width="555" alt="Screenshot 2024-03-19 at 23 09 08" src="https://github.com/react-native-tvos/react-native-tvos/assets/14181533/e5c10886-8e62-449f-8925-f79df895c95a">
<img width="549" alt="Screenshot 2024-03-19 at 23 09 17" src="https://github.com/react-native-tvos/react-native-tvos/assets/14181533/ff8c03c1-6373-4b5a-a558-c033bc7a1133">

### React Native Version

0.73.2-0"

### Output of `npx react-native info`

System:
  OS: macOS 14.3
  CPU: (8) arm64 Apple M1
  Memory: 1.74 GB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.0/bin/npm
  Watchman:
    version: 2023.09.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 29.0.2
      - 29.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-29 | Google APIs ARM 64 v8a
      - android-29 | Google APIs Intel x86 Atom
      - android-30 | Google APIs ARM 64 v8a
      - android-31 | Android TV ARM 64 v8a
      - android-31 | Google TV ARM 64 v8a
      - android-31 | Google APIs ARM 64 v8a
      - android-31 | Google Play ARM 64 v8a
      - android-33 | Android TV ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google Play ARM 64 v8a
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9477386
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.73.2-0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

info React Native v0.73.6 is now available (your project is running on v0.73.2-0).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.73.6
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.73.6
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".

### Steps to reproduce

1. yarn create react-native-app TestApp --template https://github.com/react-native-tvos/react-native-template-typescript-tv/tree/tv-release-0.73.0 --template-path template
2. yarn add expo-font
3. download and add Roboto font to assets/fonts
4. add code App.ts   const [fontsLoaded] = useFonts({
    primary: require('./assets/fonts/Roboto-Regular.ttf'),
  });

### Snack, screenshot, or link to a repository

<img width="1082" alt="Screenshot 2024-03-19 at 23 13 02" src="https://github.com/react-native-tvos/react-native-tvos/assets/14181533/2641807b-7c31-4084-bcf7-21d39778b86c">

**Comment by aksamitsah** [comment]
same issue in xcode swift cant find custom font in list

**Comment by douglowder** [comment]
Your steps above are creating a React Native project which uses the Expo CLI, but without support for Expo SDK modules. 

If you are creating a new project, and wish to add `expo-font` or other Expo SDK modules, you should create an Expo project for TV: https://docs.expo.dev/guides/building-for-tv/

**Comment by donchop** [comment]
Understood, thanks. Already cut expo from the project, fonts works.
