### ISSUE TITLE
Undefined symbol: _RCTTVNavigationEventNotificationName

### ISSUE THREAD

**Issue by KrSerg** [react-native-tvos/react-native-tvos#704]
### New Version

0.73.6-2

### Old Version

0.73.6-1

### Build Target(s)

iOS

### Output of `react-native info`

System:
  OS: macOS 14.4.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 124.73 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.0/bin/npm
  Watchman:
    version: 2024.04.01.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9123335
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.18
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/serhiikrapivko/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.73.6-2
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Issue and Reproduction Steps

With the update to version 0.73.6-2, iOS stopped compiling with the error "Undefined symbol: _RCTTVNavigationEventNotificationName".
tvOS - works.

The file RCTTVNavigationEventNotificationConstants.m, in which the constant RCTTVNavigationEventNotificationName is declared, has not been added to the React-Core-iOS build. Is this the reason?

**Comment by douglowder** [comment]
Thanks for flagging the issue! Yes a change to the React-Core podspec should fix it. I'll have a look and provide a patch while I publish a new release.

**Comment by douglowder** [comment]
@KrSerg you can get the patch from the commit in #707 .

**Comment by KrSerg** [comment]
@douglowder, Great, thanks for the prompt!!
