### ISSUE TITLE
Every time when I need to find this repo I confused by search result, why title is "files"

### ISSUE THREAD

**Issue by retyui** [react-native-tvos/react-native-tvos#711]
### Description

<img width="902" alt="Screenshot 2024-04-23 at 14 27 10" src="https://github.com/react-native-tvos/react-native-tvos/assets/4661784/12589916-217f-4ead-b0ac-4b546e30c1b3">

### React Native Version

0.73.x

### Output of `npx react-native info`

....

### Steps to reproduce

...

### Snack, screenshot, or link to a repository

...

**Comment by douglowder** [comment]
Looking at the page source, I see

```xml
  <meta name="route-pattern" content="/:user_id/:repository" data-turbo-transient>
  <meta name="route-controller" content="files" data-turbo-transient>
  <meta name="route-action" content="disambiguate" data-turbo-transient>
```

so maybe that's the reason... maybe GitHub website admins would know more 😄
