### ISSUE TITLE
After upgrading from 0.66 to 0.73.6 i am getting build error on tvos 'React/RCTTVView.h' file not found

### ISSUE THREAD

**Issue by ChadyAyoub4** [react-native-tvos/react-native-tvos#714]
### New Version

0.73.6-3

### Old Version

0.64.2-2

### Build Target(s)

debug tvos target

### Output of `react-native info`

System:
  OS: macOS 14.3
  CPU: (10) x64 Apple M1 Pro
  Memory: 195.58 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.1
    path: ~/.nvm/versions/node/v18.19.1/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v18.19.1/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v18.19.1/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/chadyayoub/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11567975
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/chadyayoub/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.73.6-3
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

### Issue and Reproduction Steps

after upgrading i just run the project from xcode and i get build error 'React/RCTTVView.h' file not found. also xcode does not seem to find the reference to this import as when i cmd + click on #import <React/RCTTVView.h>, it does not take me to its reference.

**Comment by douglowder** [comment]
There are many things that might have gone wrong when upgrading from such an old version.

I would start by checking your project's Podfile against the one in the current template (`packages/react-native/template/ios/Podfile`) to make sure that it has been updated, and do a clean pod install.

**Comment by ChadyAyoub4** [comment]
> There are many things that might have gone wrong when upgrading from such an old version.
> 
> I would start by checking your project's Podfile against the one in the current template (`packages/react-native/template/ios/Podfile`) to make sure that it has been updated, and do a clean pod install.

Thank you, i was using the podfile that was in the react native main repo instead of the one in this repo after the upgrade, however now i am facing an issue with some pod installations, react-native-render-html used to work normally before the upgrade now whenever i try to do pod install i get this error: The platform of the target `appName-tvOS` (tvOS 12.0) is not compatible with `react-native-render-html (5.1.1)`, which does not support `tvOS`.

**Comment by ChadyAyoub4** [comment]
Thank you

**Comment by douglowder** [comment]
@ChadyAyoub4 I'm going to go ahead and close this issue... if you are still having problems, or have a minimal repo that reproduces the problem, please post here and I can reopen.

**Comment by ChadyAyoub4** [comment]
@douglowder The issue was as you mentionned i was using the podfile from upgrade helper which had 2 missing lines and installs pods for ios not tvos. it works now
