### ISSUE TITLE
useTVEventHandler missing 'playPause' event for tvOS

### ISSUE THREAD

**Issue by SPalkaDolby** [react-native-tvos/react-native-tvos#747]
### Description

Hi. 

Trying to useTVEventHandler to get the event 'playPause'. Unfortunately such an event is not sent when I click it on the controller.

### Steps to reproduce

1. Install React Native tvOS 0.73.7-0
2. Setup useTVEventHandler with callback
3. Look into events and try to click 'playPause' button on Apple Siri Remote from tvOS

### React Native Version

react-native-tvos@0.73.7-0

### Affected Platforms

Other (please specify)

### Output of `npx react-native info`

```text
Empty
```

### Stacktrace or Logs

```text
Empty
```

### Reproducer

 https://gist.github.com/SPalkaDolby/23eb9fb4098232e557e8fd8da62d536b

**Comment by douglowder** [comment]
I do not reproduce this issue on Apple TV. Which platform are you testing on?
You do need to extract the event type from the event (see code suggestion in your gist).
