### ISSUE TITLE
Performance Issue with Custom Styling on Focused TouchableOpacity in React Native TV

### ISSUE THREAD

**Issue by saadlatif75** [react-native-tvos/react-native-tvos#752]
### Description

I am experiencing a performance issue in my React Native TV application. When using TouchableOpacity for buttons, the default behavior of reducing opacity when a button is focused slows down the interface. I attempted to apply custom styling to focused buttons instead, but this resulted in significantly slower performance.
**here below i my code**
const YourComponent = ({ headers, item, channelPrograms, renderCol1, handlePress }) => {
  const [focusedItem, setFocusedItem] = useState(null);

  return (
    <View style={styles.rowContainer}>
      <View style={styles.cell}>{renderCol1(item.col1)}</View>
      {headers.map((headerItem, index) => {
        const program = channelPrograms.find(program => program.time === headerItem);
        const cellKey = `${item.key}-${index}`;
        const isFocused = focusedItem === cellKey;
        
        return (
          <TouchableOpacity
            key={index}
            activeOpacity={1}
            onPress={() => handlePress(program ? program : { message: 'No Program Found' })}
            onFocus={() => setFocusedItem(cellKey)}
            onBlur={() => setFocusedItem(null)}
            style={[styles.cell, isFocused && styles.focusedItem]}>
            <Text style={styles.textcel1}>
              {program ? program.title : 'No Program Found'}
            </Text>
          </TouchableOpacity>
        );
      })}
    </View>
  );
};

### Steps to reproduce

Create a button using TouchableOpacity.
Apply custom styling to the button when it is focused using the onFocus and onBlur events.
Navigate through the buttons to observe the performance.
Expected Behavior:
The buttons should smoothly change their style without causing a slowdown in the interface.

Actual Behavior:
When navigating through the buttons, the interface becomes noticeably slow, impacting the user experience.

### React Native Version

0.73.6-1

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: Windows 11 10.0.22631
  CPU: "(6) x64 AMD Ryzen 5 4500U with Radeon Graphics         "
  Memory: 1.05 GB / 15.40 GB
Binaries:
  Node:
    version: 18.19.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 8.19.3
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    Android NDK: 22.1.7171670
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    Versions:
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.8.34408.163 (Visual Studio Community 2022)
Languages:
  Java:
    version: 17.0.10
    path: C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-tvos:
    installed: 0.73.6-1
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

info React Native v0.74.3 is now available (your project is running on v0.73.6-1).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.74.3
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.74.3
info For more info, check out "https://reactnative.dev/docs/upgrading?os=windows".
```

### Stacktrace or Logs

```text
const YourComponent = ({ headers, item, channelPrograms, renderCol1, handlePress }) => {
  const [focusedItem, setFocusedItem] = useState(null);

  return (
    <View style={styles.rowContainer}>
      <View style={styles.cell}>{renderCol1(item.col1)}</View>
      {headers.map((headerItem, index) => {
        const program = channelPrograms.find(program => program.time === headerItem);
        const cellKey = `${item.key}-${index}`;
        const isFocused = focusedItem === cellKey;
        
        return (
          <TouchableOpacity
            key={index}
            activeOpacity={1}
            onPress={() => handlePress(program ? program : { message: 'No Program Found' })}
            onFocus={() => setFocusedItem(cellKey)}
            onBlur={() => setFocusedItem(null)}
            style={[styles.cell, isFocused && styles.focusedItem]}>
            <Text style={styles.textcel1}>
              {program ? program.title : 'No Program Found'}
            </Text>
          </TouchableOpacity>
        );
      })}
    </View>
  );
};
```

### Reproducer

https://github.com/react-native-community/discussions-and-proposals

### Screenshots and Videos

const YourComponent = ({ headers, item, channelPrograms, renderCol1, handlePress }) => {
  const [focusedItem, setFocusedItem] = useState(null);

  return (
    <View style={styles.rowContainer}>
      <View style={styles.cell}>{renderCol1(item.col1)}</View>
      {headers.map((headerItem, index) => {
        const program = channelPrograms.find(program => program.time === headerItem);
        const cellKey = `${item.key}-${index}`;
        const isFocused = focusedItem === cellKey;
        
        return (
          <TouchableOpacity
            key={index}
            activeOpacity={1}
            onPress={() => handlePress(program ? program : { message: 'No Program Found' })}
            onFocus={() => setFocusedItem(cellKey)}
            onBlur={() => setFocusedItem(null)}
            style={[styles.cell, isFocused && styles.focusedItem]}>
            <Text style={styles.textcel1}>
              {program ? program.title : 'No Program Found'}
            </Text>
          </TouchableOpacity>
        );
      })}
    </View>
  );
};

**Comment by douglowder** [comment]
If you want to apply styles based on focus, and do not need the opacity to change, I would recommend using `Pressable` instead. Both the style and children props can be functions that take "pressed" and "focused" as parameters. This way there is no need for a state like `focusedItem`, which will cause your entire list of items to be rerendered.

```tsx
function MyButton() {
  return <Pressable
      style={({ pressed, focused }) =>
        pressed || focused ? styles.pressableFocused : styles.pressable
      }
    >
      {({ focused }) => {
        return (
          <Text style={styles.pressableText}>
            {focused ? 'Focused button' : 'Non-focused button'}
          </Text>
        );
      }}
    </Pressable>;
}

**Comment by saadlatif75** [comment]
Thanks @douglowder
