### ISSUE TITLE
[FireTV] eventType of HWEvent can be null

### ISSUE THREAD

**Issue by retyui** [react-native-tvos/react-native-tvos#754]
### Description

I'm observing a runtime crashes (Users affected: 12) in the production on FireTV

```tsx
evt.eventType.startsWith('long')
// ^^^ Cannot read property 'startsWith' of null
```

Are we sure this TS type is correct?

https://github.com/react-native-tvos/react-native-tvos/blob/5c49447fae9bc0404d29544d038cabdc84788693/packages/react-native/types/public/ReactNativeTVTypes.d.ts#L50

### Steps to reproduce

...

### React Native Version

0.73.x

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
...
```

### Stacktrace or Logs

```text
Message: Forced crash due to unhandled javascript runtime error: Cannot read property 'startsWith' of null
```

### Reproducer

...

**Comment by douglowder** [comment]
That should not be possible. I would need to see more details of what RNTV version you are using, maybe an example repo.
