### ISSUE TITLE
[Android TV] onLongPress prop is not being fired for Pressable and TouchableOpacity, instead when long pressed it is treated as OnPress.

### ISSUE THREAD

**Issue by bilalhameed1** [react-native-tvos/react-native-tvos#758]
### Description

We are facing an issue where we want to perform an action on longPress of a pressable, but unable to do so in Android TV, but it's working perfectly fine on Apple TV.

### Steps to reproduce

<Pressable
          style={{
            width: 800,
            height: 100,
            backgroundColor: 'red',
            marginBottom: 20,
          }}
          onPress={() => {
            console.log('Pressable OnPress Called');
          }}
          onLongPress={() => {
            console.log('Pressable OnLongPress Called');
          }}></Pressable>

<TouchableOpacity
          style={{
            width: 800,
            height: 100,
            backgroundColor: 'green',
            marginBottom: 20,
          }}
          onPress={() => {
            console.log('TouchableOpacity OnPress Called');
          }}
          onLongPress={() => {
            console.log('TouchableOpacity OnLongPress Called');
          }}></TouchableOpacity>

### React Native Version

0.73.2-0

### Affected Platforms

Other (please specify)

### Output of `npx react-native info`

```text
System:
  OS: macOS 13.4
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 538.93 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.21
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.4
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.07.10.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 29.0.2
      - 30.0.3
      - 33.0.1
      - 34.0.0
    System Images:
      - android-30 | Android TV Intel x86 Atom
      - android-34 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11005911
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.73.2-0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
LOG  TouchableOpacity OnPress Called
 LOG  TouchableOpacity OnPress Called
 LOG  Pressable OnPress Called
 LOG  Pressable OnPress Called
```

### Reproducer

.

**Comment by douglowder** [comment]
Can you please move to release 0.73.7-0, or 0.74.3-0, and see if the problem is resolved?

**Comment by bilalhameed1** [comment]
Thanks. I have tried it with release 0.73.8-0, and it's working.
But it's firing two events on onLongPress, while on Apple TV one event is fired.
Is it due to the reason how useTvEventHandler detects longSelect?

**Comment by bilalhameed1** [comment]
Thanks. I have tried it with release 0.73.7-0, and it's working.
But it's firing two events on onLongPress, while on Apple TV one event is fired.
Is it due to the reason how useTvEventHandler detects longSelect?

**Comment by douglowder** [comment]
There actually should be two events for onLongPress, one at the start of the press, and one at the end.
