### ISSUE TITLE
TVEventControl.disableTVMenuKey() doesn't work

### ISSUE THREAD

**Issue by mCzolko** [react-native-tvos/react-native-tvos#767]
### Description

TVEventControl.disableTVMenuKey() seem like doesn't do what it should

### Steps to reproduce

call `TVEventControl.disableTVMenuKey()` and the menu key still works

### React Native Version

0.74.2

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.5
  CPU: (12) arm64 Apple M3 Pro
  Memory: 532.80 MB / 36.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v18.19.0/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v18.19.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 19.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.74.2-0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
none
```

### Reproducer

https://github.com/mCzolko/tvos-menu-key-disable

**Comment by douglowder** [comment]
I think this is a misunderstanding of what this API does.

`enableTVMenuKey()` sets up a gesture recognizer for menu key presses, so that if you are using a navigator like React Navigation, the menu key will pop the navigation stack instead of exiting the app.

`disableTVMenuKey()` does the opposite -- it removes the gesture recognizer so that a menu key press takes you out of the app and back to the home screen of the TV.

The menu key is "disabled" (no gesture recognizer) by default.

**Comment by mCzolko** [comment]
I'm sorry, thank you for the explanation

**Comment by samsonroyquickplay** [comment]
@douglowder I just wanted to little more knowledge on this

will the enableTVMenuKey() work when we are using `@react-navigation/native-stack` ? I see that it doesn't work when using native stack, can you help us understand why it doesnot work with native stack ?

Many thanks in advance!
