### ISSUE TITLE
my building is stuck on " [CP-User]\ Generate\ app.config\ for\ prebuilt\ Constants.manifest"

### ISSUE THREAD

**Issue by qzw881130** [react-native-tvos/react-native-tvos#768]
### Description

when i ran "npm run ios", it was still stuck on this spot.
![111](https://github.com/user-attachments/assets/bb3ff81a-fd56-4fd9-9624-a6abf07ce5cb)

then, i used xcode to build it. it was still so.

![2222](https://github.com/user-attachments/assets/4148d7b4-6040-4984-b1bb-b1f1debb3f34)

### Steps to reproduce

pls read my code.
[https://github.com/qzw881130/tv-demo](https://github.com/qzw881130/tv-demo)

➜  tv-demo git:(master) ✗ node -v
v20.14.0
Xcode Version 15.4 (15F31d)
MacBook Pro m1 16G
Simulator Apple TV tvos 17.5

i have tried many ways,

### React Native Version

"react-native": "npm:react-native-tvos@latest",

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
➜  tv-demo git:(master) ✗ npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 14.6.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 249.94 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.14.0
    path: ~/.nvm/versions/node/v20.14.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v14.14.0/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v20.14.0/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 3.2.0
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.74.2-0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

info React Native v0.75.1 is now available (your project is running on v0.74.2-0).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.75.1
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.74.2-0
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".
```

### Stacktrace or Logs

pls readme this log file.

[https://raw.githubusercontent.com/qzw881130/tv-demo/main/issue.txt](https://raw.githubusercontent.com/qzw881130/tv-demo/main/issue.txt)

### Reproducer

https://github.com/qzw881130/tv-demo

### Screenshots and Videos

![3333](https://github.com/user-attachments/assets/0749cce7-56f7-45f0-9ddb-cb5c0c17be7c)
I made some breakpoints, it can output.
![444](https://github.com/user-attachments/assets/4c68b1eb-8ead-4414-9df3-083473bdd293)

_No response_

**Comment by qzw881130** [comment]
oh my god!
i solved it finally.

[https://github.com/expo/expo/issues/15809](https://github.com/expo/expo/issues/15809)

it was caused by `.bash_profile`
i don't know why.
i just did so.
```
mv ~/.bash_profile ~/.bash_profile.bak
touch ~/.bash_profile
chmod a+x ~/.bash_profile
```

then, `npm run ios`.

it works.
![0000](https://github.com/user-attachments/assets/e18b20fd-e6b0-4367-ad39-6d19eebefd54)

**Comment by qzw881130** [comment]
another solved way.

search "bash " and "\n/bin/sh " in `./ios`
then, replace 
`bash ` => `bash --noprofile`
and
`\n/bin/sh` => `\n/bin/bash --noprofile`

so, executing shell won't load `~/.bash_profile`

![s1](https://github.com/user-attachments/assets/62066985-51ab-4cd2-bb1a-9f8002b8f13e)

**Comment by douglowder** [comment]
Thanks @qzw881130 I really appreciate your updates with the solutions you found!
