### ISSUE TITLE
RN core is removing tvOS support

### ISSUE THREAD

**Issue by dlowder-salesforce** [react-native-tvos/react-native-tvos#77]
The PR for this has just been submitted: https://github.com/facebook/react-native/pull/29407 .

Once this is merged, you will not be able to use the core `react-native` repo for building tvOS applications.

**Comment by NickAVolpe** [comment]
As always, Thanks for the update and your vigilant attention to this. It will be a careful dance for me to maintain my _beautiful_ tvos and android tv codebase haha.

**Comment by korziee** [comment]
Thanks @dlowder-salesforce. 

I wonder what the future of AndroidTV support in the core repository looks like. Can we expect it to make it into it's own `react-native-androidtv` repository, or is there a possibility that this fork becomes the home of all react-native tv platforms?

**Comment by andy-io** [comment]
react-native-tvos cannot be used to build an android tv application ?

**Comment by dlowder-salesforce** [comment]
Yes, this repo works for Android TV (it even has one bug fix that isn’t in core).
