### ISSUE TITLE
RTL scroll view blocks left and right focus

### ISSUE THREAD

**Issue by christianEconify** [react-native-tvos/react-native-tvos#808]
See [PR](https://github.com/react-native-tvos/react-native-tvos/pull/648#issuecomment-2447985932) that initially introduces this bug, I explain some details in the comment.

You can't focus left or right out of a horizontal flat list when the contentSize exceeds the viewableSize.

I will be adding more to this issue over the coming days, but would like to raise it as early as possible

React Native Version: >= 0.73
Platform: tvOS

RNTester reproducible [here](https://github.com/christianEconify/react-native-tvos/commit/a1600b67cc8855b30533d30a89bea46592015bc6)

Changing or removing this function to the following, fixes the issue

https://github.com/react-native-tvos/react-native-tvos/blob/729d7fa30e9046d6542b6a915f8be889d244444f/packages/react-native/React/Views/ScrollView/RCTScrollView.m#L1067

(for reference I am testing again 0.74 as this is what is being used on the project I am working on)

```objc
- (BOOL)shouldUpdateFocusInContext:(UIFocusUpdateContext *)context
{
    // Determine if the layout is Right-to-Left
    BOOL isRTL = [[RCTI18nUtil sharedInstance] isRTL];
    NSLog(isRTL ? @"isRTL" : @"isntRTL");
    // Adjust for horizontal scrolling with RTL support
    if ([self isHorizontal:self.scrollView]) {
        BOOL isNavigatingToEnd = (isRTL ? context.focusHeading == UIFocusHeadingLeft : context.focusHeading == UIFocusHeadingRight);
        BOOL isNavigatingToStart = (isRTL ? context.focusHeading == UIFocusHeadingRight : context.focusHeading == UIFocusHeadingLeft);
        
        if ((isNavigatingToEnd && self.scrollView.contentOffset.x < self.scrollView.contentSize.width - self.scrollView.visibleSize.width) ||
            (isNavigatingToStart && self.scrollView.contentOffset.x > 0)) {
            return [UIFocusSystem environment:self containsEnvironment:context.nextFocusedItem];
        }
    } else {
        // Handle vertical scrolling as before
        if ((context.focusHeading == UIFocusHeadingUp && self.scrollView.contentOffset.y > 0) ||
            (context.focusHeading == UIFocusHeadingDown && self.scrollView.contentOffset.y < self.scrollView.contentSize.height - self.scrollView.visibleSize.height)) {
            return [UIFocusSystem environment:self containsEnvironment:context.nextFocusedItem];
        }
    }
    
    return [super shouldUpdateFocusInContext:context];
}
```

**Comment by douglowder** [comment]
Fixed in #809
