### ISSUE TITLE
[AndroidTV] Pressable onBlur / onPress is not invoked inside a Modal

### ISSUE THREAD

**Issue by zsoltbokor** [react-native-tvos/react-native-tvos#832]
Hi,

I have couple of Pressables inside a Modal.
I've noticed that the `onFocus` of the `Pressable` is being invoked however when I request to move to focus (with remote control) to an other one, the `onFocus` is invoked on the newly focused button but the `onBlur` doesn't.
In addition looks like the `onPress` is also not invoked.

I am using version: 0.76.1 of the package.
Hermes enabled: true
New architecture enable: false

Please note, this was working in 0.74.3 (don't know about versions between this and latest)

Can this bug somehow related to https://github.com/react-native-tvos/react-native-tvos/issues/829 ? 

Thanks!

**Comment by istvan-szilagyi** [comment]
Hello!

This has been solved in v 0.76.2.

I can confirm it was not called on 0.76.1 indeed.
