### ISSUE TITLE
Pointer events "none"  not working in android

### ISSUE THREAD

**Issue by mehthabux** [react-native-tvos/react-native-tvos#84]
Pointer event "none" is not working in android, but working fine in tvOS. Well my issue is i have a react navigation modal which is a transparent modal. So when this navigation modal comes to focus all the touchable in the previous screen get focused when i try to make some action in current modal. I have also tried the enableScreens() from react-native-screens. So what i'm doing is i'm adding  a pointer events none when the stack looses its focus. So this is working fine and perfect in tvOS, but not in android.
And i'm adding pointer events none for a Flatlist which renders touchable items.

React Native version:
react-native-tvos: 0.62.2-1

## Steps To Reproduce

1. Add pointer events "none" to a view.
2. Try to get focus using directional pad, the touchable gets focused even if the parent is provided with pointer events none

## Expected behaviour 
Expected behaviour is touchable item shouldn’t focus if the parent view is provided with pointer events none

**Comment by dlowder-salesforce** [comment]
I'm surprised this works in tvOS.  Maybe this is a different scenario than #33 , which is a related issue. Can you post an example of what you are doing, that works in tvOS but not Android?

**Comment by mehthabux** [comment]
Sure will do! btw i'm running the tv in emulator. 
It’s s easy to reproduce, just have a bunch of touchableS in Flatlist , then give the Flatlist or its parent pointer events none. still you will be able to get the focus on the touchable item.
But i also tried a solution you mentioned previously ie giving both accessible false and disabled true, in that case touchable aren’t  getting focused. but still we can here that TAP SOUND in android emulator. So something is getting focused in the flatlist
This doesn’t happens in tvOS with pointer events none

**Comment by dlowder-salesforce** [comment]
I do see that a view can be made unfocusable by setting accessible false, from the code in `ReactViewManager.java`:

```java
/** View manager for AndroidViews (plain React Views). */
@ReactModule(name = ReactViewManager.REACT_CLASS)
public class ReactViewManager extends ReactClippingViewManager<ReactViewGroup> {
.
.
.
  @ReactProp(name = "accessible")
  public void setAccessible(ReactViewGroup view, boolean accessible) {
    view.setFocusable(accessible);
  }

```

But it might not be changing focusability in the child views.  Weird that you would hear the tap sounds even if the rows are not getting focused.  I'll try to set up a test case for this.

**Comment by NickAVolpe** [comment]
I've seen something similar but eventually gave up trying to figure it out. Oddly enough I noticed differences between horizontal and vertical flat lists. If you post an example @mehthabux I would also take a second crack at this.

**Comment by dlowder-salesforce** [comment]
@mehthabux I'm finding that setting pointerEvents="none" doesn't have any effect in tvOS.  It would be great if you could post a working example showing what you did, so I can test it on both Android and tvOS and see what is different.

**Comment by mehthabux** [comment]
sure let me create a demo project for this one and il share with you soon. I noticed these issues while working on an actual project.

**Comment by mehthabux** [comment]
@dlowder-salesforce 

> @mehthabux I'm finding that setting pointerEvents="none" doesn't have any effect in tvOS. It would be great if you could post a working example showing what you did, so I can test it on both Android and tvOS and see what is different.

@dlowder-salesforce Yes you are right, it doesn’t have effect in tvos in version 0.63.1 , but it has effect in version 0.62.2-1

**Comment by dlowder-salesforce** [comment]
Wow interesting.... will have to have a look at the diffs to see if I can spot what changed
