### ISSUE TITLE
Unable to build from source for android

### ISSUE THREAD

**Issue by christianEconify** [react-native-tvos/react-native-tvos#843]
## What
Unable to build android from source following method described in the react native [docs](https://reactnative.dev/contributing/how-to-build-from-source#update-your-project-to-build-from-source)

## Output error
```
build file `**/react-native/ReactAndroid/build.gradle.kts' line: 15

* What went wrong:
Plugin [id: 'com.facebook.react'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (No included builds contain this plugin)
- Plugin Repositories (plugin dependency must include a version number for this source)
```

I tried updating the id to match the group id for react-native-tvos but came across the same error with a different ID.

I also tried setting the substitute to 
```
substitute(module("io.github.react-native-tvos:react-android")).using(project(":packages:react-native:ReactAndroid"))
```
which also did not work

Expo version 51
React Native version 0.74.5

**Comment by douglowder** [comment]
I created a new Expo TV project using RNTV 0.76.5-0, executed prebuild to create the android directory, and then added these lines to the end of `android/settings.gradle`:

```gradle
includeBuild('../node_modules/react-native') {
    dependencySubstitution {
        substitute(module('io.github.react-native-tvos:react-android')).using(project(':packages:react-native:ReactAndroid'))
        substitute(module('com.facebook.react:react-android')).using(project(':packages:react-native:ReactAndroid'))
        substitute(module('com.facebook.react:react-native')).using(project(':packages:react-native:ReactAndroid'))

        substitute(module('io.github.react-native-tvos:hermes-android')).using(project(':packages:react-native:ReactAndroid:hermes-engine'))
        substitute(module('com.facebook.react:hermes-android')).using(project(':packages:react-native:ReactAndroid:hermes-engine'))
        substitute(module('com.facebook.react:hermes-engine')).using(project(':packages:react-native:ReactAndroid:hermes-engine'))
    }
}
```

With this change, build from source works correctly with Android Studio.

**Comment by codephoenix-design** [comment]
@douglowder @christianEconify 

We are having the exact same error. I feel like we are missing something. 

RN 0.74.5
Expo 51.0.31

settings.gradle

```java
//...
includeBuild('../node_modules/react-native') {
   dependencySubstitution {
         substitute(module('io.github.react-native-tvos:react-android')).using(project(':packages:react-native:ReactAndroid'))
         substitute(module('com.facebook.react:react-android')).using(project(':packages:react-native:ReactAndroid'))
         substitute(module('com.facebook.react:react-native')).using(project(':packages:react-native:ReactAndroid'))

         substitute(module('io.github.react-native-tvos:hermes-android')).using(project(':packages:react-native:ReactAndroid:hermes-engine'))
         substitute(module('com.facebook.react:hermes-android')).using(project(':packages:react-native:ReactAndroid:hermes-engine'))
         substitute(module('com.facebook.react:hermes-engine')).using(project(':packages:react-native:ReactAndroid:hermes-engine'))
   }
}
``` 

Error:
```
Plugin [id: 'com.facebook.react'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (None of the included builds contain this plugin)
- Plugin Repositories (plugin dependency must include a version number for this source)
``` 

Any help on this would be greatly appreciated.

**Comment by douglowder** [comment]
The dependency substitution in my comment above is sufficient for RNTV 0.76 and later. You are attempting this on RNTV 0.74.

**Comment by codephoenix-design** [comment]
Yes I'd like to upgrade, but we are seeing some major performance degradation (particularly in dev builds) and bugs introduced with the upgrade. 

We have to keep the newArch disabled too as core libraries are not updated yet. We are really just trying to cherry pick [this commit](https://github.com/facebook/react-native/commit/b4532adad4e38e1237631778f7b8c917a9ccf746) which is impacting thousands of our users right now.

I'm working through your solution unsuccessfully so far. 

Is there any simple way to just cherry pick a commit like this that you know?

**Comment by douglowder** [comment]
Ok I've applied this commit to tvos-v0.74.0 branch, you can pull it from there. For future commits, you can clone this branch, add the RN core repository URL as remote `upstream`, then `git fetch upstream`, and `git cherry-pick <commit id>`.

To build the Android native artifacts, you can execute

```
node scripts/releases/prepare-tv-release.js
```

at the top of the repo. After that, the artifacts will be in `/tmp/maven-local/io/github/react-native-tvos`.

You should be aware that RN 0.74 is out of the support window, as it is no longer maintained by the RN core team. If you are seeing regressions with later versions, have you already created issues here or in the core repo that identify what the problems are?

**Comment by codephoenix-design** [comment]
Thanks for the assistance on that! 

We are working through some tight feature deadlines right now, so we haven't been able to nail down exactly the cause yet. Once we can do that or at least get a good reproduction, we will submit those regressions. 

Thanks again for your help!
