### ISSUE TITLE
How to programmatically select and focus a touchable opacity component in tvOS ? 

### ISSUE THREAD

**Issue by jasmeet447** [react-native-tvos/react-native-tvos#87]
Hi, I've been trying to implement a screen on tvOS that has a lot of touchable opacity elements(say movie cards, list elements, etc) and I want to programmatically focus a particular element when some action is performed, say to programmatically select a particular touchable opacity element on back navigation.
I tried to implement hasTVPreferredFocus = {true}, but this property only focuses on the nearest focusable view from the top left corner of the screen, despite the item it was set to.
Any help would be appreciated.

**Comment by hufkens** [comment]
The property hasTVPreferredFocus is indeed the way to go. By default it will set the top left item focused, but you should be able to set it yourself in the list by only setting that property to true for the card you need focused. We do it like that.

**Comment by jasmeet447** [comment]
@hufkens, I do it like this way:
touchableRef.setNativeProps.({ hasTVPreferredFocus: true })
Still, the top-left view is selected irrespective of the touchableRef item I apply this code to.
I couldn't get what you're trying to say in your comment.

**Comment by hufkens** [comment]
We do it like this but that will only work on tvOS, and we have a wrapper class to handle the Android TV stuff:
```
const setHasTVPreferredFocus = viewTag => {
  NativeModules.UIManager.updateView(viewTag, 'RCTView', {
    hasTVPreferredFocus: true,
  });  
};
```
